{"metadata":{"title":"explicitLyricsFiltering","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"explicitLyricsFiltering"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)explicitLyricsFiltering","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"explicitLyricsFiltering"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/explicitLyricsFiltering","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"explicitLyricsFiltering","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstatus\/explicitlyricsfiltering"]},{"paths":["\/documentation\/automixiq\/automixsdkstatus\/explicitlyricsfiltering"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"title":"AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/explicitLyricsFiltering":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/explicitLyricsFiltering","navigatorTitle":[{"kind":"identifier","text":"explicitLyricsFiltering"}],"title":"explicitLyricsFiltering","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicitLyricsFiltering","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatus\/explicitlyricsfiltering"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Provide seamless transitions between tracks and beat-matched seek experience within your music player application in iOS, iPad."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"explicitLyricsFiltering","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"explicitLyricsFiltering","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"explicitLyricsFiltering"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","value":"AutomixSDKStatus","op":"replace"},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments"},{"op":"replace","value":"explicitLyricsFiltering","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1explicitLyricsFiltering\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1explicitLyricsFiltering\/fragments","value":[{"kind":"identifier","text":"explicitLyricsFiltering"}],"op":"replace"}]}]}