{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlaySkipped","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayskipped"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayskipped"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlaySkipped","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlaySkipped","roleHeading":"Case","role":"symbol","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlaySkipped","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"symbolKind":"case","title":"AutomixSDKPlaybackEventType.trackPlaySkipped"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlaySkipped":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlaySkipped","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlaySkipped"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayskipped","title":"AutomixSDKPlaybackEventType.trackPlaySkipped"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"title":"AutomixSDKPlaybackEventType","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]}]}]}