{"metadata":{"role":"symbol","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"title":"AutomixSDKPlaybackEventType.trackPlayHeartbeat30Secs","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayheartbeat30secs"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayheartbeat30secs"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"title":"AutomixSDKPlaybackEventType","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayHeartbeat30Secs":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayheartbeat30secs","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"abstract":[],"role":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayHeartbeat30Secs","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}