{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/init(from:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/artist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/availableMarkets","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/bpm","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/color","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/duration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/explicit","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/images","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/key","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/previewURL","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/service","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/title","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackBpm","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackExplicit","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackRef"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/Se","doc:\/\/org.cocoapods.PacemakerRadio\/SE","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"type":"conformsTo"}],"seeAlsoSections":[{"generated":true,"anchor":"Data-models","title":"Data models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"]}],"metadata":{"title":"AutomixSDKMixtapeTrack","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrack","symbolKind":"class","roleHeading":"Class"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/duration":{"title":"duration","role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/duration","abstract":[{"text":"The track duration","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Data-models-article":{"type":"topic","url":"\/documentation\/pacemakerradio\/data-models-article","kind":"article","abstract":[{"text":"How data is passed to and from PacemakerRadio","type":"text"}],"title":"Data models","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","role":"article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/trackRef":{"title":"trackRef","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackRef"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackref","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackRef","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackRef","abstract":[{"text":"The identifier for the track","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","type":"topic","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"title":"TunedAuthenticationResponse","url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/artist":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/artist","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"artist","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"artist","kind":"symbol","navigatorTitle":[{"text":"artist","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The artist name"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/artist"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"title":"AutomixSDKMixtapeTrack","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/key":{"title":"key","navigatorTitle":[{"kind":"identifier","text":"key"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/key","abstract":[{"text":"The key of the track","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"key","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/key"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","role":"symbol","title":"AutomixSDKWaveformModel","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/trackExplicit":{"title":"trackExplicit","role":"symbol","navigatorTitle":[{"text":"trackExplicit","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackexplicit","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackExplicit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackExplicit","abstract":[{"text":"True if this track has explicit content, false otherwise","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/init":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/init","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/explicit":{"title":"explicit","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/explicit","abstract":[{"text":"True if this track has explicit content, false otherwise","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"explicit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/explicit"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/images":{"title":"images","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"images"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/images","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"images","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AutomixSDKMixtapeTrackImage","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrackImage"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/images","abstract":[{"text":"The set of images available for this track","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/trackBpm":{"title":"trackBpm","navigatorTitle":[{"kind":"identifier","text":"trackBpm"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackbpm","abstract":[{"text":"The bpm of the track","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackBpm"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackBpm"},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKArtistModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"url":"\/documentation\/pacemakerradio\/automixsdkartistmodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","role":"symbol","title":"AutomixSDKArtistModel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/service":{"title":"service","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"service"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/service","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"service"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/service","abstract":[{"text":"The identifier for the type of track","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPluginMetadataModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"abstract":[{"text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"url":"\/documentation\/pacemakerradio\/automixsdkpluginmetadatamodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","role":"symbol","title":"AutomixSDKPluginMetadataModel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"title":"AutomixSDKMixtapeTrackImage","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","role":"symbol","title":"AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/title":{"abstract":[{"type":"text","text":"The title"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"title":"title","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/title","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/title"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/Se":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic","kind":"symbol","title":"PacemakerRadio","role":"collection","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","role":"symbol","title":"AutomixSDKMixtapeCounters"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformBlob":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformblob","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","role":"symbol","title":"AutomixSDKWaveformBlob"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/trackDuration":{"title":"trackDuration","role":"symbol","navigatorTitle":[{"text":"trackDuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackduration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDuration"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackDuration","abstract":[{"text":"The track duration","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/init(from:)":{"title":"init(from:)","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/init(from:)","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/init(from:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKList":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKList"}],"abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdklist","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","role":"symbol","title":"AutomixSDKList"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKUser":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKUser"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKUser"}],"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkuser","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","role":"symbol","title":"AutomixSDKUser"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/availableMarkets":{"title":"availableMarkets","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableMarkets"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/availablemarkets","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableMarkets"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/availableMarkets","abstract":[{"type":"text","text":"A list of ISO2 country codes where the track is playable"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/bpm":{"title":"bpm","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/bpm","abstract":[{"type":"text","text":"The bpm of the track"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpm"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/bpm"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/previewURL":{"title":"previewURL","role":"symbol","navigatorTitle":[{"text":"previewURL","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/previewurl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewURL"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/previewURL","abstract":[{"type":"text","text":"The URL of a sample sound for this track a s a string"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/color":{"title":"color","navigatorTitle":[{"text":"color","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/color","abstract":[{"type":"text","text":"The significant color of the artwork of this track as a string representation"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/color"},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeLite":{"abstract":[{"text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapelite","title":"AutomixSDKMixtapeLite"},"doc://org.cocoapods.PacemakerRadio/SE":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"title":"AutomixSDKTrackModel","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKMixtape models a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtape","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","role":"symbol","title":"AutomixSDKMixtape"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKGenericList":{"url":"\/documentation\/pacemakerradio\/automixsdkgenericlist","abstract":[{"text":"AutomixSDKGenericList models a list of things","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKGenericList","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKGenericList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","kind":"symbol","title":"AutomixSDKGenericList"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","role":"symbol","title":"AutomixSDKPlaylistOperation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixSDKMixtapeTrack","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/artist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/availableMarkets","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/color","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/images","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/key","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/previewURL","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/service","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/title","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackBpm","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackExplicit","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackRef"],"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/init"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"title":"Data models","anchor":"Data-models"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"value":"trackRef","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackRef\/title"},{"op":"replace","value":[{"kind":"identifier","text":"trackRef"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackRef\/fragments"},{"value":"TunedAuthenticationResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}]},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"value":"artist","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1artist\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1artist\/fragments","value":[{"kind":"identifier","text":"artist"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title","op":"replace","value":"AutomixSDKMixtapeTrack"},{"op":"replace","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments"},{"value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1key\/title","op":"replace","value":"key"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1key\/fragments","value":[{"text":"key","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackExplicit\/title","op":"replace","value":"trackExplicit"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackExplicit\/fragments","value":[{"kind":"identifier","text":"trackExplicit"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1images\/title","value":"images"},{"value":[{"kind":"identifier","text":"images"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1images\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackBpm\/title","value":"trackBpm","op":"replace"},{"op":"replace","value":[{"text":"trackBpm","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackBpm\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/title","value":"AutomixSDKArtistModel","op":"replace"},{"value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/navigatorTitle","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1service\/title","value":"service"},{"value":[{"text":"service","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1service\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/title","value":"AutomixSDKPluginMetadataModel"},{"value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle","value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title","value":"AutomixSDKMixtapeTrackImage","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments","value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"value":"title","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1title\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1title\/fragments","op":"replace","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","value":"AutomixSDKMixtapeCounters","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},{"op":"replace","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/navigatorTitle","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackDuration\/title","op":"replace","value":"trackDuration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackDuration\/fragments","value":[{"text":"trackDuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/title","value":"AutomixSDKList","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/fragments","value":[{"text":"AutomixSDKList","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKList"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/title","value":"AutomixSDKUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/fragments","value":[{"kind":"identifier","text":"AutomixSDKUser"}]},{"op":"replace","value":[{"text":"AutomixSDKUser","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/navigatorTitle"},{"value":"availableMarkets","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1availableMarkets\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1availableMarkets\/fragments","op":"replace","value":[{"text":"availableMarkets","kind":"identifier"}]},{"value":"previewURL","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1previewURL\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1previewURL\/fragments","op":"replace","value":[{"text":"previewURL","kind":"identifier"}]},{"op":"replace","value":"color","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1color\/title"},{"value":[{"text":"color","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1color\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/title","value":"AutomixSDKMixtapeLite"},{"value":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title","value":"AutomixSDKMixtape"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments","op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","op":"replace"}]}]}