{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"abstract":[{"type":"text","text":"How data is passed to and from PacemakerRadio"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/data-models-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/data-models-article"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"PacemakerRadio"}],"title":"Data models"},"seeAlsoSections":[{"generated":true,"title":"Data models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"anchor":"Data-models"}],"primaryContentSections":[{"content":[{"anchor":"Data-Models","type":"heading","text":"Data Models","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","type":"reference","isActive":true}]}]}]}],"kind":"content"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformBlob":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformblob","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","role":"symbol","title":"AutomixSDKWaveformBlob"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"title":"AutomixSDKTrackModel","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","type":"topic","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"title":"TunedAuthenticationResponse","url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPluginMetadataModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"abstract":[{"text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"url":"\/documentation\/pacemakerradio\/automixsdkpluginmetadatamodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","role":"symbol","title":"AutomixSDKPluginMetadataModel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","role":"symbol","title":"AutomixSDKWaveformModel","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"title":"AutomixSDKMixtapeTrack","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"title":"AutomixSDKMixtapeTrackImage","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKList":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKList"}],"abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdklist","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","role":"symbol","title":"AutomixSDKList"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic","kind":"symbol","title":"PacemakerRadio","role":"collection","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKArtistModel":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"url":"\/documentation\/pacemakerradio\/automixsdkartistmodel","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","role":"symbol","title":"AutomixSDKArtistModel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","role":"symbol","title":"AutomixSDKMixtapeCounters"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKMixtape models a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtape","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","role":"symbol","title":"AutomixSDKMixtape"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","role":"symbol","title":"AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","role":"symbol","title":"AutomixSDKPlaylistOperation"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeLite":{"abstract":[{"text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapelite","title":"AutomixSDKMixtapeLite"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKGenericList":{"url":"\/documentation\/pacemakerradio\/automixsdkgenericlist","abstract":[{"text":"AutomixSDKGenericList models a list of things","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKGenericList","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKGenericList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","kind":"symbol","title":"AutomixSDKGenericList"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKUser":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKUser"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKUser"}],"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkuser","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","role":"symbol","title":"AutomixSDKUser"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Data models","generated":true,"anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title"},{"value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"value":"AutomixSDKPluginMetadataModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle"},{"value":"AutomixSDKWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle"},{"value":"AutomixSDKMixtapeTrackImage","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title","op":"replace"},{"value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/title","value":"AutomixSDKList","op":"replace"},{"value":[{"text":"AutomixSDKList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/navigatorTitle","value":[{"text":"AutomixSDKList","kind":"identifier"}]},{"value":"AutomixSDKArtistModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/navigatorTitle","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},{"value":"AutomixSDKMixtapeCounters","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title","op":"replace","value":"AutomixSDKMixtape"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments","op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}]},{"op":"replace","value":"AutomixSDKStatus","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle"},{"value":"AutomixSDKPlaylistOperation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title"},{"op":"replace","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKMixtapeLite","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}]},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/title","op":"replace","value":"AutomixSDKUser"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/fragments","value":[{"text":"AutomixSDKUser","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKUser"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}