{"metadata":{"externalID":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate(im)trackDownloadProgressChangedWithTrackId:progress:","modules":[{"name":"AutomixIQ"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadProgressChanged"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","title":"trackDownloadProgressChanged(trackId:progress:)","navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/automixiq\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","interfaceLanguage":"swift"},"abstract":[{"text":"Called by AutomixIQ when a track download progress has changed.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"text":"The id of the track that AutomixIQ is streaming.","type":"text"}],"type":"paragraph"}]},{"name":"progress","content":[{"inlineContent":[{"type":"text","text":"The track download progress, between 0 (none) and 1 (complete)."}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate/trackDownloadProgressChanged(trackId:progress:)":{"navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate\/trackDownloadProgressChanged(trackId:progress:)","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"title":"trackDownloadProgressChanged(trackId:progress:)","url":"\/documentation\/automixiq\/tunedmusiccachedelegate\/trackdownloadprogresschanged(trackid:progress:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","type":"topic","kind":"symbol","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"type":"topic","url":"\/documentation\/automixiq\/tunedmusiccachedelegate","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"role":"symbol","title":"TunedMusicCacheDelegate","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"trackDownloadProgressChangedWithTrackId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"text":" ","kind":"text"},{"text":"progress:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"text":"progress","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","op":"replace","value":"trackDownloadProgressChangedWithTrackId:progress:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"op":"replace"}]}]}