{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"modules":[{"name":"PacemakerRadio"}],"title":"AutomixSDKPlaybackEventType.trackPlaySkipped","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlaySkipped","symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlaySkipped","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayskipped"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayskipped"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlaySkipped"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped"},"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlaySkipped":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayskipped","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlaySkipped","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType.trackPlaySkipped"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","title":"AutomixSDKPlaybackEventType","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}]},{"value":"AutomixSDKPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}