{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/prepareRefocusUI(withWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:)"},"metadata":{"title":"prepareRefocusUI(withWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:)","symbolKind":"method","role":"symbol","externalID":"c:objc(cs)AutomixSDKObjC(im)prepareRefocusUIWithWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:","roleHeading":"Instance Method","modules":[{"name":"PacemakerRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prepareRefocusUI","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"uiDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","kind":"typeIdentifier","text":"RadioUIDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"socialBackendDelegate"},{"text":": (any ","kind":"text"},{"text":"SocialBackendDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"tunedStoreId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareRefocusUI"},{"text":"(","kind":"text"},{"text":"withWidth","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"width","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"uiDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"RadioUIDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"kind":"text","text":")?, "},{"text":"socialBackendDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SocialBackendDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tunedStoreId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"configURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepareRefocusUI"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"text":" ","kind":"text"},{"text":"width","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"uiDelegate"},{"text":": (any ","kind":"text"},{"text":"RadioUIDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":")?, ","kind":"text"},{"text":"socialBackendDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"SocialBackendDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedStoreId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC"]]},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkobjc\/preparerefocusui(withwidth:height:uidelegate:socialbackenddelegate:countrycode:tunedstoreid:configurl:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"role":"collection","type":"topic","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC","url":"\/documentation\/pacemakerradio\/automixsdkobjc","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"title":"AutomixSDKObjC","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKObjC","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"title":"RadioUIDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/prepareRefocusUI(withWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:)":{"title":"prepareRefocusUI(withWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/preparerefocusui(withwidth:height:uidelegate:socialbackenddelegate:countrycode:tunedstoreid:configurl:completion:)","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepareRefocusUI","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withWidth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":", "},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"uiDelegate"},{"kind":"text","text":": (any "},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"socialBackendDelegate"},{"text":": (any ","kind":"text"},{"text":"SocialBackendDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"tunedStoreId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"configURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/prepareRefocusUI(withWidth:height:uiDelegate:socialBackendDelegate:countryCode:tunedStoreId:configURL:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"RadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace"}]}]}