{"seeAlsoSections":[{"title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC"],"generated":true,"anchor":"AutomixIQ"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixiq-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixiq-article"]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Article","title":"AutomixIQ","role":"article","modules":[{"name":"PacemakerRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"kind":"article","sections":[],"abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Essentials","text":"Essentials","type":"heading"},{"inlineContent":[{"type":"text","text":"PacemakerRadio works on top of AutomixIQ and exposes the functionality of AutomixIQ. Please note that manipulating playback or queue with AutomixIQ when a user is creating or consuming a radio show may impact the radio show itself and is therefore discouraged."}],"type":"paragraph"},{"inlineContent":[{"text":"The documentation for AutomixIQ can be found here: ","type":"text"},{"type":"reference","identifier":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"type":"topic","abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdk","kind":"symbol","title":"AutomixSDK","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc","kind":"symbol","title":"AutomixSDKObjC","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKObjC","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKObjC"}],"type":"topic","abstract":[],"role":"symbol"},"https://tunedglobal.github.io/automix-ios/0.7.0/documentation/automixiq":{"identifier":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq","url":"https:\/\/tunedglobal.github.io\/automix-ios\/0.7.0\/documentation\/automixiq","title":"AutomixIQ","type":"link","titleInlineContent":[{"text":"AutomixIQ","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","type":"topic","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"],"anchor":"AutomixIQ","title":"AutomixIQ","generated":true}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDK"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}