{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"content":[{"anchor":"Essentials","type":"heading","level":2,"text":"Essentials"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you want to fetch a list of currently available live shows as paged request, you use "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/getLiveShows(limit:start:completion:)","isActive":true},{"text":" as shown below:","type":"text"}]},{"code":["public class MyApplication {","    \/\/ ...","    func getShows() -> Void {","        let limit: Int = 10             \/\/ Get a total of 10 shows","        let start: Int = 0              \/\/ Get the first shows","        RadioSDK.instance.getLiveShows(limit: limit, start: start) { error, liveMixtapes in","            \/\/ Present the shows on your UI","            let myLiveShows = myLiveShows","            myLiveShows.add(liveShows)","            if(liveShows.size < limit) {","                \/\/ There are more shows available!","                getNextLiveShowsPage()","            }","        }","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"metadata":{"role":"article","title":"Getting available broadcasts","roleHeading":"Article","modules":[{"name":"PacemakerRadio"}]},"kind":"article","abstract":[{"type":"text","text":"How to learn which broadcasts are currently live."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Getting-available-broadcasts-article","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/getting-available-broadcasts-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/getting-available-broadcasts-article"]}],"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","type":"topic","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/getLiveShows(limit:start:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/getLiveShows(limit:start:completion:)","url":"\/documentation\/pacemakerradio\/radiosdk\/getliveshows(limit:start:completion:)","abstract":[{"text":"Queries the live shows, paged.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"getLiveShowsWithLimit:start:completion:","kind":"identifier"}],"title":"getLiveShows(limit:start:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLiveShows"},{"text":"(","kind":"text"},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"liveMixtapes"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKList","text":"AutomixSDKList","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"getLiveShowsWithLimit:start:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1getLiveShows(limit:start:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1getLiveShows(limit:start:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLiveShowsWithLimit:start:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}