{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/muted","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableMuted","title":"AutomixSDKStatusVariable.muted","navigatorTitle":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muted","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/muted"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/muted"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"muted","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","title":"AutomixSDKStatusVariable","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","abstract":[{"type":"text","text":"AutomixIQ status variable type"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/muted":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/muted","title":"AutomixSDKStatusVariable.muted","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"muted","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/muted","type":"topic","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","url":"\/documentation\/automixiq","title":"AutomixIQ","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatusVariableMuted"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"AutomixSDKStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1muted\/title","op":"replace","value":"AutomixSDKStatusVariableMuted"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1muted\/fragments","value":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}]}]}]}