{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/normalisedVolume"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Represents the Automix SDK volume from 1 to 0. Note the device’s iOS Volume acts as a master over this one: if iOS’volume is 0, no sound will be put out regardless of this value.","type":"text"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatus\/normalisedvolume"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatus\/normalisedvolume"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)normalisedVolume","title":"normalisedVolume","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normalisedVolume"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"normalisedVolume","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"AutomixIQ"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","url":"\/documentation\/automixiq\/automixsdkstatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"title":"AutomixSDKStatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/normalisedVolume":{"type":"topic","url":"\/documentation\/automixiq\/automixsdkstatus\/normalisedvolume","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"normalisedVolume","kind":"identifier"}],"title":"normalisedVolume","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/normalisedVolume","abstract":[{"type":"text","text":"Represents the Automix SDK volume from 1 to 0. Note the device’s iOS Volume acts as a master over this one: if iOS’volume is 0, no sound will be put out regardless of this value."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"normalisedVolume","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"normalisedVolume","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"op":"replace","value":"normalisedVolume","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1normalisedVolume\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1normalisedVolume\/fragments","value":[{"kind":"identifier","text":"normalisedVolume"}],"op":"replace"}]}]}