{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanOnOff","title":"AutomixSDKStatusVariable.canOnOff","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanOnOff"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"AutomixIQ"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canOnOff","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canonoff"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canonoff"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"abstract":[{"text":"AutomixSDK play event type","type":"text"}],"title":"AutomixSDKStatusVariable","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canOnOff":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canOnOff","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canonoff","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canOnOff"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanOnOff","kind":"identifier"}],"type":"topic","title":"AutomixSDKStatusVariable.canOnOff"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"AutomixSDKStatusVariableCanOnOff","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableCanOnOff","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKStatusVariableCanOnOff","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canOnOff\/title","value":"AutomixSDKStatusVariableCanOnOff"},{"value":[{"text":"AutomixSDKStatusVariableCanOnOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canOnOff\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}