{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playingtrackcurrenttime"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus"]]},"sections":[],"metadata":{"title":"playingTrackCurrentTime","role":"symbol","symbolKind":"property","modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus(py)playingTrackCurrentTime","roleHeading":"Instance Property","navigatorTitle":[{"text":"playingTrackCurrentTime","kind":"identifier"}]},"abstract":[{"text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playingTrackCurrentTime"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","type":"topic","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus/playingTrackCurrentTime":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackCurrentTime"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"text":"Represents the current playback time of the playing track. If seeking, it reports seek landing time until jump is complete. This should be use on the UI.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playingTrackCurrentTime","navigatorTitle":[{"kind":"identifier","text":"playingTrackCurrentTime"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkstatus\/playingtrackcurrenttime","title":"playingTrackCurrentTime"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","kind":"symbol","title":"AutomixSDKStatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatus"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"playingTrackCurrentTime","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"playingTrackCurrentTime","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playingTrackCurrentTime\/title","value":"playingTrackCurrentTime","op":"replace"},{"value":[{"kind":"identifier","text":"playingTrackCurrentTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playingTrackCurrentTime\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","op":"replace"}]}]}