{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage"]}],"abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/init(from:)"]},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageHeight","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageWidth","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/url"],"anchor":"Instance-Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"PacemakerRadio"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"roleHeading":"Class","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrackImage","title":"AutomixSDKMixtapeTrackImage"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/Se","doc:\/\/org.cocoapods.PacemakerRadio\/SE","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"title":"Data models","generated":true,"anchor":"Data-models"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Data-models-article":{"title":"Data models","role":"article","kind":"article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","type":"topic","abstract":[{"text":"How data is passed to and from PacemakerRadio","type":"text"}],"url":"\/documentation\/pacemakerradio\/data-models-article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPluginMetadataModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"title":"AutomixSDKPluginMetadataModel","url":"\/documentation\/pacemakerradio\/automixsdkpluginmetadatamodel","navigatorTitle":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","type":"topic","kind":"symbol","abstract":[{"text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"text":" ","type":"text"},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"url":"\/documentation\/pacemakerradio\/automixsdkstatus","title":"AutomixSDKStatus","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","abstract":[{"text":"AutomixSDKStatus models the State of the AutomixSDK during playback.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage/imageWidth":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWidth"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage\/imagewidth","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageWidth","type":"topic","abstract":[{"type":"text","text":"The width of the image"}],"kind":"symbol","title":"imageWidth"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"title":"TunedAuthenticationResponse","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"type":"topic","url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/Se":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"title":"AutomixSDKMixtapeCounters","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage/url":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"url","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/url","type":"topic","abstract":[{"type":"text","text":"The url for the image"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage\/url","role":"symbol","navigatorTitle":[{"text":"url","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeLite":{"title":"AutomixSDKMixtapeLite","role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","type":"topic","abstract":[{"text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapelite"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKList":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","url":"\/documentation\/pacemakerradio\/automixsdklist","abstract":[],"title":"AutomixSDKList","type":"topic","navigatorTitle":[{"text":"AutomixSDKList","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformBlob":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"title":"AutomixSDKWaveformBlob","url":"\/documentation\/pacemakerradio\/automixsdkwaveformblob","navigatorTitle":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","type":"topic","kind":"symbol","abstract":[{"text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track","type":"text"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"title":"AutomixSDKTrackModel","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage/init(from:)":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init(from:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/init(from:)","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"title":"AutomixSDKMixtapeTrackImage","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","navigatorTitle":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","type":"topic","kind":"symbol","abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/SE":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"title":"AutomixSDKWaveformModel","role":"symbol","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","type":"topic","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKArtistModel":{"title":"AutomixSDKArtistModel","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"url":"\/documentation\/pacemakerradio\/automixsdkartistmodel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKArtistModel"}],"navigatorTitle":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"title":"AutomixSDKMixtapeTrack","abstract":[{"text":"AutomixSDKMixtapeTrack models a track in a mixtape","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKGenericList":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkgenericlist","abstract":[{"type":"text","text":"AutomixSDKGenericList models a list of things"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKGenericList"}],"navigatorTitle":[{"text":"AutomixSDKGenericList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","title":"AutomixSDKGenericList"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage/imageHeight":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageHeight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","title":"imageHeight","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageHeight","navigatorTitle":[{"text":"imageHeight","kind":"identifier"}],"abstract":[{"text":"The height of the image","type":"text"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage\/imageheight","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtape","title":"AutomixSDKMixtape","kind":"symbol","abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage\/init","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/init","type":"topic","abstract":[],"kind":"symbol","title":"init"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKUser":{"abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"title":"AutomixSDKUser","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKUser"}],"url":"\/documentation\/pacemakerradio\/automixsdkuser","navigatorTitle":[{"text":"AutomixSDKUser","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"title":"AutomixSDKPlaylistOperation","role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","type":"topic","abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKMixtapeTrackImage"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageHeight","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/imageWidth","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/url"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Data-models","title":"Data models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"AutomixSDKPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle","value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKStatus","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"value":"imageWidth","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1imageWidth\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1imageWidth\/fragments","value":[{"text":"imageWidth","kind":"identifier"}]},{"value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title","op":"replace"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},{"value":"url","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1url\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1url\/fragments","value":[{"text":"url","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/title","op":"replace","value":"AutomixSDKMixtapeLite"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/fragments"},{"value":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/title","value":"AutomixSDKList","op":"replace"},{"value":[{"text":"AutomixSDKList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/navigatorTitle","value":[{"text":"AutomixSDKList","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixSDKWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/title"},{"value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle"},{"op":"replace","value":"AutomixSDKMixtapeTrackImage","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title"},{"value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]},{"value":"AutomixSDKArtistModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle"},{"value":"imageHeight","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1imageHeight\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage~1imageHeight\/fragments","value":[{"text":"imageHeight","kind":"identifier"}]},{"value":"AutomixSDKMixtape","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/title","value":"AutomixSDKUser","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKUser"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKUser"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle"}]}]}