{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdk\/seekto(seconds:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/seekto(seconds:completion:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"kind":"symbol","abstract":[{"text":"Jumps playback on the current track to the desired timestamp as soon as possible.","type":"text"},{"type":"text","text":" "},{"text":"This will mix the track with itself so the seek is beatmatched and as unnoticeable as possible, which means the landing position will be close but not exactly the fed timestamp.","type":"text"}],"seeAlsoSections":[{"title":"Playback Control","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"]}],"metadata":{"title":"seekTo(seconds:completion:)","role":"symbol","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)seekToSeconds:completion:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"seekTo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"seconds"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"seekToSeconds:completion:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/pause(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pauseWithCompletion:"}],"title":"pause(completion:)","url":"\/documentation\/automixiq\/automixsdk\/pause(completion:)","abstract":[{"type":"text","text":"Pauses playback if playing."},{"type":"text","text":" "},{"type":"text","text":"If already paused it does nothing."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/next(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"next","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"nextWithCompletion:"}],"title":"next(completion:)","url":"\/documentation\/automixiq\/automixsdk\/next(completion:)","abstract":[{"type":"text","text":"Makes playback go to the beginning of the next track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/previous(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previous","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"previousWithCompletion:"}],"title":"previous(completion:)","url":"\/documentation\/automixiq\/automixsdk\/previous(completion:)","abstract":[{"type":"text","text":"Makes playback go to the beginning of the previous track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixPlaySpeed(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAutomixPlaySpeed"},{"text":"(Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}],"title":"setAutomixPlaySpeed(_:completion:)","url":"\/documentation\/automixiq\/automixsdk\/setautomixplayspeed(_:completion:)","abstract":[{"type":"text","text":"Sets the AutomixIQ SDK play speed to a given value between 0.5 and 2. 0.5 is playback at half speed, 2 is playback at double speed"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/removeTrack(at:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTrack"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"removeTrackAt:completion:"}],"title":"removeTrack(at:completion:)","url":"\/documentation\/automixiq\/automixsdk\/removetrack(at:completion:)","abstract":[{"type":"text","text":"Removes a track from the playlist in the AutomixIQ SDK at a given index."},{"type":"text","text":" "},{"type":"text","text":"If the index is out of bounds it does nothing."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loopPlayingTrack(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loopPlayingTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"title":"loopPlayingTrack(completion:)","url":"\/documentation\/automixiq\/automixsdk\/loopplayingtrack(completion:)","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK loop the currently playing track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/moveTrack(at:toIndex:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"toIndex"},{"kind":"text","text":": "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"title":"moveTrack(at:toIndex:completion:)","url":"\/documentation\/automixiq\/automixsdk\/movetrack(at:toindex:completion:)","abstract":[{"type":"text","text":"Moves the track from one index to a different index"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleReplay(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","type":"topic","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toggleReplay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"toggleReplayWithCompletion:"}],"title":"toggleReplay(completion:)","url":"\/documentation\/automixiq\/automixsdk\/togglereplay(completion:)","abstract":[{"type":"text","text":"If on, after a playlist is done it restarts. Otherwise, it pauses."},{"type":"text","text":" "},{"type":"text","text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/play(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"playWithCompletion:"}],"title":"play(completion:)","url":"\/documentation\/automixiq\/automixsdk\/play(completion:)","abstract":[{"type":"text","text":"Starts playback if paused."},{"type":"text","text":" "},{"type":"text","text":"If already playing it does nothing."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/skipToTrackAtIndex(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToTrackAtIndex"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}],"title":"skipToTrackAtIndex(_:completion:)","url":"\/documentation\/automixiq\/automixsdk\/skiptotrackatindex(_:completion:)","abstract":[{"type":"text","text":"Jumps playback to the beginning of the track at the desired index as soon as possible."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/reorderTracks(newOrder:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderTracks"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"newOrder"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}],"title":"reorderTracks(newOrder:completion:)","url":"\/documentation\/automixiq\/automixsdk\/reordertracks(neworder:completion:)","abstract":[{"type":"text","text":"Sets a new order to the playlist while continuing to play the current track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/back(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"backWithCompletion:"}],"title":"back(completion:)","url":"\/documentation\/automixiq\/automixsdk\/back(completion:)","abstract":[{"type":"text","text":"Makes playback go to the beginning of the current track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixVolumeNormalised(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAutomixVolumeNormalised","kind":"identifier"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}],"title":"setAutomixVolumeNormalised(_:completion:)","url":"\/documentation\/automixiq\/automixsdk\/setautomixvolumenormalised(_:completion:)","abstract":[{"type":"text","text":"Sets the AutomixIQ SDK volume to a given value between 0 and 1. If muted, calling this will cause the AutomixIQ SDK to unmute."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleMute(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","type":"topic","kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toggleMute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"toggleMuteWithCompletion:"}],"title":"toggleMute(completion:)","url":"\/documentation\/automixiq\/automixsdk\/togglemute(completion:)","abstract":[{"type":"text","text":"Toggles the AutomixIQ SDK mute"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/seekTo(seconds:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seekTo","kind":"identifier"},{"kind":"text","text":"("},{"text":"seconds","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"seekToSeconds:completion:"}],"title":"seekTo(seconds:completion:)","url":"\/documentation\/automixiq\/automixsdk\/seekto(seconds:completion:)","abstract":[{"type":"text","text":"Jumps playback on the current track to the desired timestamp as soon as possible."},{"type":"text","text":" "},{"type":"text","text":"This will mix the track with itself so the seek is beatmatched and as unnoticeable as possible, which means the landing position will be close but not exactly the fed timestamp."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setMute(on:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMute"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"setMuteOn:completion:"}],"title":"setMute(on:completion:)","url":"\/documentation\/automixiq\/automixsdk\/setmute(on:completion:)","abstract":[{"type":"text","text":"Sets the AutomixIQ SDK mute"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/playTrackUntilEndThenPause(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playTrackUntilEndThenPause"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playTrackUntilEndThenPauseWithCompletion:"}],"title":"playTrackUntilEndThenPause(completion:)","url":"\/documentation\/automixiq\/automixsdk\/playtrackuntilendthenpause(completion:)","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK play a given track until the end and then pause. If you run this on the last track it will fail."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","text":"AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"seconds","kind":"externalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}],"title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/automixiq\/automixsdk\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","abstract":[{"type":"text","text":"Loads a new playlist into Automix SDK."},{"type":"text","text":" "},{"type":"text","text":"If the playlist is empty this opperation will fail and Automix SDK will be turned off"},{"type":"text","text":" "},{"type":"text","text":"This will stop playback of the playlist currently playing and start the new one."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"title":"AutomixSDK","url":"\/documentation\/automixiq\/automixsdk","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTracks(identifiers:metadata:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTracks"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"text":"index","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"addTracksWithIdentifiers:metadata:index:completion:","kind":"identifier"}],"title":"addTracks(identifiers:metadata:index:completion:)","url":"\/documentation\/automixiq\/automixsdk\/addtracks(identifiers:metadata:index:completion:)","abstract":[{"type":"text","text":"Adds additional tracks to a playlist in the AutomixIQ SDK at a given index."},{"type":"text","text":" "},{"type":"text","text":"If the index is out of bounds it does nothing."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTrack(identifier:metadata:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","text":"AutomixSDKTrackModel"},{"text":"?, ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}],"title":"addTrack(identifier:metadata:index:completion:)","url":"\/documentation\/automixiq\/automixsdk\/addtrack(identifier:metadata:index:completion:)","abstract":[{"type":"text","text":"Adds a single track to a playlist in the AutomixIQ SDK at a given index."},{"type":"text","text":" "},{"type":"text","text":"If the index is out of bounds it does nothing."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/stopLoopingPlayingTrack(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopLoopingPlayingTrack"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"stopLoopingPlayingTrackWithCompletion:","kind":"identifier"}],"title":"stopLoopingPlayingTrack(completion:)","url":"\/documentation\/automixiq\/automixsdk\/stoploopingplayingtrack(completion:)","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK stop looping the currently playing track"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setReplay(on:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setReplay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setReplayOn:completion:"}],"title":"setReplay(on:completion:)","url":"\/documentation\/automixiq\/automixsdk\/setreplay(on:completion:)","abstract":[{"type":"text","text":"If on, after a playlist is done it restarts. Otherwise, it pauses."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"seekToSeconds:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"seekToSeconds:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"],"generated":true,"title":"Playback Control"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"seekToSeconds:"},{"kind":"text","text":"("},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"seconds"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"pauseWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pauseWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/title","value":"nextWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/title","value":"previousWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"previousWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/title","op":"replace","value":"setAutomixPlaySpeed:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAutomixPlaySpeed:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/title","value":"removeTrackAt:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTrackAt:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/title","value":"loopPlayingTrackWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loopPlayingTrackWithCompletion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/title","value":"moveTrackAt:toIndex:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/title","value":"toggleReplayWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toggleReplayWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/title","value":"playWithCompletion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"playWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/fragments"},{"op":"replace","value":"skipToTrackAtIndex:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"skipToTrackAtIndex:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/fragments"},{"value":"reorderTracksWithNewOrder:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/title","value":"backWithCompletion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"backWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/title","value":"setAutomixVolumeNormalised:completion:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAutomixVolumeNormalised:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/fragments"},{"op":"replace","value":"toggleMuteWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleMuteWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/fragments"},{"value":"seekToSeconds:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"seekToSeconds:completion:"}]},{"value":"setMuteOn:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMuteOn:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/title","value":"playTrackUntilEndThenPauseWithCompletion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playTrackUntilEndThenPauseWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/fragments"},{"value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:","kind":"identifier"}]},{"value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","op":"replace"},{"value":"addTracksWithIdentifiers:metadata:index:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTracksWithIdentifiers:metadata:index:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/title","op":"replace","value":"addTrackWithIdentifier:metadata:index:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/title","value":"stopLoopingPlayingTrackWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}]},{"value":"setReplayOn:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setReplayOn:completion:"}]}]}]}