{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","required":true,"role":"symbol","title":"statusChanged(variables:status:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"variables","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"statusChangedWithVariables:status:"}],"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate(im)statusChangedWithVariables:status:"},"abstract":[{"type":"text","text":"Called when the status of the AutomixIQ SDK changes"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusChanged"},{"kind":"text","text":"("},{"text":"variables","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"variables","content":[{"type":"paragraph","inlineContent":[{"text":"a list of strings with the name of each variable that changed since last time this method was called, or since the AutomixIQ SDK initialisation.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the current status of the AutomixIQ SDK"}]}],"name":"status"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)"},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixsdkstatus","title":"AutomixSDKStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate/statusChanged(variables:status:)":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"title":"statusChanged(variables:status:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variables","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"text":"AutomixSDKStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)","kind":"symbol","abstract":[{"text":"Called when the status of the AutomixIQ SDK changes","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","kind":"symbol","title":"AutomixIQ","type":"topic","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented by a class tasked with observing the status of the AutomixIQ SDK to reflect it on a UI.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","kind":"symbol","type":"topic","role":"symbol","title":"AutomixSDKStatusObserverDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"statusChangedWithVariables:status:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"statusChangedWithVariables:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"variables"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status:"},{"text":"(","kind":"text"},{"text":"AutomixSDKStatus","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","value":"AutomixSDKStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/title","value":"statusChangedWithVariables:status:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate"},{"value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"}]}]}