{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelTrace","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkloglevel\/logleveltrace"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkloglevel\/logleveltrace"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel\/logLevelTrace"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel"]]},"kind":"symbol","metadata":{"roleHeading":"Case","title":"AutomixSDKLogLevel.logLevelTrace","role":"symbol","modules":[{"name":"PacemakerRadio"}],"symbolKind":"case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelTrace","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevelTrace","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKLogLevel/logLevelTrace":{"title":"AutomixSDKLogLevel.logLevelTrace","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel\/logLevelTrace","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkloglevel\/logleveltrace","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"logLevelTrace","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKLogLevel":{"url":"\/documentation\/pacemakerradio\/automixsdkloglevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel","role":"symbol","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"title":"AutomixSDKLogLevel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKLogLevelLogLevelTrace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"AutomixSDKLogLevelLogLevelTrace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel~1logLevelTrace\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel~1logLevelTrace\/fragments","op":"replace"},{"value":"AutomixSDKLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/fragments","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}