{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel\/logLevelFatal"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkloglevel\/loglevelfatal"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkloglevel\/loglevelfatal"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"PacemakerRadio"}],"roleHeading":"Case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelFatal","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelFatal"}],"title":"AutomixSDKLogLevel.logLevelFatal","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelFatal","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKLogLevel":{"url":"\/documentation\/pacemakerradio\/automixsdkloglevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel","role":"symbol","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"title":"AutomixSDKLogLevel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKLogLevel/logLevelFatal":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel\/logLevelFatal","url":"\/documentation\/pacemakerradio\/automixsdkloglevel\/loglevelfatal","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelFatal"}],"title":"AutomixSDKLogLevel.logLevelFatal","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"AutomixSDKLogLevelLogLevelFatal","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKLogLevelLogLevelFatal","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AutomixSDKLogLevelLogLevelFatal","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/fragments","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel~1logLevelFatal\/title","value":"AutomixSDKLogLevelLogLevelFatal"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel~1logLevelFatal\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}],"op":"replace"}]}]}