{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixTempoNormalised(_:completion:)"},"abstract":[{"type":"text","text":"Sets the AutomixIQ SDK tempo to a given value between 0 and 1. 0 is -15% and 1 is +15%."}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"],"title":"Playback Control","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setAutomixTempoNormalised","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"tempoNormalised","kind":"internalParam"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The tempo value to set","type":"text"}],"type":"paragraph"}],"name":"tempoNormalised"},{"content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}],"name":"completion"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/setautomixtemponormalised(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/setautomixtemponormalised(_:completion:)"]}],"metadata":{"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)setAutomixTempoNormalised:completion:","title":"setAutomixTempoNormalised(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAutomixTempoNormalised","kind":"identifier"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setAutomixTempoNormalised:completion:"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/previous(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","type":"topic","title":"previous(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previous"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/previous(completion:)","abstract":[{"text":"Makes playback go to the beginning of the previous track","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"previousWithCompletion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixVolumeNormalised(_:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAutomixVolumeNormalised","kind":"identifier"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAutomixVolumeNormalised:completion:"}],"title":"setAutomixVolumeNormalised(_:completion:)","url":"\/documentation\/automixiq\/automixsdk\/setautomixvolumenormalised(_:completion:)","type":"topic","abstract":[{"text":"Sets the AutomixIQ SDK volume to a given value between 0 and 1. If muted, calling this will cause the AutomixIQ SDK to unmute.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setReplay(on:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","type":"topic","title":"setReplay(on:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setReplay"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/setreplay(on:completion:)","abstract":[{"type":"text","text":"If on, after a playlist is done it restarts. Otherwise, it pauses."}],"role":"symbol","navigatorTitle":[{"text":"setReplayOn:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTrack(identifier:metadata:index:completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/addtrack(identifier:metadata:index:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"?, "},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"abstract":[{"type":"text","text":"Adds a single track to a playlist in the AutomixIQ SDK at a given index."},{"text":" ","type":"text"},{"text":"If the index is out of bounds it does nothing.","type":"text"}],"title":"addTrack(identifier:metadata:index:completion:)","navigatorTitle":[{"kind":"identifier","text":"addTrackWithIdentifier:metadata:index:completion:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/back(completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","kind":"symbol","navigatorTitle":[{"text":"backWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk\/back(completion:)","title":"back(completion:)","type":"topic","abstract":[{"type":"text","text":"Makes playback go to the beginning of the current track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"AutomixSDK","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","kind":"symbol","url":"\/documentation\/automixiq\/automixsdk","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleReplay(completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toggleReplay"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","kind":"symbol","navigatorTitle":[{"text":"toggleReplayWithCompletion:","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/automixiq\/automixsdk\/togglereplay(completion:)","title":"toggleReplay(completion:)","type":"topic","abstract":[{"text":"If on, after a playlist is done it restarts. Otherwise, it pauses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This defaults to false on initialisation and should be set to match the state of the consumer’s UI"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loopPlayingTrack(completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopPlayingTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","kind":"symbol","navigatorTitle":[{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"title":"loopPlayingTrack(completion:)","url":"\/documentation\/automixiq\/automixsdk\/loopplayingtrack(completion:)","type":"topic","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK loop the currently playing track"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/pause(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","type":"topic","title":"pause(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pause","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/pause(completion:)","abstract":[{"type":"text","text":"Pauses playback if playing."},{"type":"text","text":" "},{"type":"text","text":"If already paused it does nothing."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pauseWithCompletion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setMute(on:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","type":"topic","title":"setMute(on:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/setmute(on:completion:)","abstract":[{"type":"text","text":"Sets the AutomixIQ SDK mute"}],"role":"symbol","navigatorTitle":[{"text":"setMuteOn:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/reorderTracks(newOrder:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)","type":"topic","title":"reorderTracks(newOrder:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reorderTracks"},{"kind":"text","text":"("},{"text":"newOrder","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/reordertracks(neworder:completion:)","abstract":[{"text":"Sets a new order to the playlist while continuing to play the current track","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"reorderTracksWithNewOrder:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"url":"\/documentation\/automixiq\/automixsdk\/loadtracks(identifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","abstract":[{"text":"Loads a new playlist into Automix SDK.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the playlist is empty this opperation will fail and Automix SDK will be turned off"},{"text":" ","type":"text"},{"text":"This will stop playback of the playlist currently playing and start the new one.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","title":"loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","navigatorTitle":[{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTracks"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"contextType"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/seekTo(seconds:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"seekTo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"seconds"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"seekToSeconds:completion:"}],"title":"seekTo(seconds:completion:)","url":"\/documentation\/automixiq\/automixsdk\/seekto(seconds:completion:)","type":"topic","abstract":[{"text":"Jumps playback on the current track to the desired timestamp as soon as possible.","type":"text"},{"type":"text","text":" "},{"text":"This will mix the track with itself so the seek is beatmatched and as unnoticeable as possible, which means the landing position will be close but not exactly the fed timestamp.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/next(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"next","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/next(completion:)","title":"next(completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","navigatorTitle":[{"kind":"identifier","text":"nextWithCompletion:"}],"abstract":[{"text":"Makes playback go to the beginning of the next track","type":"text"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/play(completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"play","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","kind":"symbol","navigatorTitle":[{"text":"playWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk\/play(completion:)","title":"play(completion:)","type":"topic","abstract":[{"text":"Starts playback if paused.","type":"text"},{"type":"text","text":" "},{"text":"If already playing it does nothing.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/skipToTrackAtIndex(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","type":"topic","title":"skipToTrackAtIndex(_:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipToTrackAtIndex"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/skiptotrackatindex(_:completion:)","abstract":[{"type":"text","text":"Jumps playback to the beginning of the track at the desired index as soon as possible."}],"role":"symbol","navigatorTitle":[{"text":"skipToTrackAtIndex:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/removeTrack(at:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","type":"topic","title":"removeTrack(at:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/removetrack(at:completion:)","abstract":[{"text":"Removes a track from the playlist in the AutomixIQ SDK at a given index.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the index is out of bounds it does nothing."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"removeTrackAt:completion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/moveTrack(at:toIndex:completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"toIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","kind":"symbol","navigatorTitle":[{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}],"title":"moveTrack(at:toIndex:completion:)","url":"\/documentation\/automixiq\/automixsdk\/movetrack(at:toindex:completion:)","type":"topic","abstract":[{"text":"Moves the track from one index to a different index","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/stopLoopingPlayingTrack(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","type":"topic","title":"stopLoopingPlayingTrack(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLoopingPlayingTrack"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/stoploopingplayingtrack(completion:)","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK stop looping the currently playing track"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopLoopingPlayingTrackWithCompletion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/toggleMute(completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","deprecated":true,"type":"topic","title":"toggleMute(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleMute","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/togglemute(completion:)","abstract":[{"type":"text","text":"Toggles the AutomixIQ SDK mute"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"toggleMuteWithCompletion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/playTrackUntilEndThenPause(completion:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playTrackUntilEndThenPause"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","kind":"symbol","navigatorTitle":[{"text":"playTrackUntilEndThenPauseWithCompletion:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk\/playtrackuntilendthenpause(completion:)","title":"playTrackUntilEndThenPause(completion:)","type":"topic","abstract":[{"type":"text","text":"Makes the AutomixIQ SDK play a given track until the end and then pause. If you run this on the last track it will fail."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixTempoNormalised(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixTempoNormalised(_:completion:)","type":"topic","title":"setAutomixTempoNormalised(_:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setAutomixTempoNormalised","kind":"identifier"},{"kind":"text","text":"(Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/setautomixtemponormalised(_:completion:)","abstract":[{"text":"Sets the AutomixIQ SDK tempo to a given value between 0 and 1. 0 is -15% and 1 is +15%.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setAutomixTempoNormalised:completion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setAutomixPlaySpeed(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","type":"topic","title":"setAutomixPlaySpeed(_:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAutomixPlaySpeed"},{"text":"(Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"url":"\/documentation\/automixiq\/automixsdk\/setautomixplayspeed(_:completion:)","abstract":[{"type":"text","text":"Sets the AutomixIQ SDK play speed to a given value between 0.5 and 2. 0.5 is playback at half speed, 2 is playback at double speed"}],"role":"symbol","navigatorTitle":[{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/addTracks(identifiers:metadata:index:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTracks"},{"text":"(","kind":"text"},{"text":"identifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"index"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","kind":"symbol","navigatorTitle":[{"text":"addTracksWithIdentifiers:metadata:index:completion:","kind":"identifier"}],"title":"addTracks(identifiers:metadata:index:completion:)","url":"\/documentation\/automixiq\/automixsdk\/addtracks(identifiers:metadata:index:completion:)","type":"topic","abstract":[{"type":"text","text":"Adds additional tracks to a playlist in the AutomixIQ SDK at a given index."},{"type":"text","text":" "},{"text":"If the index is out of bounds it does nothing.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"setAutomixTempoNormalised:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"setAutomixTempoNormalised:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTracks(identifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/addTrack(identifier:metadata:index:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/moveTrack(at:toIndex:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/play(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/pause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/next(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/previous(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/back(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleReplay(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setReplay(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/seekTo(seconds:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/skipToTrackAtIndex(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/playTrackUntilEndThenPause(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/toggleMute(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setMute(on:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/reorderTracks(newOrder:completion:)"],"title":"Playback Control","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setAutomixTempoNormalised:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"text":"tempoNormalised","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/title","value":"previousWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1previous(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"previousWithCompletion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/title","value":"setAutomixVolumeNormalised:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixVolumeNormalised(_:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setAutomixVolumeNormalised:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/title","value":"setReplayOn:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setReplayOn:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setReplay(on:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/title","value":"addTrackWithIdentifier:metadata:index:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addTrackWithIdentifier:metadata:index:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTrack(identifier:metadata:index:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/title","value":"backWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1back(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"backWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"},{"value":"toggleReplayWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleReplay(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toggleReplayWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/title","op":"replace","value":"loopPlayingTrackWithCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loopPlayingTrackWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loopPlayingTrack(completion:)\/fragments"},{"value":"pauseWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"pauseWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1pause(completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/title","op":"replace","value":"setMuteOn:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setMute(on:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setMuteOn:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/title","op":"replace","value":"reorderTracksWithNewOrder:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1reorderTracks(newOrder:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reorderTracksWithNewOrder:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/title","op":"replace","value":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1loadTracks(identifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadTracksWithIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/title","value":"seekToSeconds:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1seekTo(seconds:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"seekToSeconds:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/title","value":"nextWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1next(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nextWithCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/title","value":"playWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1play(completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playWithCompletion:"}]},{"op":"replace","value":"skipToTrackAtIndex:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1skipToTrackAtIndex(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"skipToTrackAtIndex:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/title","value":"removeTrackAt:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1removeTrack(at:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTrackAt:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/title","op":"replace","value":"moveTrackAt:toIndex:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1moveTrack(at:toIndex:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"moveTrackAt:toIndex:completion:","kind":"identifier"}]},{"value":"stopLoopingPlayingTrackWithCompletion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1stopLoopingPlayingTrack(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"stopLoopingPlayingTrackWithCompletion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/title","op":"replace","value":"toggleMuteWithCompletion:"},{"value":[{"kind":"text","text":"- "},{"text":"toggleMuteWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1toggleMute(completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/title","value":"playTrackUntilEndThenPauseWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1playTrackUntilEndThenPause(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"playTrackUntilEndThenPauseWithCompletion:","kind":"identifier"}],"op":"replace"},{"value":"setAutomixTempoNormalised:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixTempoNormalised(_:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixTempoNormalised(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setAutomixTempoNormalised:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/title","op":"replace","value":"setAutomixPlaySpeed:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setAutomixPlaySpeed(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setAutomixPlaySpeed:completion:","kind":"identifier"}],"op":"replace"},{"value":"addTracksWithIdentifiers:metadata:index:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1addTracks(identifiers:metadata:index:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTracksWithIdentifiers:metadata:index:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}