{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(cm)automixSDKErrorWithCode:","modules":[{"name":"AutomixIQ"}],"symbolKind":"method","title":"automixSDKError(code:)","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixSDKError"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/automixsdkerror(code:)"]},{"paths":["\/documentation\/automixiq\/automixsdk\/automixsdkerror(code:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"automixSDKError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKErrorCode","kind":"typeIdentifier","text":"AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"}]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/automixSDKError(code:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"title":"AutomixSDKErrorCode","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/automixSDKError(code:)":{"title":"automixSDKError(code:)","abstract":[],"url":"\/documentation\/automixiq\/automixsdk\/automixsdkerror(code:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"automixSDKErrorWithCode:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"automixSDKError","kind":"identifier"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKErrorCode"},{"kind":"text","text":") -> "},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/automixSDKError(code:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDK","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdk","role":"symbol","title":"AutomixSDK","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"automixSDKErrorWithCode:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"automixSDKErrorWithCode:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"automixSDKErrorWithCode:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKErrorCode","kind":"typeIdentifier","text":"AutomixSDKErrorCode"},{"kind":"text","text":") "},{"text":"code","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","op":"replace","value":"AutomixSDKErrorCode"},{"op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments"},{"op":"replace","value":"automixSDKErrorWithCode:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1automixSDKError(code:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1automixSDKError(code:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"automixSDKErrorWithCode:"}]},{"op":"replace","value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDK"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}