{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"role":"symbol","symbolKind":"enum","roleHeading":"Enumeration","title":"AutomixSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"},"abstract":[{"type":"text","text":"AutomixSDK error codes"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/unimplemented"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article"],"generated":true,"title":"Errors"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/noInternetAvailableTooLongOffline":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.noInternetAvailableTooLongOffline","url":"\/documentation\/automixiq\/automixsdkerrorcode\/nointernetavailabletoolongoffline","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","navigatorTitle":[{"text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/playToEndMixEnd":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playToEndMixEnd"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.playToEndMixEnd","url":"\/documentation\/automixiq\/automixsdkerrorcode\/playtoendmixend","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMixEnd","navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/automixiq\/automixsdkerrorcode\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://org.cocoapods.AutomixIQ/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/addTrackPlaylistDoesNotExist":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.addTrackPlaylistDoesNotExist","url":"\/documentation\/automixiq\/automixsdkerrorcode\/addtrackplaylistdoesnotexist","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/startLoopingNoLoopingTrack":{"role":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/startloopingnoloopingtrack","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack"}],"title":"AutomixSDKErrorCode.startLoopingNoLoopingTrack","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLoopingNoLoopingTrack"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"title":"AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkInitialisationUnauthorised":{"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkInitialisationUnauthorised"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdkinitialisationunauthorised","title":"AutomixSDKErrorCode.sdkInitialisationUnauthorised","type":"topic"},"doc://org.cocoapods.AutomixIQ/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkNotInitialised":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdknotinitialised","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotInitialised","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotInitialised","kind":"identifier"}],"title":"AutomixSDKErrorCode.sdkNotInitialised","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotCreateInputBuffer":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotCreateInputBuffer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"role":"symbol","title":"AutomixSDKErrorCode.cannotCreateInputBuffer","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateInputBuffer","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotcreateinputbuffer"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/addTrackNoMetadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackNoMetadata"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.addTrackNoMetadata","url":"\/documentation\/automixiq\/automixsdkerrorcode\/addtracknometadata","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackNoMetadata","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackNoMetadata","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/offlinenotuneduseridavailable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","navigatorTitle":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/seekNoTrackAvailable":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"seekNoTrackAvailable","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"title":"AutomixSDKErrorCode.seekNoTrackAvailable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoTrackAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/seeknotrackavailable","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/moveTrackOutOfBounds":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveTrackOutOfBounds"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.moveTrackOutOfBounds","url":"\/documentation\/automixiq\/automixsdkerrorcode\/movetrackoutofbounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/moveTrackOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeMoveTrackOutOfBounds","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/nextNoTrackAvailable":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNextNoTrackAvailable"}],"kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nextNoTrackAvailable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/nextNoTrackAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/nextnotrackavailable","title":"AutomixSDKErrorCode.nextNoTrackAvailable","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/offWhileTurningOn":{"url":"\/documentation\/automixiq\/automixsdkerrorcode\/offwhileturningon","type":"topic","abstract":[],"title":"AutomixSDKErrorCode.offWhileTurningOn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"offWhileTurningOn","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offWhileTurningOn","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffWhileTurningOn"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/loadTracksOutOfBounds":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracksOutOfBounds","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.loadTracksOutOfBounds","url":"\/documentation\/automixiq\/automixsdkerrorcode\/loadtracksoutofbounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/backNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backNoTrackAvailable"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.backNoTrackAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/backnotrackavailable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/backNoTrackAvailable","navigatorTitle":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/addTrackInternalError":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.addTrackInternalError","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackInternalError","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackInternalError"}],"role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/addtrackinternalerror","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackInternalError"}]},"doc://org.cocoapods.AutomixIQ/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/loadTracksEmptyPlaylist":{"title":"AutomixSDKErrorCode.loadTracksEmptyPlaylist","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/loadtracksemptyplaylist","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotLoadExplicitLyricsTrack":{"role":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotloadexplicitlyricstrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/removeTrackOutOfBounds":{"type":"topic","title":"AutomixSDKErrorCode.removeTrackOutOfBounds","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/removeTrackOutOfBounds","abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/removetrackoutofbounds","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeTrackOutOfBounds"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/init(rawValue:)":{"abstract":[],"type":"topic","url":"\/documentation\/automixiq\/automixsdkerrorcode\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/init(rawValue:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/playAlreadyPlaying":{"title":"AutomixSDKErrorCode.playAlreadyPlaying","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playAlreadyPlaying","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/playalreadyplaying","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playAlreadyPlaying"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","type":"topic","abstract":[{"type":"text","text":"AutomixSDK error codes"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/seekNoCurrentTrack":{"title":"AutomixSDKErrorCode.seekNoCurrentTrack","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoCurrentTrack","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/seeknocurrenttrack","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"seekNoCurrentTrack","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/onAlreadyTurningOn":{"title":"AutomixSDKErrorCode.onAlreadyTurningOn","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onAlreadyTurningOn","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/onalreadyturningon","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAlreadyTurningOn"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Errors-article":{"title":"Errors","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article","abstract":[{"type":"text","text":"What errors the AutomixIQ player can issue to help with player integration"}],"url":"\/documentation\/automixiq\/errors-article","role":"article","kind":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/Equatable-Implementations","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/equatable-implementations","role":"collectionGroup","kind":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/unimplemented":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnimplemented"}],"title":"AutomixSDKErrorCode.unimplemented","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unimplemented","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/unimplemented","url":"\/documentation\/automixiq\/automixsdkerrorcode\/unimplemented","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/failedToStop":{"url":"\/documentation\/automixiq\/automixsdkerrorcode\/failedtostop","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/failedToStop","abstract":[],"type":"topic","kind":"symbol","title":"AutomixSDKErrorCode.failedToStop","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToStop"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeFailedToStop","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotStartAudioEngine":{"role":"symbol","title":"AutomixSDKErrorCode.cannotStartAudioEngine","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotStartAudioEngine","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotstartaudioengine","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotStartAudioEngine"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotStartAudioEngine"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotSetupAVAudioSession":{"url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotsetupavaudiosession","title":"AutomixSDKErrorCode.cannotSetupAVAudioSession","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotSetupAVAudioSession","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/notMainThread":{"title":"AutomixSDKErrorCode.notMainThread","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/notMainThread","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/notmainthread","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notMainThread","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeNotMainThread","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/reorderMissingTrack":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeReorderMissingTrack"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/reorderMissingTrack","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/reordermissingtrack","type":"topic","title":"AutomixSDKErrorCode.reorderMissingTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderMissingTrack"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkNotOn":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotOn"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdknoton","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotOn","abstract":[],"title":"AutomixSDKErrorCode.sdkNotOn","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/noInternetAvailable":{"title":"AutomixSDKErrorCode.noInternetAvailable","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noInternetAvailable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/nointernetavailable","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeNoInternetAvailable","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cancelled":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cancelled","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCancelled"}],"kind":"symbol","role":"symbol","title":"AutomixSDKErrorCode.cancelled","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cancelled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/addTrackOutOfBounds":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackOutOfBounds"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.addTrackOutOfBounds","url":"\/documentation\/automixiq\/automixsdkerrorcode\/addtrackoutofbounds","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/pauseAlreadyPaused":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pauseAlreadyPaused","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.pauseAlreadyPaused","url":"\/documentation\/automixiq\/automixsdkerrorcode\/pausealreadypaused","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/pauseAlreadyPaused","navigatorTitle":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotCreateChannelLayout":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.cannotCreateChannelLayout","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotcreatechannellayout","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateChannelLayout","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/stopLoopingNoLoopingTrack":{"type":"topic","title":"AutomixSDKErrorCode.stopLoopingNoLoopingTrack","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","abstract":[],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/stoploopingnoloopingtrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/onWhileTurningOff":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOnWhileTurningOff","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onWhileTurningOff","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"onWhileTurningOff","kind":"identifier"}],"title":"AutomixSDKErrorCode.onWhileTurningOff","type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/onwhileturningoff"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkAlreadyOn":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkAlreadyOn","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.sdkAlreadyOn","url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdkalreadyon","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyOn","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotRestoreAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotRestoreAudioSession"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.cannotRestoreAudioSession","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotrestoreaudiosession","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotRestoreAudioSession","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/playToEndMissingTrack":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}],"type":"topic","title":"AutomixSDKErrorCode.playToEndMissingTrack","role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/playtoendmissingtrack","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMissingTrack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"playToEndMissingTrack"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/offAlreadyTurningOff":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"offAlreadyTurningOff","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.offAlreadyTurningOff","url":"\/documentation\/automixiq\/automixsdkerrorcode\/offalreadyturningoff","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offAlreadyTurningOff","navigatorTitle":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkAlreadyInitialised":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkAlreadyInitialised"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.sdkAlreadyInitialised","url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdkalreadyinitialised","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyInitialised","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/previousNoTrackAvailable":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"previousNoTrackAvailable","kind":"identifier"}],"role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.previousNoTrackAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/previousnotrackavailable","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/previousNoTrackAvailable","navigatorTitle":[{"text":"AutomixSDKErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/unimplemented"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article"],"generated":true,"title":"Errors"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/title","value":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"},{"value":[{"text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/fragments"},{"value":"AutomixSDKErrorCodePlayToEndMixEnd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playToEndMixEnd\/title"},{"value":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playToEndMixEnd\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/title","value":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/fragments"},{"value":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/title","value":"AutomixSDKErrorCodeSdkInitialisationUnauthorised","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/fragments"},{"value":"AutomixSDKErrorCodeSdkNotInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotInitialised\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotInitialised\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialised"}]},{"value":"AutomixSDKErrorCodeCannotCreateInputBuffer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodeAddTrackNoMetadata","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackNoMetadata\/title"},{"value":[{"text":"AutomixSDKErrorCodeAddTrackNoMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackNoMetadata\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoTrackAvailable\/title","value":"AutomixSDKErrorCodeSeekNoTrackAvailable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoTrackAvailable\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeSeekNoTrackAvailable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/title","op":"replace","value":"AutomixSDKErrorCodeMoveTrackOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/fragments","value":[{"text":"AutomixSDKErrorCodeMoveTrackOutOfBounds","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeNextNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1nextNoTrackAvailable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNextNoTrackAvailable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1nextNoTrackAvailable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offWhileTurningOn\/title","value":"AutomixSDKErrorCodeOffWhileTurningOn","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offWhileTurningOn\/fragments","value":[{"text":"AutomixSDKErrorCodeOffWhileTurningOn","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/title","value":"AutomixSDKErrorCodeLoadTracksOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksOutOfBounds"}]},{"value":"AutomixSDKErrorCodeBackNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1backNoTrackAvailable\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1backNoTrackAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackInternalError\/title","op":"replace","value":"AutomixSDKErrorCodeAddTrackInternalError"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackInternalError\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackInternalError"}],"op":"replace"},{"value":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/title","value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/fragments"},{"value":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playAlreadyPlaying\/title","value":"AutomixSDKErrorCodePlayAlreadyPlaying"},{"value":[{"text":"AutomixSDKErrorCodePlayAlreadyPlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playAlreadyPlaying\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoCurrentTrack\/title","value":"AutomixSDKErrorCodeSeekNoCurrentTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoCurrentTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeOnAlreadyTurningOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1onAlreadyTurningOn\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnAlreadyTurningOn"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1onAlreadyTurningOn\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1unimplemented\/title","value":"AutomixSDKErrorCodeUnimplemented","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeUnimplemented"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1unimplemented\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1failedToStop\/title","op":"replace","value":"AutomixSDKErrorCodeFailedToStop"},{"value":[{"text":"AutomixSDKErrorCodeFailedToStop","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1failedToStop\/fragments","op":"replace"},{"value":"AutomixSDKErrorCodeCannotStartAudioEngine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotStartAudioEngine\/title"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeCannotStartAudioEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotStartAudioEngine\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodeCannotSetupAVAudioSession","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/fragments","value":[{"text":"AutomixSDKErrorCodeCannotSetupAVAudioSession","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1notMainThread\/title","value":"AutomixSDKErrorCodeNotMainThread"},{"value":[{"text":"AutomixSDKErrorCodeNotMainThread","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1notMainThread\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1reorderMissingTrack\/title","value":"AutomixSDKErrorCodeReorderMissingTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1reorderMissingTrack\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeReorderMissingTrack","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSdkNotOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotOn\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotOn\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1noInternetAvailable\/title","value":"AutomixSDKErrorCodeNoInternetAvailable","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1noInternetAvailable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cancelled\/title","value":"AutomixSDKErrorCodeCancelled"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cancelled\/fragments","value":[{"text":"AutomixSDKErrorCodeCancelled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackOutOfBounds\/title","op":"replace","value":"AutomixSDKErrorCodeAddTrackOutOfBounds"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackOutOfBounds\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackOutOfBounds"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1pauseAlreadyPaused\/title","value":"AutomixSDKErrorCodePauseAlreadyPaused"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1pauseAlreadyPaused\/fragments","value":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/title","value":"AutomixSDKErrorCodeCannotCreateChannelLayout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateChannelLayout"}],"op":"replace"},{"value":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1onWhileTurningOff\/title","op":"replace","value":"AutomixSDKErrorCodeOnWhileTurningOff"},{"value":[{"text":"AutomixSDKErrorCodeOnWhileTurningOff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1onWhileTurningOff\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodeSdkAlreadyOn","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyOn\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyOn\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKErrorCodeCannotRestoreAudioSession","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/title"},{"value":[{"text":"AutomixSDKErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playToEndMissingTrack\/title","value":"AutomixSDKErrorCodePlayToEndMissingTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1playToEndMissingTrack\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodePlayToEndMissingTrack","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeOffAlreadyTurningOff","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offAlreadyTurningOff\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offAlreadyTurningOff\/fragments","value":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodeSdkAlreadyInitialised","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1previousNoTrackAvailable\/title","value":"AutomixSDKErrorCodePreviousNoTrackAvailable"},{"value":[{"text":"AutomixSDKErrorCodePreviousNoTrackAvailable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1previousNoTrackAvailable\/fragments"}]}]}