{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pauseAlreadyPaused","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/pausealreadypaused"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/pausealreadypaused"]}],"metadata":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"roleHeading":"Case","title":"AutomixSDKErrorCode.pauseAlreadyPaused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pauseAlreadyPaused"}],"role":"symbol","externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodePauseAlreadyPaused","symbolKind":"case","modules":[{"name":"PacemakerRadio"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/pauseAlreadyPaused":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/pausealreadypaused","title":"AutomixSDKErrorCode.pauseAlreadyPaused","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pauseAlreadyPaused","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","title":"AutomixSDKErrorCode","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AutomixSDKErrorCodePauseAlreadyPaused","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePauseAlreadyPaused"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/title","op":"replace","value":"AutomixSDKErrorCodePauseAlreadyPaused"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/fragments","value":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}