{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"PacemakerRadio"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeCounters(py)mixPlays","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mixPlays","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"mixPlays"}],"title":"mixPlays","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixplays"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixplays"]}],"sections":[],"abstract":[{"type":"text","text":"The number of times this mixtape has been played"}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters\/mixPlays","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlays"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"title":"AutomixSDKMixtapeCounters","abstract":[{"text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters/mixPlays":{"navigatorTitle":[{"text":"mixPlays","kind":"identifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixplays","title":"mixPlays","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mixPlays","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters\/mixPlays","kind":"symbol","abstract":[{"text":"The number of times this mixtape has been played","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"mixPlays","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"mixPlays"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlays"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"op":"replace"},{"value":"mixPlays","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters~1mixPlays\/title","op":"replace"},{"value":[{"text":"mixPlays","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters~1mixPlays\/fragments"}]}]}