{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKPlaylistOperation","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","text":"AutomixSDKPlaylistOperation"},{"text":"]]?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"playlistDiff","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus(py)playlistDiff","roleHeading":"Instance Property","modules":[{"name":"PacemakerRadio"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKPlaylistOperation","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKPlaylistOperation"},{"text":"]]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"playlistDiff"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playlistDiff","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playlistdiff"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playlistdiff"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","title":"AutomixSDKStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"title":"AutomixSDKPlaylistOperation","navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus/playlistDiff":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playlistDiff"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : [","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKPlaylistOperation","text":"AutomixSDKPlaylistOperation","kind":"typeIdentifier"},{"kind":"text","text":"]]?"}],"title":"playlistDiff","url":"\/documentation\/pacemakerradio\/automixsdkstatus\/playlistdiff","navigatorTitle":[{"kind":"identifier","text":"playlistDiff"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playlistDiff"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"role":"collection","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"type":"topic","url":"\/documentation\/pacemakerradio"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"playlistDiff","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"playlistDiff","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSArray<AutomixSDKPlaylistOperation *> *>"},{"text":" * ","kind":"text"},{"text":"playlistDiff","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"AutomixSDKPlaylistOperation","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title"},{"op":"replace","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playlistDiff\/title","value":"playlistDiff","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playlistDiff\/fragments","op":"replace","value":[{"kind":"identifier","text":"playlistDiff"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}