{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableFailedTrackLoadIdentifiers","title":"AutomixSDKStatusVariable.failedTrackLoadIdentifiers","roleHeading":"Case","modules":[{"name":"AutomixIQ"}]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/failedtrackloadidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/failedtrackloadidentifiers"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","url":"\/documentation\/automixiq\/automixsdkstatusvariable","abstract":[{"type":"text","text":"AutomixSDK play event type"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/failedTrackLoadIdentifiers":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"title":"AutomixSDKStatusVariable.failedTrackLoadIdentifiers","type":"topic","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/failedtrackloadidentifiers","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/title","op":"replace","value":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"},{"value":[{"text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}