{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/indicesPerSecond","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/nextTrack0SecondsAnchorTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/placeholder","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/trackDurationSeconds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/xAxis","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/yAxis"],"title":"Instance Properties"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"anchor":"Data-models","title":"Data models"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","title":"AutomixSDKWaveformModel","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkwaveformmodel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkwaveformmodel"]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"kind":"symbol","title":"AutomixSDKMixtapeTrackImage","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","abstract":[{"text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/rightTransitionStartTime":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartTime","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightTransitionStartTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"role":"symbol","title":"rightTransitionStartTime","navigatorTitle":[{"kind":"identifier","text":"rightTransitionStartTime"}],"abstract":[{"text":"The time in the track the right transition starts at","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/righttransitionstarttime"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"title":"AutomixSDKPlaylistOperation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/rightTransitionStartIndex":{"kind":"symbol","title":"rightTransitionStartIndex","role":"symbol","navigatorTitle":[{"text":"rightTransitionStartIndex","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartIndex","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionStartIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/righttransitionstartindex","abstract":[{"type":"text","text":"The index the right transition starts"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKArtistModel":{"role":"symbol","abstract":[{"text":"AutomixSDKArtistModel models an artist.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKArtistModel"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"url":"\/documentation\/pacemakerradio\/automixsdkartistmodel","title":"AutomixSDKArtistModel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKGenericList":{"url":"\/documentation\/pacemakerradio\/automixsdkgenericlist","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKGenericList"}],"kind":"symbol","title":"AutomixSDKGenericList","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","abstract":[{"text":"AutomixSDKGenericList models a list of things","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKGenericList"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Data-models-article":{"url":"\/documentation\/pacemakerradio\/data-models-article","kind":"article","title":"Data models","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","abstract":[{"text":"How data is passed to and from PacemakerRadio","type":"text"}],"type":"topic","role":"article"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/leftTransitionEndIndex":{"title":"leftTransitionEndIndex","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndIndex","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftTransitionEndIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The index the left transition ends"}],"type":"topic","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/lefttransitionendindex","navigatorTitle":[{"text":"leftTransitionEndIndex","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","title":"AutomixSDKTrackModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","kind":"symbol","type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/rightTransitionDuration":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionDuration","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/righttransitionduration","title":"rightTransitionDuration","abstract":[{"type":"text","text":"The duration of the right transition in track time"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"rightTransitionDuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rightTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformBlob":{"title":"AutomixSDKWaveformBlob","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformblob","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeLite":{"role":"symbol","abstract":[{"text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapelite","title":"AutomixSDKMixtapeLite","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"kind":"symbol","title":"AutomixSDKMixtapeTrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/rightTransitionEndIndex":{"abstract":[{"type":"text","text":"The index the right transition ends"}],"title":"rightTransitionEndIndex","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightTransitionEndIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndIndex","role":"symbol","navigatorTitle":[{"text":"rightTransitionEndIndex","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/righttransitionendindex"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/leftTransitionStartTime":{"abstract":[{"text":"The time in the track the left transition starts at","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"leftTransitionStartTime"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftTransitionStartTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/lefttransitionstarttime","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartTime","title":"leftTransitionStartTime","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKList":{"title":"AutomixSDKList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdklist","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKList"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","title":"AutomixSDKStatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/leftTransitionEndTime":{"title":"leftTransitionEndTime","abstract":[{"text":"The time in the track the left transition ends at","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/lefttransitionendtime","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftTransitionEndTime"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndTime","navigatorTitle":[{"text":"leftTransitionEndTime","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtape","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtape"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"title":"AutomixSDKMixtape","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","abstract":[{"type":"text","text":"AutomixSDKMixtape models a mixtape"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel","kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"type":"topic","title":"AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPluginMetadataModel":{"title":"AutomixSDKPluginMetadataModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkpluginmetadatamodel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"abstract":[{"text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/placeholder":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/placeholder","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/placeholder","title":"placeholder","role":"symbol","type":"topic","abstract":[{"text":"true if this waveform is just placeholder data, false otherwise","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/xAxis":{"abstract":[{"type":"text","text":"The normalised X axis, from 0 (meaning beginning of the track) to 1 (meaning end of the track)"}],"navigatorTitle":[{"text":"xAxis","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xAxis"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/xaxis","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/xAxis","title":"xAxis","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/rightTransitionEndTime":{"navigatorTitle":[{"text":"rightTransitionEndTime","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/righttransitionendtime","type":"topic","abstract":[{"type":"text","text":"The time in the track the right transition ends at"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rightTransitionEndTime","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"rightTransitionEndTime","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndTime"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/indicesPerSecond":{"abstract":[{"text":"The number of indices representing a second (x-axis scale)","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indicesPerSecond"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicesPerSecond"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/indicespersecond","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/indicesPerSecond","title":"indicesPerSecond","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"role":"collection","type":"topic","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/leftTransitionStartIndex":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftTransitionStartIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartIndex","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/lefttransitionstartindex","title":"leftTransitionStartIndex","role":"symbol","type":"topic","abstract":[{"text":"The index the left transition starts","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"leftTransitionStartIndex"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"title":"AutomixSDKMixtapeCounters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"abstract":[{"text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/leftTransitionDuration":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftTransitionDuration","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"title":"leftTransitionDuration","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionDuration","kind":"symbol","abstract":[{"text":"The duration of the left transition in track time","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/lefttransitionduration","navigatorTitle":[{"kind":"identifier","text":"leftTransitionDuration"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"title":"TunedAuthenticationResponse","abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/nextTrack0SecondsAnchorTime":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/nextTrack0SecondsAnchorTime","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/nexttrack0secondsanchortime","abstract":[{"type":"text","text":"The time in this track the next track’s 0 seconds position would be if played, helper to align waveforms when rendering tracnsitions"}],"role":"symbol","title":"nextTrack0SecondsAnchorTime","navigatorTitle":[{"text":"nextTrack0SecondsAnchorTime","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/yAxis":{"abstract":[{"type":"text","text":"The energy of the track over time"}],"navigatorTitle":[{"text":"yAxis","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"yAxis","kind":"identifier"},{"kind":"text","text":": ["},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]?","kind":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/yaxis","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/yAxis","title":"yAxis","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/trackDurationSeconds":{"abstract":[{"text":"The duration of the track in seconds","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"trackDurationSeconds"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackDurationSeconds","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/trackdurationseconds","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/trackDurationSeconds","title":"trackDurationSeconds","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/init","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/init","title":"init","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"AutomixSDKWaveformModel","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/indicesPerSecond","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionEndTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/leftTransitionStartTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/nextTrack0SecondsAnchorTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/placeholder","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionDuration","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionEndTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartIndex","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/rightTransitionStartTime","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/trackDurationSeconds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/xAxis","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/yAxis"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":[{"title":"Data models","generated":true,"anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"]}],"op":"replace"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title","value":"AutomixSDKMixtapeTrackImage"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"op":"replace"},{"value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle"},{"value":"rightTransitionStartTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionStartTime\/title"},{"op":"replace","value":[{"text":"rightTransitionStartTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionStartTime\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments"},{"value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionStartIndex\/title","value":"rightTransitionStartIndex"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionStartIndex\/fragments","value":[{"text":"rightTransitionStartIndex","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/title","value":"AutomixSDKArtistModel"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/fragments","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionEndIndex\/title","value":"leftTransitionEndIndex"},{"value":[{"kind":"identifier","text":"leftTransitionEndIndex"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionEndIndex\/fragments"},{"op":"replace","value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionDuration\/title","op":"replace","value":"rightTransitionDuration"},{"value":[{"text":"rightTransitionDuration","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionDuration\/fragments","op":"replace"},{"value":"AutomixSDKWaveformBlob","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/fragments","value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}]},{"value":"AutomixSDKMixtapeLite","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeLite"}]},{"value":"AutomixSDKMixtapeTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"value":"rightTransitionEndIndex","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionEndIndex\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionEndIndex\/fragments","op":"replace","value":[{"text":"rightTransitionEndIndex","kind":"identifier"}]},{"value":"leftTransitionStartTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionStartTime\/title"},{"value":[{"text":"leftTransitionStartTime","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionStartTime\/fragments","op":"replace"},{"value":"AutomixSDKList","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/fragments","value":[{"text":"AutomixSDKList","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKList"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionEndTime\/title","op":"replace","value":"leftTransitionEndTime"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionEndTime\/fragments","value":[{"kind":"identifier","text":"leftTransitionEndTime"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title","op":"replace","value":"AutomixSDKMixtape"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1placeholder\/title","value":"placeholder","op":"replace"},{"value":[{"text":"placeholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1placeholder\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1xAxis\/title","op":"replace","value":"xAxis"},{"value":[{"kind":"identifier","text":"xAxis"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1xAxis\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionEndTime\/title","value":"rightTransitionEndTime","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1rightTransitionEndTime\/fragments","value":[{"kind":"identifier","text":"rightTransitionEndTime"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1indicesPerSecond\/title","value":"indicesPerSecond","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1indicesPerSecond\/fragments","value":[{"text":"indicesPerSecond","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionStartIndex\/title","value":"leftTransitionStartIndex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionStartIndex\/fragments","value":[{"kind":"identifier","text":"leftTransitionStartIndex"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},{"value":"leftTransitionDuration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionDuration\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1leftTransitionDuration\/fragments","op":"replace","value":[{"text":"leftTransitionDuration","kind":"identifier"}]},{"value":"TunedAuthenticationResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},{"op":"replace","value":"nextTrack0SecondsAnchorTime","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1nextTrack0SecondsAnchorTime\/title"},{"value":[{"kind":"identifier","text":"nextTrack0SecondsAnchorTime"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1nextTrack0SecondsAnchorTime\/fragments","op":"replace"},{"value":"yAxis","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1yAxis\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1yAxis\/fragments","value":[{"text":"yAxis","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1trackDurationSeconds\/title","op":"replace","value":"trackDurationSeconds"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1trackDurationSeconds\/fragments","value":[{"text":"trackDurationSeconds","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}