{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSManagedObjectID"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSFetchRequestResult","doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSCopying","doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH","doc:\/\/org.cocoapods.PacemakerRadio\/s8SendableP"],"kind":"relationships"}],"seeAlsoSections":[{"title":"Persistency","anchor":"Persistency","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"metadata":{"symbolKind":"class","modules":[{"name":"PacemakerRadio"}],"externalID":"c:objc(cs)AutomixSDKTransitionLogID","title":"AutomixSDKTransitionLogID","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdktransitionlogid"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID"},"references":{"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogID":{"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKPlayLogID","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylogid","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"title":"AutomixSDKPlayLogID"},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogAttributes":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLogAttributes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogAttributes"}],"title":"AutomixSDKTransitionLogAttributes","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktransitionlogattributes"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Persistency-article":{"abstract":[{"text":"What AutomixIQ stores locally","type":"text"}],"type":"topic","kind":"article","title":"Persistency","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article","role":"article","url":"\/documentation\/pacemakerradio\/persistency-article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogID":{"abstract":[],"title":"AutomixSDKTransitionLogID","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktransitionlogid"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","type":"topic","title":"AutomixSDKPlaybackEventType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"role":"collection","type":"topic","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogAttributes":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}],"title":"AutomixSDKPlayLogAttributes","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","url":"\/documentation\/pacemakerradio\/automixsdkplaylogattributes","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSFetchRequestResult":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSFetchRequestResult","type":"unresolvable","title":"CoreData.NSFetchRequestResult"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLog":{"kind":"symbol","abstract":[],"title":"AutomixSDKTransitionLog","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktransitionlog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKTransitionLog","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKTransitionLog","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSManagedObjectID":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSManagedObjectID","type":"unresolvable","title":"CoreData.NSManagedObjectID"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLog":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","url":"\/documentation\/pacemakerradio\/automixsdkplaylog","navigatorTitle":[{"text":"AutomixSDKPlayLog","kind":"identifier"}],"title":"AutomixSDKPlayLog","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlayLog","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.PacemakerRadio/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSCopying":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSCopying","type":"unresolvable","title":"Foundation.NSCopying"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]}]}]}