{"metadata":{"externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePreferredTransitionDurationSeconds","roleHeading":"Case","title":"AutomixSDKStatusVariable.preferredTransitionDurationSeconds","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}]},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/preferredtransitiondurationseconds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/preferredtransitiondurationseconds"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/preferredTransitionDurationSeconds":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/preferredtransitiondurationseconds","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"title":"AutomixSDKStatusVariable.preferredTransitionDurationSeconds","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/title","value":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/fragments","value":[{"text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},{"value":"AutomixSDKStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}