{"kind":"symbol","abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a reorder tracks command."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatus\/canreordertracks"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatus\/canreordertracks"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canReorderTracks"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)canReorderTracks","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canReorderTracks","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"canReorderTracks"}],"title":"canReorderTracks"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/canReorderTracks":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canReorderTracks","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a reorder tracks command."}],"role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatus\/canreordertracks","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canReorderTracks","navigatorTitle":[{"text":"canReorderTracks","kind":"identifier"}],"type":"topic","kind":"symbol","title":"canReorderTracks"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatus"}],"abstract":[{"text":"AutomixSDKStatus models the State of the AutomixSDK during playback.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatus","title":"AutomixSDKStatus","type":"topic","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"canReorderTracks","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"canReorderTracks","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canReorderTracks"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canReorderTracks\/title","value":"canReorderTracks"},{"value":[{"kind":"identifier","text":"canReorderTracks"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canReorderTracks\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}