{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"]]},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdk\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdk\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"applyEnterTransition","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyExitTransition"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"AutomixSDKWaveformModel","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","modules":[{"name":"PacemakerRadio"}],"symbolKind":"method","navigatorTitle":[{"text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDK(im)waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"waveformDataForTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyEnterTransition"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyExitTransition"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to the start of the track to be applied to the waveform data, false otherwise","type":"text"}]}],"name":"applyEnterTransition"},{"content":[{"inlineContent":[{"text":"True if you want the transition to the end of the track to be applied to the waveform data, false otherwise","type":"text"}],"type":"paragraph"}],"name":"applyExitTransition"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"returns the waveform data"}],"type":"paragraph"}]}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic","kind":"symbol","title":"PacemakerRadio","role":"collection","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"title":"AutomixSDK","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDK"}],"url":"\/documentation\/pacemakerradio\/automixsdk","navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)":{"navigatorTitle":[{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk\/waveformdatafortrack(identifier:applyentertransition:applyexittransition:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)","kind":"symbol","abstract":[{"type":"text","text":"Gets the waveform data for a track."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"waveformDataForTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyEnterTransition"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"applyExitTransition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"title":"waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","role":"symbol","title":"AutomixSDKWaveformModel","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"applyEnterTransition:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"applyEnterTransition","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"applyExitTransition:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"applyExitTransition"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of a track","type":"text"}]}]},{"name":"applyEnterTransition","content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to the start of the track to be applied to the waveform data, false otherwise","type":"text"}]}]},{"name":"applyExitTransition","content":[{"type":"paragraph","inlineContent":[{"text":"True if you want the transition to the end of the track to be applied to the waveform data, false otherwise","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments","value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/title","value":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1waveformDataForTrack(identifier:applyEnterTransition:applyExitTransition:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"waveformDataForTrackWithIdentifier:applyEnterTransition:applyExitTransition:","kind":"identifier"}]},{"value":"AutomixSDKWaveformModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}