{"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canBack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canMixNow","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canOnOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSeek","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/muted","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playSpeed","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/replayOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/vinylStartStop"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/RawRepresentable-Implementations"]}],"metadata":{"role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"title":"AutomixSDKStatusVariable","roleHeading":"Enumeration","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","interfaceLanguage":"swift"},"abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/explicitLyricsFiltering":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/explicitLyricsFiltering","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/explicitlyricsfiltering","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"explicitLyricsFiltering","kind":"identifier"}],"title":"AutomixSDKStatusVariable.explicitLyricsFiltering","navigatorTitle":[{"text":"AutomixSDKStatusVariableExplicitLyricsFiltering","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"role":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/failedTrackLoadIdentifiers":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/failedtrackloadidentifiers","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"title":"AutomixSDKStatusVariable.failedTrackLoadIdentifiers","navigatorTitle":[{"text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/replayOn":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/replayOn","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/replayon","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replayOn","kind":"identifier"}],"title":"AutomixSDKStatusVariable.replayOn","navigatorTitle":[{"text":"AutomixSDKStatusVariableReplayOn","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/vinylStartStop":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/vinylStartStop","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/vinylstartstop","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"vinylStartStop","kind":"identifier"}],"title":"AutomixSDKStatusVariable.vinylStartStop","navigatorTitle":[{"text":"AutomixSDKStatusVariableVinylStartStop","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackCurrentTime":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackCurrentTime","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackcurrenttime","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackCurrentTime","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playingTrackCurrentTime","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackCurrentTime","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/requestedPauseTrackIdentifier":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedPauseTrackIdentifier","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/requestedpausetrackidentifier","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestedPauseTrackIdentifier","kind":"identifier"}],"title":"AutomixSDKStatusVariable.requestedPauseTrackIdentifier","navigatorTitle":[{"text":"AutomixSDKStatusVariableRequestedPauseTrackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackIdentifier":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackIdentifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackidentifier","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIdentifier","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackIdentifier","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playingTrackIdentifier","kind":"symbol","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/muted":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/muted","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/muted","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muted","kind":"identifier"}],"title":"AutomixSDKStatusVariable.muted","navigatorTitle":[{"text":"AutomixSDKStatusVariableMuted","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackIndex":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIndex","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackindex","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackIndex","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playingTrackIndex","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackIndex","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/preferredTransitionDurationSeconds":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/preferredtransitiondurationseconds","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredTransitionDurationSeconds","kind":"identifier"}],"title":"AutomixSDKStatusVariable.preferredTransitionDurationSeconds","navigatorTitle":[{"text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/normalisedVolume":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/normalisedVolume","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/normalisedvolume","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"normalisedVolume","kind":"identifier"}],"title":"AutomixSDKStatusVariable.normalisedVolume","navigatorTitle":[{"text":"AutomixSDKStatusVariableNormalisedVolume","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playlistDiff":{"role":"symbol","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playlistdiff","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playlistDiff","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlistDiff","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaylistDiff","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackStreamingProgress":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackStreamingProgress","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackstreamingprogress","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playingTrackStreamingProgress","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playingTrackStreamingProgress","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canMixNow":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canMixNow","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canmixnow","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canMixNow","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canMixNow","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanMixNow","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canReorderTracks":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canReorderTracks","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canreordertracks","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canReorderTracks","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canReorderTracks","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanReorderTracks","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playSpeed":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playSpeed","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playspeed","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playSpeed","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playSpeed","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaySpeed","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playing":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playing","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playing","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playing","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playing","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaying","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canBack":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canBack","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canback","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canBack","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canBack","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanBack","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canSkipToPrevious":{"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canskiptoprevious","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToPrevious","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToPrevious"}],"role":"symbol","title":"AutomixSDKStatusVariable.canSkipToPrevious"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackTotalTime":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackTotalTime","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackTotalTime"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackTotalTime"}],"kind":"symbol","type":"topic","title":"AutomixSDKStatusVariable.playingTrackTotalTime","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtracktotaltime","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/RawRepresentable-Implementations","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canPlayPause":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canPlayPause","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canplaypause","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canPlayPause","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canPlayPause","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/mixing":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixing","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixing"}],"title":"AutomixSDKStatusVariable.mixing","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableMixing"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/mixing"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/requestedLoopTrackIdentifier":{"role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/requestedlooptrackidentifier","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedLoopTrackIdentifier","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestedLoopTrackIdentifier"}],"abstract":[],"title":"AutomixSDKStatusVariable.requestedLoopTrackIdentifier","navigatorTitle":[{"text":"AutomixSDKStatusVariableRequestedLoopTrackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canOnOff":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canOnOff","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canonoff","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canOnOff","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canOnOff","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanOnOff","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/init(rawValue:)","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/init(rawvalue:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/transitionStartTimeSeconds":{"kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/transitionstarttimeseconds","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/transitionStartTimeSeconds","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"transitionStartTimeSeconds","kind":"identifier"}],"abstract":[],"title":"AutomixSDKStatusVariable.transitionStartTimeSeconds","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableTransitionStartTimeSeconds"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/Equatable-Implementations","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/equatable-implementations","role":"collectionGroup","type":"topic","kind":"article","title":"Equatable Implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/readyToPlay":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/readyToPlay","type":"topic","title":"AutomixSDKStatusVariable.readyToPlay","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"readyToPlay"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/readytoplay","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStatusVariableReadyToPlay","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/nextTransitionDuration":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/nextTransitionDuration","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/nexttransitionduration","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nextTransitionDuration","kind":"identifier"}],"title":"AutomixSDKStatusVariable.nextTransitionDuration","navigatorTitle":[{"text":"AutomixSDKStatusVariableNextTransitionDuration","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canSkipToNext":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToNext","abstract":[],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSkipToNext","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canSkipToNext","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canskiptonext","title":"AutomixSDKStatusVariable.canSkipToNext","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playlist":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlist","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playlist","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playlist"}],"title":"AutomixSDKStatusVariable.playlist","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylist"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackOriginalSessionId":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playingTrackOriginalSessionId","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playingTrackOriginalSessionId","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackOriginalSessionId","abstract":[],"type":"topic","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackOriginalSessionId","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackoriginalsessionid","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canSeek":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSeek","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canseek","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"canSeek","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canSeek","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSeek","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/mixId":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixId"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/mixid","kind":"symbol","title":"AutomixSDKStatusVariable.mixId","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableMixId"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixId","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatusVariable"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canBack","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canMixNow","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canOnOff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canPlayPause","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canReorderTracks","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSeek","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToNext","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canSkipToPrevious","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/explicitLyricsFiltering","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/mixing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/muted","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/nextTransitionDuration","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/normalisedVolume","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playSpeed","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playing","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackCurrentTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackOriginalSessionId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackStreamingProgress","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackTotalTime","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlist","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlistDiff","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/readyToPlay","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/replayOn","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedLoopTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/requestedPauseTrackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/transitionStartTimeSeconds","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/vinylStartStop"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1explicitLyricsFiltering\/title","value":"AutomixSDKStatusVariableExplicitLyricsFiltering"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableExplicitLyricsFiltering"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1explicitLyricsFiltering\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},{"value":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}]},{"value":"AutomixSDKStatusVariableReplayOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1replayOn\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableReplayOn"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1replayOn\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1vinylStartStop\/title","value":"AutomixSDKStatusVariableVinylStartStop"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1vinylStartStop\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableVinylStartStop"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackCurrentTime\/title","value":"AutomixSDKStatusVariablePlayingTrackCurrentTime","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackCurrentTime\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackCurrentTime"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1requestedPauseTrackIdentifier\/title","value":"AutomixSDKStatusVariableRequestedPauseTrackIdentifier","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1requestedPauseTrackIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableRequestedPauseTrackIdentifier"}]},{"value":"AutomixSDKStatusVariablePlayingTrackIdentifier","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIdentifier\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIdentifier\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariablePlayingTrackIdentifier","kind":"identifier"}]},{"value":"AutomixSDKStatusVariableMuted","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1muted\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1muted\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableMuted"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIndex\/title","value":"AutomixSDKStatusVariablePlayingTrackIndex"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIndex\/fragments","value":[{"text":"AutomixSDKStatusVariablePlayingTrackIndex","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/title","op":"replace"},{"value":[{"text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1normalisedVolume\/title","value":"AutomixSDKStatusVariableNormalisedVolume","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1normalisedVolume\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableNormalisedVolume"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlistDiff\/title","value":"AutomixSDKStatusVariablePlaylistDiff","op":"replace"},{"value":[{"text":"AutomixSDKStatusVariablePlaylistDiff","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlistDiff\/fragments"},{"op":"replace","value":"AutomixSDKStatusVariablePlayingTrackStreamingProgress","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackStreamingProgress\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackStreamingProgress\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariablePlayingTrackStreamingProgress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canMixNow\/title","value":"AutomixSDKStatusVariableCanMixNow","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariableCanMixNow","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canMixNow\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canReorderTracks\/title","value":"AutomixSDKStatusVariableCanReorderTracks"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanReorderTracks"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canReorderTracks\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playSpeed\/title","value":"AutomixSDKStatusVariablePlaySpeed"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaySpeed"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playSpeed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playing\/title","value":"AutomixSDKStatusVariablePlaying"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playing\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaying"}],"op":"replace"},{"op":"replace","value":"AutomixSDKStatusVariableCanBack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canBack\/title"},{"value":[{"text":"AutomixSDKStatusVariableCanBack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canBack\/fragments","op":"replace"},{"value":"AutomixSDKStatusVariableCanSkipToPrevious","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToPrevious\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToPrevious\/fragments"},{"value":"AutomixSDKStatusVariablePlayingTrackTotalTime","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackTotalTime\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackTotalTime"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackTotalTime\/fragments"},{"value":"AutomixSDKStatusVariableCanPlayPause","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canPlayPause\/title"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canPlayPause\/fragments"},{"op":"replace","value":"AutomixSDKStatusVariableMixing","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1mixing\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1mixing\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableMixing"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1requestedLoopTrackIdentifier\/title","op":"replace","value":"AutomixSDKStatusVariableRequestedLoopTrackIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1requestedLoopTrackIdentifier\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableRequestedLoopTrackIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canOnOff\/title","value":"AutomixSDKStatusVariableCanOnOff"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canOnOff\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanOnOff"}],"op":"replace"},{"value":"AutomixSDKStatusVariableTransitionStartTimeSeconds","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1transitionStartTimeSeconds\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1transitionStartTimeSeconds\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableTransitionStartTimeSeconds"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1readyToPlay\/title","value":"AutomixSDKStatusVariableReadyToPlay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1readyToPlay\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableReadyToPlay"}]},{"op":"replace","value":"AutomixSDKStatusVariableNextTransitionDuration","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1nextTransitionDuration\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1nextTransitionDuration\/fragments","value":[{"text":"AutomixSDKStatusVariableNextTransitionDuration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToNext\/title","value":"AutomixSDKStatusVariableCanSkipToNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSkipToNext\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToNext"}]},{"value":"AutomixSDKStatusVariablePlaylist","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlist\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlist\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylist"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackOriginalSessionId\/title","value":"AutomixSDKStatusVariablePlayingTrackOriginalSessionId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackOriginalSessionId\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackOriginalSessionId"}]},{"op":"replace","value":"AutomixSDKStatusVariableCanSeek","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSeek\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canSeek\/fragments","value":[{"text":"AutomixSDKStatusVariableCanSeek","kind":"identifier"}]},{"value":"AutomixSDKStatusVariableMixId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1mixId\/title"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1mixId\/fragments"}]}]}