{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToPrevious"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptoprevious"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptoprevious"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/canSkipToPrevious","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSkipToPrevious"}],"symbolKind":"case","title":"AutomixSDKStatusVariable.canSkipToPrevious","externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanSkipToPrevious","modules":[{"name":"PacemakerRadio"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}]},"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"title":"AutomixSDKStatusVariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/canSkipToPrevious":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canSkipToPrevious","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canSkipToPrevious","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/canSkipToPrevious","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptoprevious","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatusVariableCanSkipToPrevious"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableCanSkipToPrevious","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","op":"replace","value":"AutomixSDKStatusVariable"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1canSkipToPrevious\/title","value":"AutomixSDKStatusVariableCanSkipToPrevious","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1canSkipToPrevious\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToPrevious"}]}]}]}