{"abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"type":"text","text":" "},{"text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioSDKConfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","text":"RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]}]},{"kind":"parameters","parameters":[{"name":"config","content":[{"inlineContent":[{"text":"The RadioSDK configuration.","type":"text"}],"type":"paragraph"}]},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate."}]}],"name":"statusDelegate"},{"name":"radioUIDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the Radio SDK needs"}]}]},{"name":"musicCacheDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate providing cached track data and metadata."}]}]},{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"PacemakerRadio"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","text":"RadioSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","kind":"identifier"}],"title":"initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDK(cm)initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"abstract":[],"title":"RadioSDKConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkconfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"url":"\/documentation\/pacemakerradio\/tunedrestdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","title":"TunedRestDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","title":"TunedMusicCacheDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixSDKStatusObserverDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","text":"RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","kind":"typeIdentifier","text":"RadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","title":"initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","url":"\/documentation\/pacemakerradio\/radiosdk\/initialise(config:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)","abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"type":"text","text":" "},{"text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK":{"abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"title":"RadioSDK","role":"symbol","navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDK"}],"url":"\/documentation\/pacemakerradio\/radiosdk","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","title":"RadioUIDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:"},{"kind":"text","text":"("},{"text":"RadioSDKConfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"config"},{"kind":"text","text":" "},{"text":"tunedDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<TunedRestDelegate>","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tunedDelegate"},{"kind":"text","text":" "},{"text":"statusDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"statusDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"text":"radioUIDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"id<RadioUIDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radioUIDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicCacheDelegate:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"id<TunedMusicCacheDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"musicCacheDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"config","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The RadioSDK configuration."}]}]},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate."}]}],"name":"statusDelegate"},{"name":"radioUIDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of presenting user interfaces the Radio SDK needs","type":"text"}]}]},{"name":"musicCacheDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate providing cached track data and metadata."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","op":"replace","value":"RadioSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle","value":[{"text":"RadioSDKConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate","op":"replace"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle"},{"value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/title","value":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1initialise(config:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/title","value":"RadioSDK","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/fragments","op":"replace","value":[{"kind":"identifier","text":"RadioSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace"},{"op":"replace","value":[{"text":"RadioUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}