{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/stoploopingnoloopingtrack"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/stoploopingnoloopingtrack"]}],"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeStopLoopingNoLoopingTrack","symbolKind":"case","role":"symbol","title":"AutomixSDKErrorCode.stopLoopingNoLoopingTrack","roleHeading":"Case","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack"}]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/stopLoopingNoLoopingTrack":{"type":"topic","abstract":[],"role":"symbol","title":"AutomixSDKErrorCode.stopLoopingNoLoopingTrack","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"stopLoopingNoLoopingTrack","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/stoploopingnoloopingtrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"role":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixsdkerrorcode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","abstract":[{"type":"text","text":"AutomixSDK error codes"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/title","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]}]}]}