{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/mixPlaybackEnded"},"sections":[],"metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Case","role":"symbol","title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","externalID":"c:@M@AutomixIQ@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeMixPlaybackEnded","symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlaybackEnded"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/mixplaybackended"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/mixplaybackended"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Provide seamless transitions between tracks and beat-matched seek experience within your music player application in iOS, iPad."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","abstract":[{"type":"text","text":"AutomixSDK play event type"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/mixplaybackended","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlaybackEnded"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}