{"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncCheckDeviceStatus(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/cacheMetadata(_:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/getDeviceIdentifier()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/isLoggedIn()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/logAutomixSDKMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate"]},{"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"],"title":"Initializing AutomixIQ for use with a custom backend","generated":true,"anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"kind":"relationships"}],"metadata":{"roleHeading":"Protocol","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"symbolKind":"protocol","title":"AutomixSDKStreamingDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","title":"trackDownloadProgressChanged(trackId:progress:)","abstract":[{"text":"Called by AutomixIQ when a track download progress has changed.","type":"text"}],"type":"topic","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"type":"topic","url":"\/documentation\/automixiq\/automixsdkloglevel","title":"AutomixSDKLogLevel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","abstract":[{"type":"text","text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","navigatorTitle":[{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asyncGetStream","kind":"identifier"},{"kind":"text","text":"("},{"text":"streamingDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"newSessionId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required.","type":"text"}],"title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/syncGetCachedTrack(trackId:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","role":"symbol","navigatorTitle":[{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgetcachedtrack(trackid:)","title":"syncGetCachedTrack(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"type":"topic","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncCheckDeviceStatus(completion:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asynccheckdevicestatus(completion:)","navigatorTitle":[{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asyncCheckDeviceStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"canContinuePlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously"}],"title":"asyncCheckDeviceStatus(completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"title":"trackDownloadCompleted(trackId:data:)","kind":"symbol","navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","role":"symbol","abstract":[{"text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":")"}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompleted(trackid:data:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/logAutomixSDKMessage(logLevel:message:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/logAutomixSDKMessage(logLevel:message:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/logautomixsdkmessage(loglevel:message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"logLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKLogLevel","text":"AutomixSDKLogLevel","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"logAutomixSDKMessage(logLevel:message:)","navigatorTitle":[{"kind":"identifier","text":"logAutomixSDKMessageWithLogLevel:message:"}],"abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","kind":"article","url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","title":"Initializing AutomixIQ with a custom backend","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with a custom backend","type":"text"}],"type":"topic","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/syncGetTrackMetadata(trackId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"syncGetTrackMetadata","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetTrackMetadata(trackId:)","role":"symbol","navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgettrackmetadata(trackid:)","title":"syncGetTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available."}],"type":"topic","required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/isLoggedIn()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/isLoggedIn()","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/isloggedin()","navigatorTitle":[{"text":"isLoggedIn","kind":"identifier"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isLoggedIn"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise"}],"title":"isLoggedIn()","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/cacheMetadata(_:)":{"kind":"symbol","type":"topic","required":true,"navigatorTitle":[{"text":"cacheMetadata:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/cachemetadata(_:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/cacheMetadata(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cacheMetadata","kind":"identifier"},{"kind":"text","text":"(["},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"text":"])","kind":"text"}],"abstract":[{"text":"AutomixIQ calls this function to provide a chance to cache metadata to shortcut future requests.","type":"text"}],"title":"cacheMetadata(_:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"title":"AutomixSDKStreamingDelegate","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asyncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"track","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called by AutomixIQ when it requires the metadata of a track in order to load it."}],"title":"asyncGetTrackMetadata(trackId:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/getDeviceIdentifier()":{"title":"getDeviceIdentifier()","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/getdeviceidentifier()","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/getDeviceIdentifier()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getDeviceIdentifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getDeviceIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixSDKStreamingDelegate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncCheckDeviceStatus(completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/cacheMetadata(_:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/getDeviceIdentifier()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/isLoggedIn()","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/logAutomixSDKMessage(logLevel:message:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"anchor":"Initializing-AutomixIQ-for-use-with-a-custom-backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"],"title":"Initializing AutomixIQ for use with a custom backend","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","value":"trackDownloadProgressChangedWithTrackId:progress:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}]},{"op":"replace","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments"},{"value":"syncGetCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title","value":"asyncCheckDeviceStatusWithCompletion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asyncCheckDeviceStatusWithCompletion:"}]},{"value":"trackDownloadCompletedWithTrackId:data:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadCompletedWithTrackId:data:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1logAutomixSDKMessage(logLevel:message:)\/title","value":"logAutomixSDKMessageWithLogLevel:message:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1logAutomixSDKMessage(logLevel:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","value":"syncGetTrackMetadataWithTrackId:"},{"value":[{"kind":"text","text":"- "},{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments"},{"op":"replace","value":"isLoggedIn","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1isLoggedIn()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1isLoggedIn()\/fragments","value":[{"kind":"text","text":"- "},{"text":"isLoggedIn","kind":"identifier"}],"op":"replace"},{"value":"cacheMetadata:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1cacheMetadata(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheMetadata:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1cacheMetadata(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","op":"replace","value":"AutomixSDKStreamingDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/navigatorTitle","op":"replace"},{"value":"asyncGetTrackMetadataWithTrackId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetTrackMetadataWithTrackId:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1getDeviceIdentifier()\/title","value":"getDeviceIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1getDeviceIdentifier()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}