{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/allowpublicbroadcasts"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/allowpublicbroadcasts"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowPublicBroadcasts","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"allowPublicBroadcasts","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig(py)allowPublicBroadcasts","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"allowPublicBroadcasts"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/allowPublicBroadcasts","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig/allowPublicBroadcasts":{"url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/allowpublicbroadcasts","navigatorTitle":[{"text":"allowPublicBroadcasts","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/allowPublicBroadcasts","abstract":[],"role":"symbol","title":"allowPublicBroadcasts","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"allowPublicBroadcasts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"allowPublicBroadcasts","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1allowPublicBroadcasts\/title","op":"replace","value":"allowPublicBroadcasts"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1allowPublicBroadcasts\/fragments","op":"replace","value":[{"text":"allowPublicBroadcasts","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title","value":"RadioSDKFeatureSetConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]}]}]}