{"seeAlsoSections":[{"generated":true,"title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdk\/initialise(streamingdelegate:statusdelegate:countrycode:storeid:applicationid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdk\/initialise(streamingdelegate:statusdelegate:countrycode:storeid:applicationid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initialiser for Automix SDK to work against any custom set of APIs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed all data and metadata the Automix SDK needs."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"streamingDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of feeding all data and metadata the Automix SDK needs. See AutomixSDKStreamingDelegate."}]}],"name":"streamingDelegate"},{"name":"statusDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate.","type":"text"}]}]},{"name":"countryCode","content":[{"inlineContent":[{"text":"The ISO2 country code the device runs from.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Tuned Global’s store id."}],"type":"paragraph"}],"name":"storeId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Application id."}]}],"name":"applicationId"},{"name":"completion","content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"streamingDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","kind":"identifier"}],"title":"initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(cm)initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)":{"type":"topic","title":"initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cachedMusicProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKCachedMusicProvider","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initialiseWithTunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Initialiser for Automix SDK to work against a Tuned Global’s Store and Tuned Global’s APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)","kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/initialise(tuneddelegate:statusdelegate:countrycode:storeid:applicationid:cachedmusicprovider:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","kind":"symbol","title":"AutomixSDKStreamingDelegate","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","type":"topic","role":"symbol","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the information it requires to play content.","type":"text"},{"type":"text","text":" "},{"text":"See TunedDemoStreamingHandler for an example of an object implementing this protocol.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Provide seamless transitions between tracks and beat-matched seek experience within your music player application in iOS, iPad."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the Automix SDK and exposes all its functionality. It follows a Singleton pattern."}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk","title":"AutomixSDK","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)":{"type":"topic","title":"initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": "},{"text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Initialiser for Automix SDK to work against any custom set of APIs."},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed all data and metadata the Automix SDK needs.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)","kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/initialise(streamingdelegate:statusdelegate:countrycode:storeid:applicationid:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","role":"symbol","kind":"symbol","type":"topic","title":"AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented by a class tasked with observing the status of Automix SDK to reflect it on a UI."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)"],"generated":true}]},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initialiseWithStreamingDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","text":"id<AutomixSDKStreamingDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"streamingDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"statusDelegate"},{"text":" ","kind":"text"},{"kind":"identifier","text":"countryCode:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"countryCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"storeId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"storeId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"applicationId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"applicationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)\/title","op":"replace","value":"initialiseWithTunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(tunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithTunedDelegate:statusDelegate:countryCode:storeId:applicationId:cachedMusicProvider:completion:"}]},{"value":"AutomixSDKStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","op":"replace"},{"value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","value":"AutomixSDK","op":"replace"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)\/title","op":"replace","value":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"op":"replace","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}