{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCachedMusicProvider"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cachedMusicProvider"},{"kind":"text","text":": "},{"text":"AutomixSDKCachedMusicProvider","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"musicCacheDelegate","content":[{"inlineContent":[{"text":"The delegate to add.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setCachedMusicProvider(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdk\/setcachedmusicprovider(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/setcachedmusicprovider(_:)"]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCachedMusicProvider"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider","text":"AutomixSDKCachedMusicProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"AutomixIQ"}],"title":"setCachedMusicProvider(_:)","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)setCachedMusicProvider:","navigatorTitle":[{"kind":"identifier","text":"setCachedMusicProvider:"}]},"abstract":[{"text":"Add a new music cache delegate","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider":{"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"role":"symbol","type":"topic","title":"AutomixSDKCachedMusicProvider","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented by a class tasked with storing cached track data"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","url":"\/documentation\/automixiq","role":"collection","title":"AutomixIQ","abstract":[{"type":"text","text":"Provide seamless transitions between tracks and beat-matched seek experience within your music player application in iOS, iPad."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setCachedMusicProvider(_:)":{"type":"topic","title":"setCachedMusicProvider(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setCachedMusicProvider","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AutomixSDKCachedMusicProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setCachedMusicProvider:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Add a new music cache delegate","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setCachedMusicProvider(_:)","kind":"symbol","url":"\/documentation\/automixiq\/automixsdk\/setcachedmusicprovider(_:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the Automix SDK and exposes all its functionality. It follows a Singleton pattern."}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk","title":"AutomixSDK","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"setCachedMusicProvider:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"setCachedMusicProvider:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setCachedMusicProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<AutomixSDKCachedMusicProvider>","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cachedMusicProvider"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/title","value":"AutomixSDKCachedMusicProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/fragments","value":[{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setCachedMusicProvider(_:)\/title","op":"replace","value":"setCachedMusicProvider:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setCachedMusicProvider:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setCachedMusicProvider(_:)\/fragments"},{"value":"AutomixSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"}]}]}