{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/offlinenotuneduseridavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/offlinenotuneduseridavailable"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","role":"symbol","type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","url":"\/documentation\/automixiq\/automixsdkerrorcode\/offlinenotuneduseridavailable","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"abstract":[],"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","url":"\/documentation\/automixiq","title":"AutomixIQ","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title","op":"replace","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}