{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate\/didCloseRadioUI(userInitiated:)"},"abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI is closed"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pacemakerradio\/radiouidelegate\/didcloseradioui(userinitiated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiouidelegate\/didcloseradioui(userinitiated:)"]}],"metadata":{"symbolKind":"method","title":"didCloseRadioUI(userInitiated:)","roleHeading":"Instance Method","externalID":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate(im)didCloseRadioUIWithUserInitiated:","navigatorTitle":[{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCloseRadioUI"},{"text":"(","kind":"text"},{"text":"userInitiated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"required":true,"role":"symbol","modules":[{"name":"PacemakerRadio"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate/didCloseRadioUI(userInitiated:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate\/didCloseRadioUI(userInitiated:)","url":"\/documentation\/pacemakerradio\/radiouidelegate\/didcloseradioui(userinitiated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didCloseRadioUI","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInitiated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}],"abstract":[{"text":"Called by AutomixSDK when the Radio UI is closed","type":"text"}],"role":"symbol","kind":"symbol","title":"didCloseRadioUI(userInitiated:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioUIDelegate","kind":"identifier"}],"title":"RadioUIDelegate","navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"didCloseRadioUIWithUserInitiated:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"didCloseRadioUIWithUserInitiated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"userInitiated","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate~1didCloseRadioUI(userInitiated:)\/title","value":"didCloseRadioUIWithUserInitiated:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didCloseRadioUIWithUserInitiated:"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate~1didCloseRadioUI(userInitiated:)\/fragments"},{"value":"RadioUIDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title"},{"value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"RadioUIDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}