{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"PacemakerRadio"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearCache","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"clearCacheWithCompletion:","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDK(im)clearCacheWithCompletion:","title":"clearCache(completion:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCache"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]}],"abstract":[{"text":"Clears AutomixIQ backing files and recreates them empty","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/clearCache(completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdk\/clearcache(completion:)"]},{"paths":["\/documentation\/pacemakerradio\/radiosdk\/clearcache(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/clearCache(completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearCacheWithCompletion:"}],"title":"clearCache(completion:)","kind":"symbol","abstract":[{"type":"text","text":"Clears AutomixIQ backing files and recreates them empty"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/clearCache(completion:)","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdk\/clearcache(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearCache","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK":{"abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"url":"\/documentation\/pacemakerradio\/radiosdk","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}],"title":"RadioSDK","navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"clearCacheWithCompletion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCacheWithCompletion:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"clearCacheWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}],"type":"paragraph"}],"name":"completion"}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1clearCache(completion:)\/title","value":"clearCacheWithCompletion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"clearCacheWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1clearCache(completion:)\/fragments"},{"value":"RadioSDK","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/title","op":"replace"},{"value":[{"text":"RadioSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/navigatorTitle","op":"replace","value":[{"text":"RadioSDK","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}