{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/featureSetConfig","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"featureSetConfig","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"title":"featureSetConfig","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)featureSetConfig","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"featureSetConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier"}]},"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/featuresetconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/featuresetconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"featureSetConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"kind":"symbol","title":"RadioSDKConfig","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","type":"topic","navigatorTitle":[{"text":"RadioSDKConfig","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/radiosdkconfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"title":"RadioSDKFeatureSetConfig","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/featureSetConfig":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"featureSetConfig"}],"abstract":[],"title":"featureSetConfig","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/featureSetConfig","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"featureSetConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier","text":"RadioSDKFeatureSetConfig"}],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/featuresetconfig","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"role":"collection","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"type":"topic","url":"\/documentation\/pacemakerradio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"featureSetConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"featureSetConfig"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","text":"RadioSDKFeatureSetConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"featureSetConfig","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"text":"RadioSDKConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"op":"replace","value":"RadioSDKFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments","op":"replace","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},{"value":"featureSetConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1featureSetConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1featureSetConfig\/fragments","value":[{"kind":"identifier","text":"featureSetConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}