{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSkipToNext"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToNext"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSkipToNext","kind":"identifier"}],"title":"AutomixSDKStatusVariable.canSkipToNext","modules":[{"name":"PacemakerRadio"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanSkipToNext"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/canSkipToNext","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptonext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptonext"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/canSkipToNext":{"title":"AutomixSDKStatusVariable.canSkipToNext","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSkipToNext"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanSkipToNext","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/canSkipToNext","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/canskiptonext"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"role":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixSDKStatusVariableCanSkipToNext","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableCanSkipToNext","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanSkipToNext"}]}]}},{"value":"AutomixSDKStatusVariableCanSkipToNext","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1canSkipToNext\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1canSkipToNext\/fragments","value":[{"text":"AutomixSDKStatusVariableCanSkipToNext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}