{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}],"role":"symbol","modules":[{"name":"PacemakerRadio"}],"title":"AutomixSDKStatusVariable.failedTrackLoadIdentifiers","symbolKind":"case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableFailedTrackLoadIdentifiers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedTrackLoadIdentifiers"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/failedtrackloadidentifiers"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/failedtrackloadidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"role":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/failedTrackLoadIdentifiers":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/failedTrackLoadIdentifiers","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/failedtrackloadidentifiers","role":"symbol","title":"AutomixSDKStatusVariable.failedTrackLoadIdentifiers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedTrackLoadIdentifiers","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/title","value":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariableFailedTrackLoadIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1failedTrackLoadIdentifiers\/fragments"}]}]}