{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations"],"generated":true}],"seeAlsoSections":[{"generated":true,"anchor":"Persistency","title":"Persistency","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Start of track playback"}],"type":"paragraph"}],"name":"trackPlayStart"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has played for 5 seconds"}]}],"name":"trackPlayPlayed5Secs"},{"name":"trackPlayHeartbeat30Secs","content":[{"type":"paragraph","inlineContent":[{"text":"Track has played for 30 seconds, this is called every 30 seconds of playback","type":"text"}]}]},{"name":"trackPlayStartMixingIntoNext","content":[{"type":"paragraph","inlineContent":[{"text":"Track has started transitioning into the next track","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Track has been skipped to the next track (this is also called when seeking through the same track)"}]}],"name":"trackPlaySkipped"},{"name":"trackPlayFinished","content":[{"inlineContent":[{"type":"text","text":"Track has finished playback (if transitioning this is called at the end of the transition for the first track)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Queue has reached the end and there are no more tracks to play","type":"text"}]}],"name":"mixPlaybackEnded"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH","doc:\/\/org.cocoapods.PacemakerRadio\/SY"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType","title":"AutomixSDKPlaybackEventType","modules":[{"name":"PacemakerRadio"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/init(rawvalue:)","role":"symbol","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/Equatable-Implementations":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/equatable-implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/Equatable-Implementations"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLog":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKTransitionLog","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLog"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktransitionlog","title":"AutomixSDKTransitionLog","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogID":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktransitionlogid","title":"AutomixSDKTransitionLogID","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayFinished":{"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayfinished","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}],"title":"AutomixSDKPlaybackEventType.trackPlayFinished","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlayFinished","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogID":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylogid","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","role":"symbol","title":"AutomixSDKPlayLogID","navigatorTitle":[{"text":"AutomixSDKPlayLogID","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayPlayed5Secs":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","title":"AutomixSDKPlaybackEventType.trackPlayPlayed5Secs","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayplayed5secs"},"doc://org.cocoapods.PacemakerRadio/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH"},"doc://org.cocoapods.PacemakerRadio/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SY"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Persistency-article":{"role":"article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"type":"topic","url":"\/documentation\/pacemakerradio\/persistency-article","title":"Persistency","kind":"article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLog":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlayLog","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylog","abstract":[],"navigatorTitle":[{"text":"AutomixSDKPlayLog","kind":"identifier"}],"title":"AutomixSDKPlayLog","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayStart":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","title":"AutomixSDKPlaybackEventType.trackPlayStart","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStart"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplaystart","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStart"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogAttributes":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","title":"AutomixSDKTransitionLogAttributes","abstract":[],"navigatorTitle":[{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdktransitionlogattributes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogAttributes":{"url":"\/documentation\/pacemakerradio\/automixsdkplaylogattributes","type":"topic","title":"AutomixSDKPlayLogAttributes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","role":"symbol","title":"AutomixSDKPlaybackEventType","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayHeartbeat30Secs":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayHeartbeat30Secs"}],"title":"AutomixSDKPlaybackEventType.trackPlayHeartbeat30Secs","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayheartbeat30secs","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayStartMixingIntoNext":{"title":"AutomixSDKPlaybackEventType.trackPlayStartMixingIntoNext","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplaystartmixingintonext","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStartMixingIntoNext"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlaySkipped":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlaySkipped"}],"title":"AutomixSDKPlaybackEventType.trackPlaySkipped","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayskipped","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/mixplaybackended","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlaybackEnded"}],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"],"title":"Enumeration Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":[{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article"],"generated":true,"anchor":"Persistency"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/fragments"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/title"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/fragments"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayStart","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStart\/title"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStart\/fragments"},{"value":"AutomixSDKPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title"},{"value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"},{"op":"replace","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/title","value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"},{"value":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments"}]}]}