{"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/unimplemented"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/Equatable-Implementations","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH","doc:\/\/org.cocoapods.PacemakerRadio\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to use the SDK from any thread not main","type":"text"}]}],"name":"notMainThread"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to use the SDK prior to initialising it","type":"text"}]}],"name":"sdkNotInitialised"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to use playback controls when AutomixIQ is not on"}]}],"name":"sdkNotOn"},{"name":"sdkAlreadyOn","content":[{"inlineContent":[{"text":"Thrown when you attempt to turn on AutomixIQ but it is already on","type":"text"}],"type":"paragraph"}]},{"name":"loadTracksEmptyPlaylist","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to load an empty playlist"}],"type":"paragraph"}]},{"name":"loadTracksOutOfBounds","content":[{"inlineContent":[{"text":"","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""}]}],"name":"addTrackPlaylistDoesNotExist"},{"name":"addTrackOutOfBounds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to insert a track at a position outside the bounds of the loaded playlist"}]}]},{"name":"addTrackNoMetadata","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when the metadata for a track you are trying to load is not available and could not be downloaded","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when AutomixIQ fails internally (not user error)","type":"text"}],"type":"paragraph"}],"name":"addTrackInternalError"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to remove a track at a position outside the bounds of the loaded playlist"}],"type":"paragraph"}],"name":"removeTrackOutOfBounds"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to play but AutomixIQ is already playing","type":"text"}]}],"name":"playAlreadyPlaying"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to pause but AutomixIQ is already paused"}]}],"name":"pauseAlreadyPaused"},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the previous track but AutomixIQ is already on the first in the playlist and “Repeat” is off"}],"type":"paragraph"}],"name":"previousNoTrackAvailable"},{"name":"nextNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to go to the next track but AutomixIQ is already on the last in the playlist and “Repeat” is off"}],"type":"paragraph"}]},{"name":"backNoTrackAvailable","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to go to the start of a track but the playlist is empty","type":"text"}]}]},{"name":"seekNoTrackAvailable","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to seek to a track but the playlist is empty or the index is out of bounds of the playlist"}],"type":"paragraph"}]},{"name":"seekNoCurrentTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to seek within a track but the playlist is empty or the track is not yet loaded","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to move a track that is not on the loaded playlist"}]}],"name":"reorderMissingTrack"},{"name":"playToEndMissingTrack","content":[{"inlineContent":[{"text":"Thrown when you attempt to select a track to be played until the end but that track is not on the loaded playlist","type":"text"}],"type":"paragraph"}]},{"name":"moveTrackOutOfBounds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to move a track at a position outside the bounds of the loaded playlist"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to stop looping a track but that track is not on the loaded playlist"}]}],"name":"startLoopingNoLoopingTrack"},{"name":"stopLoopingNoLoopingTrack","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to loop a track but that track is not on the loaded playlist"}],"type":"paragraph"}]},{"name":"unimplemented","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to use an unimplemented method of the SDK"}],"type":"paragraph"}]},{"name":"cancelled","content":[{"inlineContent":[{"text":"Thrown when an action you previously issued to AutomixIQ is cancelled due to another user initialed action that overrides it","type":"text"}],"type":"paragraph"}]},{"name":"onAlreadyTurningOn","content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning on"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ on while it is already turning off"}],"type":"paragraph"}],"name":"onWhileTurningOff"},{"content":[{"inlineContent":[{"text":"Thrown when you attempt to turn AutomixIQ off while it is already turning off","type":"text"}],"type":"paragraph"}],"name":"offAlreadyTurningOff"},{"name":"offWhileTurningOn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when you attempt to turn AutomixIQ off while it is already turning on"}]}]},{"content":[{"inlineContent":[{"text":"Thrown when AutomixIQ fails to set up the channel layout","type":"text"}],"type":"paragraph"}],"name":"cannotCreateChannelLayout"},{"name":"cannotCreateInputBuffer","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails to set up the input buffer","type":"text"}]}]},{"name":"cannotSetupAVAudioSession","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to set up the AVAudioSession"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Thrown when AutomixIQ fails to start the audio engine"}]}],"name":"cannotStartAudioEngine"},{"name":"cannotRestoreAudioSession","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when AutomixIQ fails to restore the audio session to the state it found it when you turned it on","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Thrown when AutomixIQ is unable to be stopped"}],"type":"paragraph"}],"name":"failedToStop"},{"name":"cannotLoadExplicitLyricsTrack","content":[{"type":"paragraph","inlineContent":[{"text":"Thrown when you attempt to load an explicit track but the setting to filter out explicit tracks is on","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"metadata":{"roleHeading":"Enumeration","modules":[{"name":"PacemakerRadio"}],"symbolKind":"enum","title":"AutomixSDKErrorCode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode"},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Errors-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/sdkError(code:)"],"title":"Errors","anchor":"Errors","generated":true}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkInitialisationUnauthorised":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised"}],"abstract":[],"title":"AutomixSDKErrorCode.sdkInitialisationUnauthorised","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkInitialisationUnauthorised"}],"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdkinitialisationunauthorised","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/unimplemented":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/unimplemented","title":"AutomixSDKErrorCode.unimplemented","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/unimplemented","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeUnimplemented","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unimplemented"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/init(rawValue:)":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/init(rawvalue:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/reorderMissingTrack":{"navigatorTitle":[{"text":"AutomixSDKErrorCodeReorderMissingTrack","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/reorderMissingTrack","title":"AutomixSDKErrorCode.reorderMissingTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderMissingTrack"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/reordermissingtrack"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/onWhileTurningOff":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.onWhileTurningOff","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onWhileTurningOff","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/onwhileturningoff","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onWhileTurningOff","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnWhileTurningOff"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"abstract":[],"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/offlinenotuneduseridavailable","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkAlreadyOn":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyOn"}],"title":"AutomixSDKErrorCode.sdkAlreadyOn","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdkalreadyon","type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/pauseAlreadyPaused":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"pauseAlreadyPaused","kind":"identifier"}],"title":"AutomixSDKErrorCode.pauseAlreadyPaused","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/pausealreadypaused","type":"topic","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodePauseAlreadyPaused","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/failedToStop":{"abstract":[],"title":"AutomixSDKErrorCode.failedToStop","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/failedtostop","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedToStop","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/failedToStop","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeFailedToStop"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/loadTracksEmptyPlaylist":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/loadtracksemptyplaylist","type":"topic","title":"AutomixSDKErrorCode.loadTracksEmptyPlaylist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTracksEmptyPlaylist","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/onAlreadyTurningOn":{"title":"AutomixSDKErrorCode.onAlreadyTurningOn","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOnAlreadyTurningOn"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/onalreadyturningon","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAlreadyTurningOn"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkAlreadyInitialised":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdkalreadyinitialised","navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}],"title":"AutomixSDKErrorCode.sdkAlreadyInitialised","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkAlreadyInitialised"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/loadTracksOutOfBounds":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/loadtracksoutofbounds","title":"AutomixSDKErrorCode.loadTracksOutOfBounds","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadTracksOutOfBounds"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksOutOfBounds"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/moveTrackOutOfBounds":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/movetrackoutofbounds","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeMoveTrackOutOfBounds","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","role":"symbol","type":"topic","title":"AutomixSDKErrorCode.moveTrackOutOfBounds","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"moveTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/offWhileTurningOn":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offWhileTurningOn","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offWhileTurningOn"}],"title":"AutomixSDKErrorCode.offWhileTurningOn","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/offwhileturningon","kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffWhileTurningOn"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotCreateInputBuffer":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotCreateInputBuffer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotcreateinputbuffer","type":"topic","kind":"symbol","title":"AutomixSDKErrorCode.cannotCreateInputBuffer","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/startLoopingNoLoopingTrack":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"startLoopingNoLoopingTrack","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","type":"topic","title":"AutomixSDKErrorCode.startLoopingNoLoopingTrack","abstract":[],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/startloopingnoloopingtrack","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkNotOn":{"title":"AutomixSDKErrorCode.sdkNotOn","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotOn","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkNotOn","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotOn"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdknoton","abstract":[],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/playAlreadyPlaying":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.playAlreadyPlaying","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/playalreadyplaying","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playAlreadyPlaying"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayAlreadyPlaying"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/noInternetAvailable":{"title":"AutomixSDKErrorCode.noInternetAvailable","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/nointernetavailable","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeNoInternetAvailable"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"kind":"symbol","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode"},"doc://org.cocoapods.PacemakerRadio/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/backNoTrackAvailable":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.backNoTrackAvailable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/backnotrackavailable","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"backNoTrackAvailable","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/addTrackInternalError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackInternalError"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/addtrackinternalerror","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackInternalError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackInternalError","role":"symbol","title":"AutomixSDKErrorCode.addTrackInternalError"},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cancelled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelled","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCancelled"}],"type":"topic","kind":"symbol","abstract":[],"title":"AutomixSDKErrorCode.cancelled","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cancelled","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cancelled"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotSetupAVAudioSession":{"title":"AutomixSDKErrorCode.cannotSetupAVAudioSession","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotsetupavaudiosession","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotSetupAVAudioSession","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/addTrackPlaylistDoesNotExist":{"abstract":[],"title":"AutomixSDKErrorCode.addTrackPlaylistDoesNotExist","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/addtrackplaylistdoesnotexist","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"addTrackPlaylistDoesNotExist","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/addTrackNoMetadata":{"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/addtracknometadata","title":"AutomixSDKErrorCode.addTrackNoMetadata","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackNoMetadata"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackNoMetadata"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","abstract":[],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotLoadExplicitLyricsTrack":{"type":"topic","title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotloadexplicitlyricstrack","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/nextNoTrackAvailable":{"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/nextnotrackavailable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","kind":"symbol","title":"AutomixSDKErrorCode.nextNoTrackAvailable","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextNoTrackAvailable"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeNextNoTrackAvailable","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/addTrackOutOfBounds":{"abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/addtrackoutofbounds","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addTrackOutOfBounds","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","kind":"symbol","type":"topic","role":"symbol","title":"AutomixSDKErrorCode.addTrackOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Errors-article":{"type":"topic","abstract":[{"text":"What errors the PacemakerRadio player can issue to help with player integration","type":"text"}],"role":"article","kind":"article","title":"Errors","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Errors-article","url":"\/documentation\/pacemakerradio\/errors-article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/Equatable-Implementations","kind":"article","type":"topic","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/seekNoTrackAvailable":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"seekNoTrackAvailable"}],"kind":"symbol","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/seeknotrackavailable","title":"AutomixSDKErrorCode.seekNoTrackAvailable","type":"topic","navigatorTitle":[{"text":"AutomixSDKErrorCodeSeekNoTrackAvailable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/notMainThread":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/notMainThread","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/notmainthread","title":"AutomixSDKErrorCode.notMainThread","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notMainThread","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeNotMainThread","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotRestoreAudioSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotRestoreAudioSession"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","type":"topic","title":"AutomixSDKErrorCode.cannotRestoreAudioSession","abstract":[],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotrestoreaudiosession","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/previousNoTrackAvailable":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodePreviousNoTrackAvailable"}],"kind":"symbol","title":"AutomixSDKErrorCode.previousNoTrackAvailable","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/previousnotrackavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"previousNoTrackAvailable","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkNotInitialisedVersionNoLongerSupported":{"title":"AutomixSDKErrorCode.sdkNotInitialisedVersionNoLongerSupported","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdknotinitialisedversionnolongersupported","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/playToEndMissingTrack":{"navigatorTitle":[{"text":"AutomixSDKErrorCodePlayToEndMissingTrack","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playToEndMissingTrack","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/playtoendmissingtrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","title":"AutomixSDKErrorCode.playToEndMissingTrack","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/playToEndMixEnd":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playToEndMixEnd"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMixEnd","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMixEnd"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/playtoendmixend","abstract":[],"kind":"symbol","type":"topic","title":"AutomixSDKErrorCode.playToEndMixEnd"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/offAlreadyTurningOff":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOffAlreadyTurningOff"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offAlreadyTurningOff","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/offalreadyturningoff","abstract":[],"title":"AutomixSDKErrorCode.offAlreadyTurningOff","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/removeTrackOutOfBounds":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"title":"AutomixSDKErrorCode.removeTrackOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/removetrackoutofbounds","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/seekNoCurrentTrack":{"type":"topic","abstract":[],"title":"AutomixSDKErrorCode.seekNoCurrentTrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/seeknocurrenttrack","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekNoCurrentTrack"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoCurrentTrack"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotCreateChannelLayout":{"title":"AutomixSDKErrorCode.cannotCreateChannelLayout","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotcreatechannellayout","abstract":[],"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}]},"doc://org.cocoapods.PacemakerRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/sdkError(code:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/sdkError(code:)","abstract":[],"url":"\/documentation\/pacemakerradio\/sdkerror(code:)","title":"sdkError(code:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sdkError","kind":"identifier"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode"},{"kind":"text","text":") -> "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/noInternetAvailableTooLongOffline":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/nointernetavailabletoolongoffline","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}],"title":"AutomixSDKErrorCode.noInternetAvailableTooLongOffline","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noInternetAvailableTooLongOffline","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/sdkNotInitialised":{"title":"AutomixSDKErrorCode.sdkNotInitialised","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/sdknotinitialised","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialised","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotInitialised"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotInitialised","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotStartAudioEngine":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","title":"AutomixSDKErrorCode.cannotStartAudioEngine","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cannotStartAudioEngine","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotStartAudioEngine"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotstartaudioengine"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/stopLoopingNoLoopingTrack":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopLoopingNoLoopingTrack"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/stoploopingnoloopingtrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack"}],"title":"AutomixSDKErrorCode.stopLoopingNoLoopingTrack","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCode"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackInternalError","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackNoMetadata","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/addTrackPlaylistDoesNotExist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cancelled","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateInputBuffer","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotSetupAVAudioSession","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotStartAudioEngine","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/failedToStop","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksEmptyPlaylist","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/loadTracksOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/moveTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/nextNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/noInternetAvailableTooLongOffline","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/notMainThread","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offAlreadyTurningOff","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offWhileTurningOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onAlreadyTurningOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/onWhileTurningOff","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/pauseAlreadyPaused","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playAlreadyPlaying","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMissingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/playToEndMixEnd","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/previousNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/removeTrackOutOfBounds","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/reorderMissingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyInitialised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkAlreadyOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkInitialisationUnauthorised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialised","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotInitialisedVersionNoLongerSupported","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/sdkNotOn","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoCurrentTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/seekNoTrackAvailable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/startLoopingNoLoopingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/stopLoopingNoLoopingTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/unimplemented"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":[{"generated":true,"title":"Errors","anchor":"Errors","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Errors-article"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/title","value":"AutomixSDKErrorCodeSdkInitialisationUnauthorised","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkInitialisationUnauthorised\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkInitialisationUnauthorised"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1unimplemented\/title","value":"AutomixSDKErrorCodeUnimplemented"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeUnimplemented","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1unimplemented\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1reorderMissingTrack\/title","value":"AutomixSDKErrorCodeReorderMissingTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1reorderMissingTrack\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeReorderMissingTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1onWhileTurningOff\/title","op":"replace","value":"AutomixSDKErrorCodeOnWhileTurningOff"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1onWhileTurningOff\/fragments","value":[{"text":"AutomixSDKErrorCodeOnWhileTurningOff","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkAlreadyOn\/title","op":"replace","value":"AutomixSDKErrorCodeSdkAlreadyOn"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkAlreadyOn\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodePauseAlreadyPaused","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePauseAlreadyPaused"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1pauseAlreadyPaused\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1failedToStop\/title","value":"AutomixSDKErrorCodeFailedToStop","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeFailedToStop","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1failedToStop\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/title","value":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1loadTracksEmptyPlaylist\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeLoadTracksEmptyPlaylist"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/title","value":"AutomixSDKErrorCodeOnAlreadyTurningOn"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1onAlreadyTurningOn\/fragments","value":[{"text":"AutomixSDKErrorCodeOnAlreadyTurningOn","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSdkAlreadyInitialised","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkAlreadyInitialised\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyInitialised","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/title","value":"AutomixSDKErrorCodeLoadTracksOutOfBounds"},{"value":[{"text":"AutomixSDKErrorCodeLoadTracksOutOfBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1loadTracksOutOfBounds\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/title","op":"replace","value":"AutomixSDKErrorCodeMoveTrackOutOfBounds"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeMoveTrackOutOfBounds"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1moveTrackOutOfBounds\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offWhileTurningOn\/title","value":"AutomixSDKErrorCodeOffWhileTurningOn"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offWhileTurningOn\/fragments","value":[{"text":"AutomixSDKErrorCodeOffWhileTurningOn","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeCannotCreateInputBuffer","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/title","op":"replace","value":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1startLoopingNoLoopingTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeStartLoopingNoLoopingTrack","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodeSdkNotOn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotOn\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotOn\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotOn"}]},{"op":"replace","value":"AutomixSDKErrorCodePlayAlreadyPlaying","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playAlreadyPlaying\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayAlreadyPlaying"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1noInternetAvailable\/title","value":"AutomixSDKErrorCodeNoInternetAvailable","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeNoInternetAvailable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1noInternetAvailable\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","op":"replace","value":"AutomixSDKErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","op":"replace"},{"value":"AutomixSDKErrorCodeBackNoTrackAvailable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}],"op":"replace"},{"value":"AutomixSDKErrorCodeAddTrackInternalError","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackInternalError\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackInternalError\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeAddTrackInternalError","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeCancelled","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cancelled\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cancelled\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeCancelled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/title","value":"AutomixSDKErrorCodeCannotSetupAVAudioSession"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotSetupAVAudioSession\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotSetupAVAudioSession"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/title","value":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackPlaylistDoesNotExist\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackPlaylistDoesNotExist"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackNoMetadata\/title","op":"replace","value":"AutomixSDKErrorCodeAddTrackNoMetadata"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackNoMetadata\/fragments","value":[{"text":"AutomixSDKErrorCodeAddTrackNoMetadata","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/title","value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1nextNoTrackAvailable\/title","value":"AutomixSDKErrorCodeNextNoTrackAvailable","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeNextNoTrackAvailable"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1nextNoTrackAvailable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackOutOfBounds\/title","value":"AutomixSDKErrorCodeAddTrackOutOfBounds"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackOutOfBounds"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1addTrackOutOfBounds\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1seekNoTrackAvailable\/title","op":"replace","value":"AutomixSDKErrorCodeSeekNoTrackAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1seekNoTrackAvailable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoTrackAvailable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1notMainThread\/title","op":"replace","value":"AutomixSDKErrorCodeNotMainThread"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1notMainThread\/fragments","value":[{"text":"AutomixSDKErrorCodeNotMainThread","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeCannotRestoreAudioSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1previousNoTrackAvailable\/title","value":"AutomixSDKErrorCodePreviousNoTrackAvailable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1previousNoTrackAvailable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodePreviousNoTrackAvailable"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/title","value":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","op":"replace"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeSdkNotInitialisedVersionNoLongerSupported","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotInitialisedVersionNoLongerSupported\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/title","value":"AutomixSDKErrorCodePlayToEndMissingTrack"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodePlayToEndMissingTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playToEndMissingTrack\/fragments"},{"op":"replace","value":"AutomixSDKErrorCodePlayToEndMixEnd","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1playToEndMixEnd\/fragments","value":[{"text":"AutomixSDKErrorCodePlayToEndMixEnd","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/title","op":"replace","value":"AutomixSDKErrorCodeOffAlreadyTurningOff"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offAlreadyTurningOff\/fragments","value":[{"text":"AutomixSDKErrorCodeOffAlreadyTurningOff","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/title","op":"replace","value":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/fragments","value":[{"text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSeekNoCurrentTrack","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1seekNoCurrentTrack\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1seekNoCurrentTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/title","value":"AutomixSDKErrorCodeCannotCreateChannelLayout"},{"value":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/title","value":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1noInternetAvailableTooLongOffline\/fragments","value":[{"text":"AutomixSDKErrorCodeNoInternetAvailableTooLongOffline","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeSdkNotInitialised","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkNotInitialised"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1sdkNotInitialised\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotStartAudioEngine\/title","op":"replace","value":"AutomixSDKErrorCodeCannotStartAudioEngine"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotStartAudioEngine\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotStartAudioEngine"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/title","op":"replace","value":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1stopLoopingNoLoopingTrack\/fragments","value":[{"text":"AutomixSDKErrorCodeStopLoopingNoLoopingTrack","kind":"identifier"}]}]}]}