{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/bpm"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpm"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Objective-C accessible member for the bpm, 09 if unavailable","type":"text"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdktrackmodel\/bpm"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdktrackmodel\/bpm"]}],"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel(py)bpm","symbolKind":"property","roleHeading":"Instance Property","title":"bpm","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bpm","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"bpm"}],"role":"symbol","modules":[{"name":"AutomixIQ"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/bpm":{"type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the bpm, 09 if unavailable"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/bpm","navigatorTitle":[{"kind":"identifier","text":"bpm"}],"url":"\/documentation\/automixiq\/automixsdktrackmodel\/bpm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bpm","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"bpm","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"role":"symbol","title":"AutomixSDKTrackModel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"bpm","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"bpm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"text":"bpm","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1bpm\/title","op":"replace","value":"bpm"},{"op":"replace","value":[{"kind":"identifier","text":"bpm"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1bpm\/fragments"},{"value":"AutomixSDKTrackModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}