{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backNoTrackAvailable"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backNoTrackAvailable"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeBackNoTrackAvailable","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeBackNoTrackAvailable"}],"symbolKind":"case","roleHeading":"Case","title":"AutomixSDKErrorCode.backNoTrackAvailable","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/backnotrackavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/backNoTrackAvailable":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/backNoTrackAvailable","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backNoTrackAvailable"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/backnotrackavailable","title":"AutomixSDKErrorCode.backNoTrackAvailable","navigatorTitle":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","kind":"symbol","title":"AutomixSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeBackNoTrackAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeBackNoTrackAvailable"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeBackNoTrackAvailable"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/title","op":"replace","value":"AutomixSDKErrorCodeBackNoTrackAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1backNoTrackAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeBackNoTrackAvailable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace"}]}]}