{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotOn","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AutomixIQ"}],"symbolKind":"case","role":"symbol","title":"AutomixSDKErrorCode.sdkNotOn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkNotOn"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeSdkNotOn","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotOn"},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdknoton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdknoton"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"title":"AutomixSDKErrorCode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","abstract":[{"text":"AutomixSDK error codes","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","kind":"symbol","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkNotOn":{"type":"topic","url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdknoton","abstract":[],"kind":"symbol","title":"AutomixSDKErrorCode.sdkNotOn","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkNotOn","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkNotOn"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic","url":"\/documentation\/automixiq","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixSDKErrorCodeSdkNotOn","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}]}],"kind":"declarations"}},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotOn\/title","value":"AutomixSDKErrorCodeSdkNotOn","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkNotOn\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkNotOn","kind":"identifier"}],"op":"replace"}]}]}