{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIdentifier"},"metadata":{"modules":[{"name":"AutomixIQ"}],"title":"AutomixSDKStatusVariable.playingTrackIdentifier","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackIdentifier"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playingTrackIdentifier","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePlayingTrackIdentifier"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackIdentifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playingTrackIdentifier":{"kind":"symbol","title":"AutomixSDKStatusVariable.playingTrackIdentifier","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playingTrackIdentifier","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playingtrackidentifier","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playingTrackIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"AutomixSDKStatusVariablePlayingTrackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","abstract":[{"text":"AutomixSDK play event type","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"role":"symbol","title":"AutomixSDKStatusVariable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKStatusVariablePlayingTrackIdentifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AutomixSDKStatusVariablePlayingTrackIdentifier","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"AutomixSDKStatusVariablePlayingTrackIdentifier","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIdentifier\/title","op":"replace","value":"AutomixSDKStatusVariablePlayingTrackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playingTrackIdentifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlayingTrackIdentifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace"}]}]}