{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"logLevel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKLogLevel","text":"AutomixSDKLogLevel","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate(im)logAutomixSDKMessageWithLogLevel:message:","navigatorTitle":[{"kind":"identifier","text":"logAutomixSDKMessageWithLogLevel:message:"}],"role":"symbol","title":"logAutomixSDKMessage(logLevel:message:)","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixSDKMessage(logLevel:message:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"]]},"abstract":[{"type":"text","text":"Called by AutomixIQ when it wishes to output a log message"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logAutomixSDKMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","text":"AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"logLevel","content":[{"type":"paragraph","inlineContent":[{"text":"The log level.","type":"text"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message it wishes to log."}]}]}]}],"variants":[{"paths":["\/documentation\/automixiq\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"url":"\/documentation\/automixiq\/tunedrestdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","url":"\/documentation\/automixiq\/automixsdkloglevel","title":"AutomixSDKLogLevel","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate/logAutomixSDKMessage(logLevel:message:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logAutomixSDKMessage"},{"kind":"text","text":"("},{"text":"logLevel","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKLogLevel"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"logAutomixSDKMessageWithLogLevel:message:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate\/logAutomixSDKMessage(logLevel:message:)","kind":"symbol","title":"logAutomixSDKMessage(logLevel:message:)","url":"\/documentation\/automixiq\/tunedrestdelegate\/logautomixsdkmessage(loglevel:message:)","abstract":[{"text":"Called by AutomixIQ when it wishes to output a log message","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"logAutomixSDKMessageWithLogLevel:message:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"logAutomixSDKMessageWithLogLevel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","text":"AutomixSDKLogLevel"},{"kind":"text","text":") "},{"text":"logLevel","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixSDKMessage(logLevel:message:)\/title","value":"logAutomixSDKMessageWithLogLevel:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate~1logAutomixSDKMessage(logLevel:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logAutomixSDKMessageWithLogLevel:message:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}