{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationTypeRemoved","kind":"identifier"}],"role":"symbol","modules":[{"name":"PacemakerRadio"}],"title":"AutomixSDKPlaylistOperationType.Removed","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaylistOperationType@AutomixSDKPlaylistOperationTypeRemoved","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Removed","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Removed"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/removed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/removed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/Removed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","type":"topic","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType/Removed":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationTypeRemoved","kind":"identifier"}],"abstract":[],"title":"AutomixSDKPlaylistOperationType.Removed","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/Removed","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/removed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Removed","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType":{"navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"title":"AutomixSDKPlaylistOperationType","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"AutomixSDKPlaylistOperationTypeRemoved","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixSDKPlaylistOperationTypeRemoved","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"AutomixSDKPlaylistOperationTypeRemoved","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDKPlaylistOperationTypeRemoved","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType~1Removed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType~1Removed\/fragments","value":[{"text":"AutomixSDKPlaylistOperationTypeRemoved","kind":"identifier"}]},{"value":"AutomixSDKPlaylistOperationType","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/title","op":"replace"},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]}]}]}