{"abstract":[{"text":"Adds a new music cache delegate","type":"text"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdk\/setmusiccachedelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdk\/setmusiccachedelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMusicCacheDelegate(_:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMusicCacheDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"musicCacheDelegate","content":[{"inlineContent":[{"text":"The delegate to add.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"metadata":{"title":"setMusicCacheDelegate(_:)","roleHeading":"Instance Method","modules":[{"name":"PacemakerRadio"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDK(im)setMusicCacheDelegate:","navigatorTitle":[{"text":"setMusicCacheDelegate:","kind":"identifier"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMusicCacheDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/setMusicCacheDelegate(_:)":{"type":"topic","navigatorTitle":[{"text":"setMusicCacheDelegate:","kind":"identifier"}],"title":"setMusicCacheDelegate(_:)","url":"\/documentation\/pacemakerradio\/automixsdk\/setmusiccachedelegate(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/setMusicCacheDelegate(_:)","abstract":[{"type":"text","text":"Adds a new music cache delegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"role":"symbol","title":"AutomixSDK","url":"\/documentation\/pacemakerradio\/automixsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDK"}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"title":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setMusicCacheDelegate:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMusicCacheDelegate:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setMusicCacheDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<TunedMusicCacheDelegate>","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"musicCacheDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate to add."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMusicCacheDelegate(_:)\/title","value":"setMusicCacheDelegate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setMusicCacheDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1setMusicCacheDelegate(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title","value":"AutomixSDK"},{"op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"value":"TunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]}]}]}