{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtape\/title"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtape\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"title","role":"symbol","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"text":"title","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtape(py)title","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape\/title"},"kind":"symbol","abstract":[{"type":"text","text":"The title of this mixtape"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape/title":{"role":"symbol","abstract":[{"type":"text","text":"The title of this mixtape"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkmixtape\/title","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape\/title","kind":"symbol","title":"title"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtape","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtape","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","type":"topic","title":"AutomixSDKMixtape","kind":"symbol","abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"title","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"title","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape~1title\/title"},{"value":[{"text":"title","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape~1title\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title","value":"AutomixSDKMixtape"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}