{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamingDelegate"},{"text":": any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]},{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","kind":"typeIdentifier","text":"AutomixSDKConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig"},{"text":", ","kind":"text"},{"text":"streamingDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkobjc\/initialise(with:streamingdelegate:statusdelegate:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"c:objc(cs)AutomixSDKObjC(cm)initialiseWithConfig:streamingDelegate:statusDelegate:completion:","symbolKind":"method","role":"symbol","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"modules":[{"name":"PacemakerRadio"}],"title":"initialise(with:streamingDelegate:statusDelegate:completion:)"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKObjC","kind":"identifier"}],"abstract":[],"title":"AutomixSDKObjC","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKConfig":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKConfig","kind":"identifier"}],"abstract":[],"title":"AutomixSDKConfig","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkconfig","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/CompletionWithError":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithError"}],"abstract":[],"title":"CompletionWithError","navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/completionwitherror","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/CompletionWithError"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"url":"\/documentation\/pacemakerradio\/automixsdkstreamingdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"kind":"symbol","title":"AutomixSDKStatusObserverDelegate","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/initialise(with:streamingDelegate:statusDelegate:completion:)":{"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/initialise(with:streamingdelegate:statusdelegate:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"AutomixSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig"},{"kind":"text","text":", "},{"text":"streamingDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","title":"initialise(with:streamingDelegate:statusDelegate:completion:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"AutomixSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/fragments","value":[{"text":"AutomixSDKConfig","kind":"identifier"}]},{"value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/navigatorTitle"},{"value":"AutomixSDKStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}