{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/images"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/images"]}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrack(py)images","roleHeading":"Instance Property","title":"images","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"text":"images","kind":"identifier"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"text":": [","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrackImage","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/images","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"images","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrackImage","text":"AutomixSDKMixtapeTrackImage","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The set of images available for this track"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","title":"AutomixSDKMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/images":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"images"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKMixtapeTrackImage","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrackImage"},{"text":"]?","kind":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/images","kind":"symbol","role":"symbol","abstract":[{"text":"The set of images available for this track","type":"text"}],"navigatorTitle":[{"text":"images","kind":"identifier"}],"title":"images","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/images"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"type":"topic","title":"AutomixSDKMixtapeTrackImage","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","navigatorTitle":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"images","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"images"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSArray<AutomixSDKMixtapeTrackImage *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"images","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1images\/title","value":"images","op":"replace"},{"value":[{"text":"images","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1images\/fragments"},{"value":"AutomixSDKMixtapeTrackImage","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title","op":"replace"},{"value":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}