{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayfinished"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayfinished"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}],"modules":[{"name":"PacemakerRadio"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"roleHeading":"Case","role":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayFinished","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlayFinished"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/trackPlayFinished":{"role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType.trackPlayFinished","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayFinished","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/trackplayfinished","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/trackPlayFinished","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"role":"collection","title":"PacemakerRadio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"type":"topic","url":"\/documentation\/pacemakerradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1trackPlayFinished\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayFinished"}]},{"op":"replace","value":"AutomixSDKPlaybackEventType","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace"}]}]}