{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackNumber-29iph"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel"]]},"metadata":{"navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel(py)trackNumber","title":"trackNumber","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"AutomixIQ"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdktrackmodel\/tracknumber-29iph"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdktrackmodel\/tracknumber-29iph"]}],"abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/trackNumber-29iph":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackNumber-29iph","title":"trackNumber","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"trackNumber","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdktrackmodel\/tracknumber-29iph"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdktrackmodel","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"type":"topic","kind":"symbol","title":"AutomixSDKTrackModel"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"trackNumber","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"trackNumber","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"trackNumber","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackNumber-29iph\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackNumber-29iph\/fragments","op":"replace","value":[{"text":"trackNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title","value":"AutomixSDKTrackModel","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}