{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotloadexplicitlyricstrack"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotloadexplicitlyricstrack"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"metadata":{"title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"role":"symbol","externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}],"symbolKind":"case","modules":[{"name":"AutomixIQ"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"AutomixSDK error codes","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","title":"AutomixSDKErrorCode","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotLoadExplicitLyricsTrack":{"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cannotLoadExplicitLyricsTrack","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotloadexplicitlyricstrack","kind":"symbol","title":"AutomixSDKErrorCode.cannotLoadExplicitLyricsTrack","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotLoadExplicitLyricsTrack"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/title","op":"replace","value":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotLoadExplicitLyricsTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotLoadExplicitLyricsTrack"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}