{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/fromIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/toIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackInstance","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/type"]}],"metadata":{"navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"symbolKind":"class","title":"AutomixSDKPlaylistOperation","modules":[{"name":"AutomixIQ"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKPlaylistOperation"},"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkplaylistoperation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkplaylistoperation"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"references":{"doc://org.cocoapods.AutomixIQ/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/trackInstance":{"abstract":[{"text":"The unique identifier for this track in this playlist, i.e. if the same track happens to appear twice in a playlist this identifier will differ.","type":"text"}],"title":"trackInstance","url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/trackinstance","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackInstance","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackInstance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackInstance"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation":{"abstract":[{"type":"text","text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation","title":"AutomixSDKPlaylistOperation","role":"symbol","url":"\/documentation\/automixiq\/automixsdkplaylistoperation","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/init","title":"init","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/init","role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/trackIdentifier":{"abstract":[{"type":"text","text":"The identifier of the track."}],"title":"trackIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackIdentifier","url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/trackidentifier","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackIdentifier"}]},"doc://org.cocoapods.AutomixIQ/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/toIndex":{"title":"toIndex","navigatorTitle":[{"kind":"identifier","text":"toIndex"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/toIndex","abstract":[{"type":"text","text":"The index int the playlist the track was added to or was moved to, -1 otherwise."}],"url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/toindex","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"toIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/fromIndex":{"title":"fromIndex","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromIndex"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":"The index int the playlist the track was removed from or was moved from, -1 otherwise.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"fromIndex","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/fromindex","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/fromIndex"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaylistOperation/type":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/type","title":"type","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaylistoperation\/type","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"AutomixSDKPlaylistOperationType","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKPlaylistOperationType"}],"abstract":[{"type":"text","text":"The type of operation, Add \/ Remove \/ Move"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKPlaylistOperation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/fromIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/toIndex","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/trackInstance","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/type"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaylistOperation\/init"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1trackInstance\/title","value":"trackInstance"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1trackInstance\/fragments","op":"replace","value":[{"kind":"identifier","text":"trackInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation"},{"value":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1trackIdentifier\/title","value":"trackIdentifier"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1trackIdentifier\/fragments","op":"replace","value":[{"text":"trackIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1toIndex\/title","value":"toIndex"},{"value":[{"text":"toIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1toIndex\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1fromIndex\/title","value":"fromIndex","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1fromIndex\/fragments","op":"replace","value":[{"kind":"identifier","text":"fromIndex"}]},{"value":"type","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1type\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaylistOperation~1type\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]}]}]}