{"sections":[],"seeAlsoSections":[{"title":"Initializing AutomixIQ for use with a custom backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKLogLevel","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKLogLevel"}],"title":"AutomixSDKLogLevel"},"abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"logLevelTrace","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ logs with no filter"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"AutomixIQ logs everything except low level details","type":"text"}],"type":"paragraph"}],"name":"logLevelDebug"},{"name":"logLevelInfo","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ logs everything except low level details and debug statements"}],"type":"paragraph"}]},{"name":"logLevelWarning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ only logs errors and warnings"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ only logs errors"}]}],"name":"logLevelError"},{"name":"logLevelFatal","content":[{"inlineContent":[{"type":"text","text":"AutomixIQ only logs fatal errors"}],"type":"paragraph"}]}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelWarning"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkloglevel"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","url":"\/documentation\/automixiq\/automixsdkloglevel","title":"AutomixSDKLogLevel","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelDebug":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelDebug"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelDebug","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelDebug"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelDebug","url":"\/documentation\/automixiq\/automixsdkloglevel\/logleveldebug"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/Equatable-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/Equatable-Implementations","url":"\/documentation\/automixiq\/automixsdkloglevel\/equatable-implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.AutomixIQ/SQ":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/automixiq\/automixsdkloglevel\/rawrepresentable-implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelFatal":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelFatal","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelFatal"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelFatal","url":"\/documentation\/automixiq\/automixsdkloglevel\/loglevelfatal"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelTrace":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelTrace","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelTrace"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelTrace","url":"\/documentation\/automixiq\/automixsdkloglevel\/logleveltrace"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","url":"\/documentation\/automixiq\/automixsdkloglevel\/init(rawvalue:)"},"doc://org.cocoapods.AutomixIQ/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"type":"topic","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"title":"AutomixSDKStreamingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelWarning":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelWarning"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelWarning","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"logLevelWarning","kind":"identifier"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelWarning","url":"\/documentation\/automixiq\/automixsdkloglevel\/loglevelwarning"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelInfo":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelInfo"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelInfo","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevelInfo"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelInfo","url":"\/documentation\/automixiq\/automixsdkloglevel\/loglevelinfo"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelError":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelError"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"logLevelError","kind":"identifier"}],"type":"topic","title":"AutomixSDKLogLevel.logLevelError","url":"\/documentation\/automixiq\/automixsdkloglevel\/loglevelerror"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with a custom backend"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","title":"Initializing AutomixIQ with a custom backend","role":"article","url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article","kind":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKLogLevel"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelDebug","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelFatal","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelInfo","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelTrace","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelWarning"]}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"],"title":"Initializing AutomixIQ for use with a custom backend","generated":true}]},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKLogLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDKLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelDebug\/title","op":"replace","value":"AutomixSDKLogLevelLogLevelDebug"},{"value":[{"text":"AutomixSDKLogLevelLogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelDebug\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelFatal\/title","value":"AutomixSDKLogLevelLogLevelFatal"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelFatal\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelFatal"}]},{"value":"AutomixSDKLogLevelLogLevelTrace","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelTrace\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelTrace\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"op":"replace"},{"value":"AutomixSDKStreamingDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelWarning\/title","value":"AutomixSDKLogLevelLogLevelWarning"},{"value":[{"text":"AutomixSDKLogLevelLogLevelWarning","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelWarning\/fragments"},{"op":"replace","value":"AutomixSDKLogLevelLogLevelInfo","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelInfo\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelError\/title","value":"AutomixSDKLogLevelLogLevelError","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelError"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}