{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixPlaybackEnded"}]}]}],"metadata":{"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","modules":[{"name":"PacemakerRadio"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeMixPlaybackEnded","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/mixplaybackended"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/mixplaybackended"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype\/mixplaybackended","abstract":[],"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mixPlaybackEnded"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","role":"symbol","title":"AutomixSDKPlaybackEventType","abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","op":"replace","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]}]}]}