{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"]]},"sections":[],"abstract":[{"text":"Turns the AutomixIQ player off.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In order to turn it back on you will have to call -(void)automixOnWithIdentifiers:playTrackIndex:seconds:autoplay:"}],"kind":"symbol","variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdk\/automixoff(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdk\/automixoff(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"automixOff","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","kind":"typeIdentifier","text":"AutomixSDKStatus"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}]}]}]}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDK(im)automixOffWithCompletion:","navigatorTitle":[{"kind":"identifier","text":"automixOffWithCompletion:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"PacemakerRadio"}],"title":"automixOff(completion:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"automixOff","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"text":"AutomixSDKStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOff(completion:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatus"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"title":"AutomixSDKStatus","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK","type":"topic","role":"symbol","title":"AutomixSDK","url":"\/documentation\/pacemakerradio\/automixsdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDK","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK/automixOff(completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK\/automixOff(completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixOff"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"automixOffWithCompletion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Turns the AutomixIQ player off."},{"type":"text","text":" "},{"type":"text","text":"In order to turn it back on you will have to call -(void)automixOnWithIdentifiers:playTrackIndex:seconds:autoplay:"}],"role":"symbol","title":"automixOff(completion:)","url":"\/documentation\/pacemakerradio\/automixsdk\/automixoff(completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"automixOffWithCompletion:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"automixOffWithCompletion:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"automixOffWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle"},{"op":"replace","value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments","op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOff(completion:)\/title","value":"automixOffWithCompletion:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK~1automixOff(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"automixOffWithCompletion:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}