{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/preferredtransitiondurationseconds"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/preferredtransitiondurationseconds"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"AutomixSDKStatusVariable.preferredTransitionDurationSeconds","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePreferredTransitionDurationSeconds","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/preferredTransitionDurationSeconds":{"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/preferredtransitiondurationseconds","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredTransitionDurationSeconds"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/preferredTransitionDurationSeconds","kind":"symbol","abstract":[],"role":"symbol","title":"AutomixSDKStatusVariable.preferredTransitionDurationSeconds"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","type":"topic","role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"kind":"symbol","title":"AutomixSDKStatusVariable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/title"},{"value":[{"text":"AutomixSDKStatusVariablePreferredTransitionDurationSeconds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1preferredTransitionDurationSeconds\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}