{"metadata":{"symbolKind":"method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate(im)syncGetCachedTrackWithTrackId:","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","role":"symbol","title":"syncGetCachedTrack(trackId:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgetcachedtrack(trackid:)"]},{"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgetcachedtrack(trackid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The id of the track that the AutomixIQ SDK is streaming.","type":"text"}],"type":"paragraph"}],"name":"trackId"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"the entire unencrypted track"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the entire unencrypted track."}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/syncGetCachedTrack(trackId:)":{"title":"syncGetCachedTrack(trackId:)","role":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgetcachedtrack(trackid:)","type":"topic","navigatorTitle":[{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the entire unencrypted track."}],"required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","kind":"symbol","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","title":"AutomixSDKStreamingDelegate","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","kind":"symbol","abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the information it requires to play content.","type":"text"},{"text":" ","type":"text"},{"text":"See TunedDemoStreamingHandler for an example of an object implementing this protocol.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"syncGetCachedTrackWithTrackId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"trackId","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/title","value":"syncGetCachedTrackWithTrackId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","op":"replace","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}