{"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"removeTrackOutOfBounds","kind":"identifier"}],"title":"AutomixSDKErrorCode.removeTrackOutOfBounds","roleHeading":"Case","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeRemoveTrackOutOfBounds","navigatorTitle":[{"text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/removeTrackOutOfBounds"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeTrackOutOfBounds"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/removetrackoutofbounds"]},{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/removetrackoutofbounds"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/removeTrackOutOfBounds":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/removeTrackOutOfBounds","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTrackOutOfBounds"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/removetrackoutofbounds","title":"AutomixSDKErrorCode.removeTrackOutOfBounds","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"kind":"symbol","role":"symbol","type":"topic","title":"AutomixSDKErrorCode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/title","value":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1removeTrackOutOfBounds\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeRemoveTrackOutOfBounds"}]},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","op":"replace"}]}]}