{"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyOn","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sdkAlreadyOn","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeSdkAlreadyOn","title":"AutomixSDKErrorCode.sdkAlreadyOn","symbolKind":"case","modules":[{"name":"AutomixIQ"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sdkAlreadyOn","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdkalreadyon"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/sdkalreadyon"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/sdkAlreadyOn":{"abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/sdkalreadyon","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/sdkAlreadyOn","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkAlreadyOn"}],"type":"topic","title":"AutomixSDKErrorCode.sdkAlreadyOn","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkAlreadyOn"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"kind":"symbol","role":"symbol","type":"topic","title":"AutomixSDKErrorCode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"AutomixSDKErrorCodeSdkAlreadyOn","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeSdkAlreadyOn"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyOn\/title","value":"AutomixSDKErrorCodeSdkAlreadyOn"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeSdkAlreadyOn","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1sdkAlreadyOn\/fragments"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]}]}]}