{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogsecondarybuttontextcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogsecondarybuttontextcolor"]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"roleHeading":"Instance Property","title":"dialogSecondaryButtonTextColor","role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig(py)dialogSecondaryButtonTextColor","navigatorTitle":[{"text":"dialogSecondaryButtonTextColor","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/dialogSecondaryButtonTextColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"type":"topic","title":"RadioSDKUIConfig","url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","role":"symbol","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig/dialogSecondaryButtonTextColor":{"navigatorTitle":[{"text":"dialogSecondaryButtonTextColor","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogsecondarybuttontextcolor","title":"dialogSecondaryButtonTextColor","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/dialogSecondaryButtonTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dialogSecondaryButtonTextColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dialogSecondaryButtonTextColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1dialogSecondaryButtonTextColor\/title","value":"dialogSecondaryButtonTextColor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1dialogSecondaryButtonTextColor\/fragments","value":[{"kind":"identifier","text":"dialogSecondaryButtonTextColor"}]}]}]}