{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/Equatable-Implementations","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH","doc:\/\/org.cocoapods.AutomixIQ\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"title":"AutomixSDKPlaybackEventType","modules":[{"name":"AutomixIQ"}],"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"roleHeading":"Enumeration","externalID":"c:@M@AutomixIQ@E@AutomixSDKPlaybackEventType","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate"],"title":"Updating custom player’s UI"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"abstract":[{"type":"text","text":"AutomixSDK play event type"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.AutomixIQ/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Updating-custom-player's-UI-article":{"type":"topic","kind":"article","role":"article","title":"Updating your player UI","url":"\/documentation\/automixiq\/updating-custom-player's-ui-article","abstract":[{"text":"How to create a UI to reflect the AutomixIQ player","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayHeartbeat30Secs":{"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlayHeartbeat30Secs","kind":"identifier"}],"kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayHeartbeat30Secs","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayheartbeat30secs","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayStart":{"navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlayStart","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayStart"}],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplaystart","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStart"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/init(rawValue:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/init(rawvalue:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayPlayed5Secs":{"title":"AutomixSDKPlaybackEventType.trackPlayPlayed5Secs","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayplayed5secs"},"doc://org.cocoapods.AutomixIQ/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"kind":"symbol","role":"symbol","abstract":[{"text":"AutomixSDK play event type","type":"text"}],"title":"AutomixSDKPlaybackEventType","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented by a class tasked with observing the status of the AutomixIQ SDK to reflect it on a UI.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"type":"topic","title":"AutomixSDKStatusObserverDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayStartMixingIntoNext":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayStartMixingIntoNext"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplaystartmixingintonext","type":"topic","title":"AutomixSDKPlaybackEventType.trackPlayStartMixingIntoNext","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlaySkipped":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"abstract":[],"kind":"symbol","title":"AutomixSDKPlaybackEventType.trackPlaySkipped","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlaySkipped","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayskipped","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlaySkipped"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/mixPlaybackEnded":{"title":"AutomixSDKPlaybackEventType.mixPlaybackEnded","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixPlaybackEnded","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/mixplaybackended","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/RawRepresentable-Implementations","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/rawrepresentable-implementations"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","kind":"article","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayFinished":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayFinished","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trackPlayFinished","kind":"identifier"}],"title":"AutomixSDKPlaybackEventType.trackPlayFinished","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayfinished"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"AutomixSDKPlaybackEventType","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/mixPlaybackEnded","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayFinished","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayHeartbeat30Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlaySkipped","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStart","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayStartMixingIntoNext"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Updating custom player’s UI","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayHeartbeat30Secs"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayHeartbeat30Secs\/fragments"},{"op":"replace","value":"AutomixSDKPlaybackEventTypeTrackPlayStart","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayStart\/title"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayStart","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayStart\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","op":"replace"},{"value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},{"op":"replace","value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayStartMixingIntoNext\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayStartMixingIntoNext"}]},{"value":"AutomixSDKPlaybackEventTypeTrackPlaySkipped","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlaySkipped"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlaySkipped\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/title","value":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeMixPlaybackEnded"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1mixPlaybackEnded\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayFinished\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayFinished","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayFinished\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayFinished","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}