{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/automixiq\/automixsdktrackmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdktrackmodel"]}],"metadata":{"role":"symbol","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","symbolKind":"class","title":"AutomixSDKTrackModel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"seeAlsoSections":[{"title":"Data models","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataDictionaryEntryModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"],"generated":true}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/init(from:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Artists","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Duration-2v49c","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Image","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/IsExplicit-gzv8","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Name","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/ReleaseName","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/TrackId","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/TrackNumber-oosb","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/bpm","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/duration-2pb5i","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/isExplicit-wipj","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/key","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackNumber-29iph"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AutomixIQ\/Se","doc:\/\/org.cocoapods.AutomixIQ\/SE","doc:\/\/org.cocoapods.AutomixIQ\/SQ","doc:\/\/org.cocoapods.AutomixIQ\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SH","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SE","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/duration-2pb5i":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/duration-2pb5i","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"duration","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/duration-2pb5i","type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the track duration"}],"navigatorTitle":[{"kind":"identifier","text":"duration"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/trackIdentifier":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/trackidentifier","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"trackIdentifier","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackIdentifier","type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the track identifier as String"}],"navigatorTitle":[{"text":"trackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/TrackId":{"kind":"symbol","role":"symbol","title":"TrackId","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/TrackId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TrackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The identifier of a track as an integer"}],"type":"topic","url":"\/documentation\/automixiq\/automixsdktrackmodel\/trackid"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Data-models-article":{"type":"topic","title":"Data models","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","url":"\/documentation\/automixiq\/data-models-article","role":"article","kind":"article","abstract":[{"text":"How data is passed to and from the AutomixIQ player","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKArtistModel":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkartistmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKArtistModel","kind":"identifier"}],"title":"AutomixSDKArtistModel","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","type":"topic","abstract":[{"text":"AutomixSDKArtistModel models an artist. This metadata is required","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/IsExplicit-gzv8":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/isexplicit-gzv8","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsExplicit"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"title":"IsExplicit","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/IsExplicit-gzv8","type":"topic","abstract":[{"text":"true if the track is explicit, false otherwise","type":"text"}]},"doc://org.cocoapods.AutomixIQ/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/Se","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/Image":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/image","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"Image","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Image","type":"topic","abstract":[{"text":"The url of the artwork image for this track as a String","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/isExplicit-wipj":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/isexplicit-wipj","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isExplicit"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isExplicit","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/isExplicit-wipj","type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for IsExplicit"}],"navigatorTitle":[{"text":"isExplicit","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)":{"abstract":[{"text":"Initialises a Track Model","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","role":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isExplicit"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"trackNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"releaseName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse":{"type":"topic","title":"TunedAuthenticationResponse","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","url":"\/documentation\/automixiq\/tunedauthenticationresponse","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}]},"doc://org.cocoapods.AutomixIQ/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/init(from:)":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"init(from:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/init(from:)","type":"topic","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/Artists":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/artists","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Artists"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKArtistModel","kind":"typeIdentifier","text":"AutomixSDKArtistModel"},{"text":"]?","kind":"text"}],"title":"Artists","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Artists","type":"topic","abstract":[{"text":"The artists of a track - the first one is the one to be presented by a UI","type":"text"}],"navigatorTitle":[{"text":"Artists","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/ReleaseName":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/releasename","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReleaseName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"ReleaseName","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/ReleaseName","type":"topic","abstract":[{"text":"The name of the album this track belongs to","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ReleaseName"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/Duration-2v49c":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/duration-2v49c","abstract":[{"text":"The duration of a track in seconds","type":"text"}],"role":"symbol","title":"Duration","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"Duration"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Duration-2v49c"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/TrackNumber-oosb":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/tracknumber-oosb","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":"?","kind":"text"}],"title":"TrackNumber","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/TrackNumber-oosb","type":"topic","abstract":[{"type":"text","text":"The index of this track in the album it belongs to"}]},"doc://org.cocoapods.AutomixIQ/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/SQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPluginMetadataDictionaryEntryModel":{"type":"topic","title":"AutomixSDKPluginMetadataDictionaryEntryModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKPluginMetadataDictionaryEntryModel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKPluginMetadataDictionaryEntryModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataDictionaryEntryModel","url":"\/documentation\/automixiq\/automixsdkpluginmetadatadictionaryentrymodel","role":"symbol","kind":"symbol","abstract":[{"text":"AutomixSDKPluginMetadataDictionaryEntryModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}]},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","url":"\/documentation\/automixiq\/automixsdkstatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"title":"AutomixSDKStatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/trackNumber-29iph":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/tracknumber-29iph","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"trackNumber","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackNumber-29iph","type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the track number"}],"navigatorTitle":[{"text":"trackNumber","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/bpm":{"url":"\/documentation\/automixiq\/automixsdktrackmodel\/bpm","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bpm"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"bpm","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/bpm","type":"topic","abstract":[{"text":"Objective-C accessible member for the bpm, 09 if unavailable","type":"text"}],"navigatorTitle":[{"text":"bpm","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/Name":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/name","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"Name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"Name","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Name","type":"topic","abstract":[{"text":"The title of a track","type":"text"}],"navigatorTitle":[{"text":"Name","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"type":"topic","url":"\/documentation\/automixiq\/automixsdktrackmodel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"title":"AutomixSDKTrackModel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}]},"doc://org.cocoapods.AutomixIQ/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel/key":{"kind":"symbol","url":"\/documentation\/automixiq\/automixsdktrackmodel\/key","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"key","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/key","type":"topic","abstract":[{"text":"Objective-C accessible member for the key, nil if unavailable","type":"text"}],"navigatorTitle":[{"text":"key","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKTrackModel"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Artists","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Image","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/Name","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/ReleaseName","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/bpm","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/duration-2pb5i","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/isExplicit-wipj","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/key","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/trackNumber-29iph"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Data models","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataDictionaryEntryModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKTrackModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1duration-2pb5i\/title","value":"duration","op":"replace"},{"value":[{"kind":"identifier","text":"duration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1duration-2pb5i\/fragments"},{"op":"replace","value":"trackIdentifier","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackIdentifier\/title"},{"value":[{"kind":"identifier","text":"trackIdentifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackIdentifier\/fragments","op":"replace"},{"op":"replace","value":"AutomixSDKArtistModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKArtistModel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKArtistModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Image\/title","value":"Image"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Image\/fragments","op":"replace","value":[{"text":"Image","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1isExplicit-wipj\/title","op":"replace","value":"isExplicit"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1isExplicit-wipj\/fragments","op":"replace","value":[{"text":"isExplicit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/title","value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse","op":"replace"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/fragments","op":"replace"},{"value":"Artists","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Artists\/title"},{"value":[{"kind":"identifier","text":"Artists"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Artists\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1ReleaseName\/title","value":"ReleaseName"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1ReleaseName\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReleaseName"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPluginMetadataDictionaryEntryModel\/title","op":"replace","value":"AutomixSDKPluginMetadataDictionaryEntryModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPluginMetadataDictionaryEntryModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataDictionaryEntryModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackNumber-29iph\/title","value":"trackNumber"},{"value":[{"text":"trackNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1trackNumber-29iph\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1bpm\/title","value":"bpm","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1bpm\/fragments","value":[{"kind":"identifier","text":"bpm"}]},{"value":"Name","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Name\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1Name\/fragments","value":[{"kind":"identifier","text":"Name"}],"op":"replace"},{"value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title","op":"replace"},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1key\/title","op":"replace","value":"key"},{"op":"replace","value":[{"kind":"identifier","text":"key"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel~1key\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}