{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)"},"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(im)initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureSetConfig"},{"kind":"text","text":": "},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiConfig"},{"text":": ","kind":"text"},{"text":"RadioSDKUIConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"featureSetConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier","text":"RadioSDKFeatureSetConfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig"},{"text":" = RadioSDKFeatureSetConfig(), ","kind":"text"},{"text":"uiConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","text":"RadioSDKUIConfig"},{"kind":"text","text":" = RadioSDKUIConfig())"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"kind":"symbol","navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig","type":"topic","abstract":[],"title":"RadioSDKFeatureSetConfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"abstract":[],"title":"RadioSDKConfig","url":"\/documentation\/pacemakerradio\/radiosdkconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","role":"symbol","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"type":"topic","title":"RadioSDKUIConfig","url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","role":"symbol","navigatorTitle":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKUIConfig"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)":{"kind":"symbol","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig"},{"text":", ","kind":"text"},{"text":"uiConfig","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"apiKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"country:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"country"},{"kind":"text","text":" "},{"text":"storeId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"storeId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"featureSetConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig","kind":"typeIdentifier","text":"RadioSDKFeatureSetConfig"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"featureSetConfig"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfig:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","kind":"typeIdentifier","text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uiConfig"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"RadioSDKFeatureSetConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title"},{"value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments"},{"value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle"},{"value":"RadioSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","op":"replace","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"op":"replace","value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:"}],"op":"replace"}]}]}