{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"artistName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackNumber"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"releaseName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The identifier of the track","type":"text"}]}],"name":"trackId"},{"name":"artistName","content":[{"inlineContent":[{"type":"text","text":"The name of the main artist of the track"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The title of the track"}]}],"name":"name"},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track duration in seconds"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"True if the track contains explicit lyrics, false otherwise"}],"type":"paragraph"}],"name":"isExplicit"},{"name":"trackNumber","content":[{"inlineContent":[{"type":"text","text":"The index of the track in the album it was released in"}],"type":"paragraph"}]},{"name":"releaseName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The nemae of the release this track’s in"}]}]},{"name":"key","content":[{"inlineContent":[{"text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable","type":"text"}],"type":"paragraph"}]},{"name":"tempo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The bpm of this track as a float"}]}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"type":"paragraph"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)"]},{"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel"]]},"metadata":{"title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isExplicit"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackNumber"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"releaseName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"tempo","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel(im)initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","symbolKind":"init","roleHeading":"Initializer"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Initialises a Track Model"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)":{"type":"topic","kind":"symbol","title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","role":"symbol","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"abstract":[{"text":"Initialises a Track Model","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"artistName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"isExplicit","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"releaseName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tempo"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","title":"AutomixSDKTrackModel","role":"symbol","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTrackId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"artistName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"artistName","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"duration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"duration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isExplicit:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isExplicit","kind":"internalParam"},{"kind":"text","text":" "},{"text":"trackNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"trackNumber","kind":"internalParam"},{"kind":"text","text":" "},{"text":"releaseName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"releaseName","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"text":"tempo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"tempo"},{"text":" ","kind":"text"},{"text":"image:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"text":"The identifier of the track","type":"text"}],"type":"paragraph"}]},{"name":"artistName","content":[{"inlineContent":[{"type":"text","text":"The name of the main artist of the track"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The title of the track"}]}],"name":"name"},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track duration in seconds"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"True if the track contains explicit lyrics, false otherwise"}],"type":"paragraph"}],"name":"isExplicit"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The index of the track in the album it was released in","type":"text"}]}],"name":"trackNumber"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The nemae of the release this track’s in","type":"text"}]}],"name":"releaseName"},{"content":[{"inlineContent":[{"type":"text","text":"The key of this track as a String in Camelot format, i.e. 8m, nil if unavailable"}],"type":"paragraph"}],"name":"key"},{"name":"tempo","content":[{"inlineContent":[{"type":"text","text":"The bpm of this track as a float"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the artwork image for this track as a String"}]}],"name":"image"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/title","value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}]},{"op":"replace","value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}]},{"value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}