{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"masterTempoNormalized"}]}]}],"sections":[],"metadata":{"roleHeading":"Case","title":"AutomixSDKStatusVariable.masterTempoNormalized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masterTempoNormalized","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableMasterTempoNormalized","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableMasterTempoNormalized"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/masterTempoNormalized"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/mastertemponormalized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/mastertemponormalized"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/masterTempoNormalized":{"title":"AutomixSDKStatusVariable.masterTempoNormalized","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/masterTempoNormalized","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableMasterTempoNormalized"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterTempoNormalized"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/mastertemponormalized"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"url":"\/documentation\/automixiq\/automixsdkstatusvariable","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"AutomixSDK play event type"}],"title":"AutomixSDKStatusVariable","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"AutomixSDKStatusVariableMasterTempoNormalized","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"AutomixSDKStatusVariableMasterTempoNormalized","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableMasterTempoNormalized"}]}],"kind":"declarations"}},{"value":"AutomixSDKStatusVariableMasterTempoNormalized","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1masterTempoNormalized\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1masterTempoNormalized\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableMasterTempoNormalized"}]},{"op":"replace","value":"AutomixSDKStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}