{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineNoTunedUserIdAvailable"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"roleHeading":"Case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","symbolKind":"case","role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/offlinenotuneduseridavailable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/offlinenotuneduseridavailable"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"title":"AutomixSDKErrorCode","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/offlineNoTunedUserIdAvailable":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"title":"AutomixSDKErrorCode.offlineNoTunedUserIdAvailable","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/offlinenotuneduseridavailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"offlineNoTunedUserIdAvailable","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/offlineNoTunedUserIdAvailable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/title","value":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1offlineNoTunedUserIdAvailable\/fragments","value":[{"text":"AutomixSDKErrorCodeOfflineNoTunedUserIdAvailable","kind":"identifier"}]}]}]}