{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"]]},"metadata":{"title":"initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","modules":[{"name":"PacemakerRadio"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"text":"radioUIDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"RadioUIDelegate"},{"text":", ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDK(cm)initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","kind":"typeIdentifier","text":"RadioUIDelegate"},{"text":", ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"apiKey","content":[{"type":"paragraph","inlineContent":[{"text":"The RadioSDK API Key","type":"text"}]}]},{"name":"tunedDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate."}],"type":"paragraph"}],"name":"statusDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of presenting user interfaces the Radio SDK needs","type":"text"}]}],"name":"radioUIDelegate"},{"content":[{"inlineContent":[{"text":"The ISO2 country code the device runs from.","type":"text"}],"type":"paragraph"}],"name":"countryCode"},{"name":"storeId","content":[{"inlineContent":[{"text":"Tuned Global’s store id.","type":"text"}],"type":"paragraph"}]},{"name":"applicationId","content":[{"type":"paragraph","inlineContent":[{"text":"Application id.","type":"text"}]}]},{"name":"musicCacheDelegate","content":[{"inlineContent":[{"text":"The delegate providing cached track data and metadata.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdk\/initialise(apikey:tuneddelegate:statusdelegate:radiouidelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdk\/initialise(apikey:tuneddelegate:statusdelegate:radiouidelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"]}],"abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"title":"RadioSDK","url":"\/documentation\/pacemakerradio\/radiosdk","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDK"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","role":"symbol","url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"type":"topic","title":"TunedMusicCacheDelegate"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"title":"AutomixSDKStatusObserverDelegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"RadioUIDelegate","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/radiouidelegate","title":"RadioUIDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioUIDelegate"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedRestDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"type":"topic","title":"TunedRestDelegate","url":"\/documentation\/pacemakerradio\/tunedrestdelegate","role":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)":{"kind":"symbol","url":"\/documentation\/pacemakerradio\/radiosdk\/initialise(apikey:tuneddelegate:statusdelegate:radiouidelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)","navigatorTitle":[{"kind":"identifier","text":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:"}],"type":"topic","title":"initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","abstract":[{"type":"text","text":"Initialiser for Radio SDK to work against a Tuned Global’s Store and Tuned Global’s APIs."},{"text":" ","type":"text"},{"text":"This method takes in delegates to update the UI and feed access tokens to the Tuned Global’s APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": "},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIDelegate"},{"kind":"text","text":": "},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initialiseWithApiKey:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"apiKey","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"id<TunedRestDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"tunedDelegate"},{"kind":"text","text":" "},{"text":"statusDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"id<AutomixSDKStatusObserverDelegate>"},{"kind":"text","text":") "},{"text":"statusDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"text":"radioUIDelegate:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"id<RadioUIDelegate>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"radioUIDelegate"},{"kind":"text","text":" "},{"text":"countryCode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"countryCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"storeId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"storeId"},{"kind":"text","text":" "},{"text":"applicationId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"musicCacheDelegate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"id<TunedMusicCacheDelegate>"},{"text":") ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The RadioSDK API Key","type":"text"}]}],"name":"apiKey"},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global APIs access tokens. See TunedRestDelegate.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of updating any UI with status updates from Automix SDK. See AutomixSDKStatusObserverDelegate.","type":"text"}]}],"name":"statusDelegate"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate in charge of presenting user interfaces the Radio SDK needs"}]}],"name":"radioUIDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The ISO2 country code the device runs from."}],"type":"paragraph"}],"name":"countryCode"},{"name":"storeId","content":[{"inlineContent":[{"text":"Tuned Global’s store id.","type":"text"}],"type":"paragraph"}]},{"name":"applicationId","content":[{"inlineContent":[{"text":"Application id.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delegate providing cached track data and metadata.","type":"text"}]}],"name":"musicCacheDelegate"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","value":"RadioSDK","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/fragments","op":"replace","value":[{"kind":"identifier","text":"RadioSDK"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/navigatorTitle","op":"replace","value":[{"text":"RadioSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title","op":"replace","value":"TunedMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle"},{"value":"RadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments","value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"RadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)\/title","value":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1initialise(apiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithApiKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}