{"sections":[],"abstract":[{"text":"true if this waveform is placeholder data, false otherwise","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/placeholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/placeholder"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/placeholder"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"role":"symbol","title":"placeholder","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel(py)placeholder","modules":[{"name":"PacemakerRadio"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel/placeholder":{"type":"topic","abstract":[{"text":"true if this waveform is placeholder data, false otherwise","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel\/placeholder","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel\/placeholder","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"placeholder"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"title":"AutomixSDKWaveformModel","role":"symbol","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","type":"topic","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"placeholder","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"placeholder"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"placeholder","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1placeholder\/title","value":"placeholder"},{"value":[{"kind":"identifier","text":"placeholder"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel~1placeholder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title","op":"replace","value":"AutomixSDKWaveformModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments","value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}