{"metadata":{"role":"symbol","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"}],"roleHeading":"Case","title":"AutomixSDKStatusVariable.playlistDiff","symbolKind":"case","externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePlaylistDiff","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaylistDiff","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/playlistdiff"]},{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/playlistdiff"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlistDiff","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/playlistDiff":{"role":"symbol","abstract":[],"url":"\/documentation\/automixiq\/automixsdkstatusvariable\/playlistdiff","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"playlistDiff","kind":"identifier"}],"title":"AutomixSDKStatusVariable.playlistDiff","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/playlistDiff","navigatorTitle":[{"text":"AutomixSDKStatusVariablePlaylistDiff","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"role":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkstatusvariable","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKStatusVariablePlaylistDiff"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylistDiff"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AutomixSDKStatusVariablePlaylistDiff","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"AutomixSDKStatusVariablePlaylistDiff","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlistDiff\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1playlistDiff\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylistDiff"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","op":"replace","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace"}]}]}