{"kind":"symbol","metadata":{"title":"AutomixSDKCachedMusicProvider","roleHeading":"Protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"modules":[{"name":"AutomixIQ"}],"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider"},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"AutomixSDKCachedMusicProvider protocol defines the methods to be implemented by a class tasked with storing and providing cached track data"}],"seeAlsoSections":[{"generated":true,"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackBufferingProgress(trackId:progress:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackFinishedDownloading(trackId:data:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider"]},{"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","type":"topic","url":"\/documentation\/automixiq\/initialising-automixiq-article","title":"Initializing AutomixIQ","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs"}],"role":"article","kind":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/syncGetCachedTrack(trackId:)":{"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgetcachedtrack(trackid:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"abstract":[{"text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the entire unencrypted track.","type":"text"}],"kind":"symbol","required":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetCachedTrack(trackId:)","title":"syncGetCachedTrack(trackId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"syncGetCachedTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/trackBufferingProgress(trackId:progress:)":{"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/trackbufferingprogress(trackid:progress:)","title":"trackBufferingProgress(trackId:progress:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackBufferingProgress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackBufferingProgress(trackId:progress:)","navigatorTitle":[{"kind":"identifier","text":"trackBufferingProgressWithTrackId:progress:"}],"type":"topic","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK when a track download progress has changed."}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented by a class tasked with providing the credentials and identifiers to Tuned Global’s backend"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedRestDelegate","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/trackFinishedDownloading(trackId:data:)":{"title":"trackFinishedDownloading(trackId:data:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackFinishedDownloading"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackFinishedDownloading(trackId:data:)","navigatorTitle":[{"text":"trackFinishedDownloadingWithTrackId:data:","kind":"identifier"}],"abstract":[{"text":"Called by the AutomixIQ SDK when a track has been fully downloaded.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/trackfinisheddownloading(trackid:data:)","required":true,"type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/syncGetTrackMetadata(trackId:)":{"title":"syncGetTrackMetadata(trackId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadata"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgettrackmetadata(trackid:)","kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetTrackMetadata(trackId:)","type":"topic","abstract":[{"text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the required data from an on-device cache or any other synchronous method","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider":{"role":"symbol","url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"navigatorTitle":[{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}],"abstract":[{"text":"AutomixSDKCachedMusicProvider protocol defines the methods to be implemented by a class tasked with storing and providing cached track data","type":"text"}],"title":"AutomixSDKCachedMusicProvider","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"AutomixSDKCachedMusicProvider","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}]},{"value":[{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetCachedTrack(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetTrackMetadata(trackId:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackBufferingProgress(trackId:progress:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackFinishedDownloading(trackId:data:)"]}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate"]}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"kind":"text","text":">"}]}]}},{"value":"syncGetCachedTrackWithTrackId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetCachedTrack(trackId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetCachedTrack(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackBufferingProgress(trackId:progress:)\/title","value":"trackBufferingProgressWithTrackId:progress:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackBufferingProgress(trackId:progress:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackBufferingProgressWithTrackId:progress:","kind":"identifier"}]},{"value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"value":"trackFinishedDownloadingWithTrackId:data:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackFinishedDownloading(trackId:data:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackFinishedDownloading(trackId:data:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackFinishedDownloadingWithTrackId:data:"}],"op":"replace"},{"value":"syncGetTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetTrackMetadata(trackId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetTrackMetadata(trackId:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/title","value":"AutomixSDKCachedMusicProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/fragments","value":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}]}]}]}