{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"expires_in","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"PacemakerRadio"}],"title":"expires_in","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expires_in","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:14PacemakerRadio27TunedAuthenticationResponseC10expires_inSiSgvp","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse\/expires_in","interfaceLanguage":"swift"},"abstract":[{"text":"The expiry time","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/tunedauthenticationresponse\/expires_in"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse/expires_in":{"url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse\/expires_in","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse\/expires_in","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expires_in","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"title":"expires_in","abstract":[{"text":"The expiry time","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"title":"TunedAuthenticationResponse","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedAuthenticationResponse"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"op":"replace"}]}]}