{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/init"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/init"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)init","role":"symbol","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/init":{"url":"\/documentation\/automixiq\/automixsdk\/init","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDK"}],"title":"AutomixSDK","type":"topic","url":"\/documentation\/automixiq\/automixsdk","abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AutomixSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"},{"value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/navigatorTitle"}]}]}