{"metadata":{"symbolKind":"module","modules":[{"name":"AutomixIQ"}],"externalID":"AutomixIQ","title":"AutomixIQ","role":"collection","roleHeading":"Framework"},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Importing AutomixIQ","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Importing-AutomixIQ-article"]},{"title":"AutomixSDK singleton","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC"]},{"title":"Initializing AutomixIQ for use with Tuned Global’s APIs","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate"]},{"title":"Initializing AutomixIQ for use with a custom backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"]},{"title":"Switching between AutomixIQ player and any other player","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Switching-between-AutomixIQ-player-and-any-other-player-article"]},{"title":"Controlling playback","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Audio-file-requirements-article"],"title":"Audio file requirements"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"],"title":"Updating custom player’s UI"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article"],"title":"Accessing waveform data"},{"title":"Errors","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"],"title":"Data models"},{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Persistency-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLogID","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLogID"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/sdkError(code:)"],"title":"Functions"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithErrorAndPlaybackState"],"title":"Type Aliases"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Swift"]}],"primaryContentSections":[{"content":[{"level":2,"text":"Overview","anchor":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ is a framework that exposes a music player which analyzes tracks in your application. It offers machine-learned transitions between tracks and when seeking, essentially serving as an automated DJ for your music. The framework determines the ideal points in each song to smoothly transition to the next, synchronizing beats and matching keys."}]},{"type":"paragraph","inlineContent":[{"text":"This documentation provides a step-by-step guide (in both Objective C or Swift) on how to get started with using the AutomixIQ SDK in your application.","type":"text"}]},{"inlineContent":[{"identifier":"overview-tuned-demo-automix","type":"image"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/automixiq"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"title":"AutomixSDKErrorCode","url":"\/documentation\/automixiq\/automixsdkerrorcode","type":"topic","abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"title":"AutomixSDKLogLevel","url":"\/documentation\/automixiq\/automixsdkloglevel","type":"topic","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlayLogAttributes":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"title":"AutomixSDKPlayLogAttributes","url":"\/documentation\/automixiq\/automixsdkplaylogattributes","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLogAttributes","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLogAttributes","abstract":[],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Persistency-article":{"type":"topic","kind":"article","role":"article","url":"\/documentation\/automixiq\/persistency-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Persistency-article","title":"Persistency","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"title":"AutomixSDKPlaybackEventType","abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKArtistModel":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","title":"AutomixSDKArtistModel","url":"\/documentation\/automixiq\/automixsdkartistmodel","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKArtistModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","type":"topic","role":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusvariable","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"kind":"symbol","title":"AutomixSDKStatusVariable"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"url":"\/documentation\/automixiq\/completionwitherror","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","kind":"symbol","title":"CompletionWithError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CompletionWithError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","type":"topic","title":"AutomixSDKStreamingDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTransitionLogAttributes":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogAttributes"}],"title":"AutomixSDKTransitionLogAttributes","url":"\/documentation\/automixiq\/automixsdktransitionlogattributes","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogAttributes","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLogAttributes","abstract":[],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Swift":{"title":"Swift","kind":"symbol","url":"\/documentation\/automixiq\/swift","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Swift","abstract":[],"type":"topic","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Errors-article":{"abstract":[{"type":"text","text":"What errors the AutomixIQ player can issue to help with player integration"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article","title":"Errors","type":"topic","kind":"article","role":"article","url":"\/documentation\/automixiq\/errors-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","title":"TunedRestDelegate","url":"\/documentation\/automixiq\/tunedrestdelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Controlling-playback-article":{"url":"\/documentation\/automixiq\/controlling-playback-article","type":"topic","abstract":[{"text":"How to play, skip, pause and seek through content","type":"text"}],"role":"article","title":"Controlling Playback","kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTransitionLogID":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/automixsdktransitionlogid","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLogID","title":"AutomixSDKTransitionLogID","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlayLogID":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/automixiq\/automixsdkplaylogid","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLogID","title":"AutomixSDKPlayLogID","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLogID","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithErrorAndPlaybackState":{"kind":"symbol","type":"topic","title":"CompletionWithErrorAndPlaybackState","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithErrorAndPlaybackState","navigatorTitle":[{"text":"CompletionWithErrorAndPlaybackState","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CompletionWithErrorAndPlaybackState"}],"role":"symbol","abstract":[],"url":"\/documentation\/automixiq\/completionwitherrorandplaybackstate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTransitionLog":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLog"}],"title":"AutomixSDKTransitionLog","url":"\/documentation\/automixiq\/automixsdktransitionlog","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLog","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTransitionLog","abstract":[],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatus"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"title":"AutomixSDKStatus","type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Data-models-article":{"url":"\/documentation\/automixiq\/data-models-article","abstract":[{"text":"How data is passed to and from the AutomixIQ player","type":"text"}],"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","title":"Data models","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Switching-between-AutomixIQ-player-and-any-other-player-article":{"kind":"article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Switching-between-AutomixIQ-player-and-any-other-player-article","title":"Switching between AutomixIQ player and any other player","abstract":[{"text":"How to toggle the AutomixIQ player on and off","type":"text"}],"role":"article","type":"topic","url":"\/documentation\/automixiq\/switching-between-automixiq-player-and-any-other-player-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/sdkError(code:)":{"title":"sdkError(code:)","abstract":[],"url":"\/documentation\/automixiq\/sdkerror(code:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/sdkError(code:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkError"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKErrorCode","preciseIdentifier":"c:@M@AutomixIQ@E@AutomixSDKErrorCode","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Audio-file-requirements-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Audio-file-requirements-article","type":"topic","url":"\/documentation\/automixiq\/audio-file-requirements-article","kind":"article","role":"article","abstract":[],"title":"Audio file requirements"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Accessing-waveform-data-article":{"url":"\/documentation\/automixiq\/accessing-waveform-data-article","role":"article","kind":"article","title":"Accessing waveform data","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"role":"symbol","type":"topic","title":"AutomixSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","type":"topic","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"url":"\/documentation\/automixiq\/tunedmusiccachedelegate","title":"TunedMusicCacheDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-article":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with Tuned Global APIs"}],"kind":"article","title":"Initializing AutomixIQ","url":"\/documentation\/automixiq\/initialising-automixiq-article","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlayLog":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLog"}],"title":"AutomixSDKPlayLog","url":"\/documentation\/automixiq\/automixsdkplaylog","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLog","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlayLog","abstract":[],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC":{"url":"\/documentation\/automixiq\/automixsdkobjc","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC","kind":"symbol","title":"AutomixSDKObjC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKObjC"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Updating-custom-player's-UI-article":{"kind":"article","type":"topic","url":"\/documentation\/automixiq\/updating-custom-player's-ui-article","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","abstract":[{"type":"text","text":"How to create a UI to reflect the AutomixIQ player"}],"title":"Updating your player UI","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"type":"topic","title":"AutomixSDKTrackModel","url":"\/documentation\/automixiq\/automixsdktrackmodel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse":{"role":"symbol","title":"TunedAuthenticationResponse","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"type":"topic","url":"\/documentation\/automixiq\/tunedauthenticationresponse","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Importing-AutomixIQ-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Importing-AutomixIQ-article","type":"topic","url":"\/documentation\/automixiq\/importing-automixiq-article","kind":"article","role":"article","abstract":[{"type":"text","text":"Accessing the PacemakerAutomixIQ framework"}],"title":"Importing AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Initialising-AutomixIQ-with-custom-backend-article":{"type":"topic","abstract":[{"type":"text","text":"How to validate your client and start using the AutomixIQ SDK with a custom backend"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","title":"Initializing AutomixIQ with a custom backend","kind":"article","role":"article","url":"\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPluginMetadataModel":{"url":"\/documentation\/automixiq\/automixsdkpluginmetadatamodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataModel","type":"topic","abstract":[{"text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format."}],"kind":"symbol","title":"AutomixSDKPluginMetadataModel","role":"symbol"},"overview-tuned-demo-automix":{"type":"image","identifier":"overview-tuned-demo-automix","alt":"A player interface that uses the AutomixIQ player to reproduce a playlist. The automatically generated transition is highlighted in yellow.","variants":[{"traits":["1x","light"],"url":"\/images\/overview-tuned-demo-automix.png"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Importing-AutomixIQ-article"],"title":"Importing AutomixIQ"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"],"title":"AutomixSDK singleton"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate"],"title":"Initializing AutomixIQ for use with Tuned Global’s APIs"},{"title":"Initializing AutomixIQ for use with a custom backend","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"]},{"title":"Switching between AutomixIQ player and any other player","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Switching-between-AutomixIQ-player-and-any-other-player-article"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Controlling-playback-article"],"title":"Controlling playback"},{"title":"Audio file requirements","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Audio-file-requirements-article"]},{"title":"Updating custom player’s UI","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article"],"title":"Accessing waveform data"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Errors-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"],"title":"Errors"},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Data-models-article","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"],"title":"Data models"},{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Persistency-article"]},{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"],"title":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"AutomixSDKErrorCode","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"op":"replace"},{"op":"replace","value":"AutomixSDKLogLevel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"value":"AutomixSDKPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKArtistModel\/title","op":"replace","value":"AutomixSDKArtistModel"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKArtistModel\/fragments","op":"replace","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments"},{"op":"replace","value":"TunedRestDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments"},{"value":"AutomixSDKStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","op":"replace","value":"AutomixSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments","op":"replace","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},{"value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse"},{"value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPluginMetadataModel\/title","value":"AutomixSDKPluginMetadataModel"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPluginMetadataModel\/fragments"}]}]}