{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixId","kind":"identifier"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableMixId","roleHeading":"Case","navigatorTitle":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"title":"AutomixSDKStatusVariable.mixId","role":"symbol","modules":[{"name":"PacemakerRadio"}],"symbolKind":"case"},"sections":[],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/mixid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/mixid"]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/mixId","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mixId","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/mixId":{"title":"AutomixSDKStatusVariable.mixId","navigatorTitle":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixId"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/mixid","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/mixId","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"role":"collection","type":"topic","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","title":"AutomixSDKStatusVariable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKStatusVariableMixId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixSDKStatusVariableMixId","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1mixId\/title","op":"replace"},{"value":[{"text":"AutomixSDKStatusVariableMixId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1mixId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]}]}]}