{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token_type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/tunedauthenticationresponse\/token_type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/tunedauthenticationresponse\/token_type"]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"token_type","navigatorTitle":[{"text":"token_type","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token_type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@AutomixIQ@objc(cs)TunedAuthenticationResponse(py)token_type"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The token type"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse\/token_type","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse":{"abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse","kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/tunedauthenticationresponse","title":"TunedAuthenticationResponse","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedAuthenticationResponse/token_type":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedAuthenticationResponse\/token_type","abstract":[{"text":"The token type","type":"text"}],"role":"symbol","type":"topic","title":"token_type","kind":"symbol","url":"\/documentation\/automixiq\/tunedauthenticationresponse\/token_type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token_type","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"token_type","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"token_type"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"token_type","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"token_type","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TunedAuthenticationResponse","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/title","op":"replace"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse~1token_type\/title","op":"replace","value":"token_type"},{"value":[{"text":"token_type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedAuthenticationResponse~1token_type\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}