{"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"playbackEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"originalSessionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The playback event type"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The track identifier this event refers to"}]}],"name":"identifier"},{"name":"originalSessionId","content":[{"inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The current status of AutomixIQ","type":"text"}],"type":"paragraph"}],"name":"status"}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate(im)playbackEventWithType:identifier:originalSessionId:status:","roleHeading":"Instance Method","title":"playbackEvent(type:identifier:originalSessionId:status:)","modules":[{"name":"PacemakerRadio"}],"symbolKind":"method","navigatorTitle":[{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackEvent"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType","text":"AutomixSDKPlaybackEventType"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"originalSessionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus"},{"text":"?)","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Called when a playback event of AutomixIQ happens","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"title":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","type":"topic","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKPlaybackEventType is an enum of all the available playback events"}],"title":"AutomixSDKPlaybackEventType","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkstatus","title":"AutomixSDKStatus"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate/playbackEvent(type:identifier:originalSessionId:status:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate\/playbackEvent(type:identifier:originalSessionId:status:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playbackEventWithType:identifier:originalSessionId:status:"}],"abstract":[{"type":"text","text":"Called when a playback event of AutomixIQ happens"}],"title":"playbackEvent(type:identifier:originalSessionId:status:)","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/playbackevent(type:identifier:originalsessionid:status:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"AutomixSDKPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType"},{"kind":"text","text":", "},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"originalSessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus"},{"kind":"text","text":"?)"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playbackEventWithType:identifier:originalSessionId:status:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"playbackEventWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKPlaybackEventType","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"identifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"originalSessionId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"originalSessionId"},{"text":" ","kind":"text"},{"text":"status:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AutomixSDKStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":{"parameters":[{"name":"type","content":[{"inlineContent":[{"text":"The playback event type","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The track identifier this event refers to"}],"type":"paragraph"}],"name":"identifier"},{"name":"originalSessionId","content":[{"inlineContent":[{"text":"The initial session id for the track this event refers to. AutomixIQ may use more session ids as needed if the session expires and it needs more data.","type":"text"}],"type":"paragraph"}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AutomixSDKStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"value":"AutomixSDKPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","op":"replace"},{"value":[{"text":"AutomixSDKStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle"},{"value":"playbackEventWithType:identifier:originalSessionId:status:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate~1playbackEvent(type:identifier:originalSessionId:status:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"playbackEventWithType:identifier:originalSessionId:status:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}