{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSeek"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatus\/canseek"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkstatus\/canseek"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canSeek"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"]]},"abstract":[{"text":"Represents wether the engine is ready to receive a seek command.","type":"text"}],"metadata":{"modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKStatus(py)canSeek","role":"symbol","title":"canSeek","navigatorTitle":[{"kind":"identifier","text":"canSeek"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSeek"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/automixiq","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"title":"AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus/canSeek":{"type":"topic","role":"symbol","title":"canSeek","url":"\/documentation\/automixiq\/automixsdkstatus\/canseek","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus\/canSeek","abstract":[{"type":"text","text":"Represents wether the engine is ready to receive a seek command."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSeek"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canSeek","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"canSeek","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"canSeek"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"text":"canSeek","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"AutomixSDKStatus","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canSeek\/title","value":"canSeek"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus~1canSeek\/fragments","value":[{"kind":"identifier","text":"canSeek"}]}]}]}