{"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","kind":"typeIdentifier","text":"RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"modules":[{"name":"PacemakerRadio"}],"roleHeading":"Type Method","title":"initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","externalID":"c:objc(cs)RadioSDKObjC(cm)initializeWithConfig:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","text":"RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","kind":"typeIdentifier","text":"RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}]},{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"config","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"typeIdentifier","text":"RadioSDKConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RadioUIDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkobjc\/initialize(with:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/initialize(with:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)","title":"initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","kind":"typeIdentifier","text":"RadioSDKConfig"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"RadioUIDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC":{"abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKObjC"}],"type":"topic","navigatorTitle":[{"text":"RadioSDKObjC","kind":"identifier"}],"title":"RadioSDKObjC","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"abstract":[],"title":"RadioSDKConfig","url":"\/documentation\/pacemakerradio\/radiosdkconfig","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","role":"symbol","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioUIDelegate","kind":"identifier"}],"title":"RadioUIDelegate","navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"title":"TunedMusicCacheDelegate","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"url":"\/documentation\/pacemakerradio\/tunedrestdelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","role":"symbol","type":"topic","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"title":"TunedRestDelegate","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}]}},"variantOverrides":[{"patch":[{"value":"AutomixSDKStatusObserverDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"value":[{"text":"RadioSDKConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"},{"value":"RadioUIDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"RadioUIDelegate"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioUIDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments","op":"replace","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}