{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackPlayPlayed5Secs"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"]]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayplayed5secs"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayplayed5secs"]}],"metadata":{"title":"AutomixSDKPlaybackEventType.trackPlayPlayed5Secs","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackPlayPlayed5Secs","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"AutomixIQ"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKPlaybackEventType@AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","navigatorTitle":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}]},"sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"abstract":[{"type":"text","text":"AutomixSDK play event type"}],"type":"topic","title":"AutomixSDKPlaybackEventType"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType/trackPlayPlayed5Secs":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackPlayPlayed5Secs"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType\/trackPlayPlayed5Secs","url":"\/documentation\/automixiq\/automixsdkplaybackeventtype\/trackplayplayed5secs","title":"AutomixSDKPlaybackEventType.trackPlayPlayed5Secs","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title","op":"replace","value":"AutomixSDKPlaybackEventType"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/title","value":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType~1trackPlayPlayed5Secs\/fragments","value":[{"text":"AutomixSDKPlaybackEventTypeTrackPlayPlayed5Secs","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}