{"metadata":{"modules":[{"name":"PacemakerRadio"}],"title":"removeStatusObserverDelegate(_:)","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDK(im)removeStatusObserverDelegate:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeStatusObserverDelegate:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/removeStatusObserverDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes a status observer delegate"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeStatusObserverDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"statusObserverDelegate","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"statusObserverDelegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate to remove."}]}]}]}],"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdk\/removestatusobserverdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/radiosdk\/removestatusobserverdelegate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","title":"AutomixSDKStatusObserverDelegate","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDK"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDK"}],"kind":"symbol","title":"RadioSDK","url":"\/documentation\/pacemakerradio\/radiosdk","abstract":[{"text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK/removeStatusObserverDelegate(_:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK\/removeStatusObserverDelegate(_:)","type":"topic","abstract":[{"text":"Removes a status observer delegate","type":"text"}],"title":"removeStatusObserverDelegate(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeStatusObserverDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")"}],"url":"\/documentation\/pacemakerradio\/radiosdk\/removestatusobserverdelegate(_:)","navigatorTitle":[{"text":"removeStatusObserverDelegate:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeStatusObserverDelegate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeStatusObserverDelegate:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"statusObserverDelegate"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"name":"statusObserverDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate to remove.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/title","value":"RadioSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/fragments","value":[{"kind":"identifier","text":"RadioSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDK"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1removeStatusObserverDelegate(_:)\/title","value":"removeStatusObserverDelegate:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeStatusObserverDelegate:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK~1removeStatusObserverDelegate(_:)\/fragments"}]}]}