{"kind":"article","abstract":[{"type":"text","text":"What AutomixIQ stores locally"}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Music-Metadata-Database","level":2,"type":"heading","text":"Music Metadata Database"},{"inlineContent":[{"text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the metadata of tracks that have been played for subsequent lookup. This file is called “music.db” and if deleted will be recreated on launch.","type":"text"}],"type":"paragraph"},{"type":"heading","anchor":"Music-Analysis-Database","level":2,"text":"Music Analysis Database"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the Caches Directory, AutomixIQ keeps a light weight sql database to store the analysis data of tracks that have been played for subsequent lookup. This analysis is required to produce beat-matched transitions. This file is called “paralysis.db” and if deleted will be recreated on launch."}]},{"level":2,"anchor":"Playback-Log","text":"Playback Log","type":"heading"},{"inlineContent":[{"text":"AutomixIQ stores offline playback logs for subsequent reporting on a Core Data database, modelled by the following classes:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","type":"reference"}],"type":"paragraph"}]}]},{"anchor":"Transition-Playback-Log","type":"heading","text":"Transition Playback Log","level":2},{"inlineContent":[{"type":"text","text":"AutomixIQ stores offline transition playback logs for subsequent reporting on a Core Data database, modelled by the following classes:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID","isActive":true,"type":"reference"}]}]}]}]}],"metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"PacemakerRadio"}],"title":"Persistency"},"sections":[],"seeAlsoSections":[{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"],"anchor":"Persistency","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Persistency-article"},"variants":[{"paths":["\/documentation\/pacemakerradio\/persistency-article"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/persistency-article"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLog":{"abstract":[],"title":"AutomixSDKTransitionLog","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLog","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLog","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktransitionlog","kind":"symbol","navigatorTitle":[{"text":"AutomixSDKTransitionLog","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLog":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylog","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLog","title":"AutomixSDKPlayLog","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLog"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlayLog","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogID":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylogid","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogID","title":"AutomixSDKPlayLogID","navigatorTitle":[{"text":"AutomixSDKPlayLogID","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlayLogID"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogAttributes":{"url":"\/documentation\/pacemakerradio\/automixsdktransitionlogattributes","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTransitionLogAttributes"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogAttributes","title":"AutomixSDKTransitionLogAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogAttributes"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTransitionLogID":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktransitionlogid","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTransitionLogID","title":"AutomixSDKTransitionLogID","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTransitionLogID"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKTransitionLogID","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackEventType":{"abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackeventtype","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType","title":"AutomixSDKPlaybackEventType","navigatorTitle":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlayLogAttributes":{"abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylogattributes","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlayLogAttributes","title":"AutomixSDKPlayLogAttributes","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKPlayLogAttributes"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"replace","value":[{"title":"Persistency","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackEventType"],"anchor":"Persistency","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/title","value":"AutomixSDKPlaybackEventType"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackEventType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}