{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"seeAlsoSections":[{"title":"Errors","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Errors-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"],"generated":true,"anchor":"Errors"}],"metadata":{"modules":[{"name":"PacemakerRadio"}],"title":"sdkError(code:)","externalID":"s:14PacemakerRadio8sdkError4codes0D0_pAA19AutomixSDKErrorCodeO_tF","symbolKind":"func","roleHeading":"Function","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"text":"AutomixSDKErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/sdkError(code:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sdkError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode","text":"AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/sdkerror(code:)"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","kind":"symbol","title":"AutomixSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/sdkError(code:)":{"type":"topic","role":"symbol","title":"sdkError(code:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode","kind":"typeIdentifier","text":"AutomixSDKErrorCode"},{"text":") -> ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/sdkError(code:)","url":"\/documentation\/pacemakerradio\/sdkerror(code:)","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Errors-article":{"type":"topic","title":"Errors","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Errors-article","role":"article","url":"\/documentation\/pacemakerradio\/errors-article","abstract":[{"type":"text","text":"What errors the PacemakerRadio player can issue to help with player integration"}],"kind":"article"}},"variantOverrides":[{"patch":[{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}