{"metadata":{"externalID":"c:objc(cs)RadioSDKObjC","symbolKind":"class","title":"RadioSDKObjC","roleHeading":"Class","modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKObjC","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKObjC","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkobjc"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/add(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/endRadioSession()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getLiveShows(withLimit:start:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/isAudioDeviceActive()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/play(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/radioUIViewController()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/remove(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/reportMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/reportUser(withIdentifier:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/startRadioSession(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/stopEngine()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialised()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/instance()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/internetAvailable()"],"title":"Type Methods"}],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK"],"title":"RadioSDK singleton","generated":true,"anchor":"RadioSDK-singleton"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","text":"RadioSDKConfig","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/initialize(with:tuneddelegate:statusdelegate:radiouidelegate:musiccachedelegate:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","kind":"symbol","title":"initialize(with:tunedDelegate:statusDelegate:radioUIDelegate:musicCacheDelegate:completion:)","role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/radioUIViewController()":{"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/radiouiviewcontroller()","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/radioUIViewController()","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIViewController"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"title":"radioUIViewController()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/reportMixtape(withIdentifier:completion:)":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/reportmixtape(withidentifier:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reportMixtape","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/reportMixtape(withIdentifier:completion:)","abstract":[],"title":"reportMixtape(withIdentifier:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/startradiosession(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","role":"symbol","title":"startRadioSession(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRadioSession"},{"text":"(","kind":"text"},{"text":"withIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"kind":"externalParam","text":"seconds"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"contextId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","role":"collection"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/getAutomixStreamingDelegate()":{"type":"topic","abstract":[],"title":"getAutomixStreamingDelegate()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAutomixStreamingDelegate"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"}],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/getautomixstreamingdelegate()","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/internetAvailable()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/internetAvailable()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internetAvailable"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/internetavailable()","role":"symbol","abstract":[],"kind":"symbol","title":"internetAvailable()","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/stopEngine()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopEngine","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/stopEngine()","title":"stopEngine()","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/stopengine()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/initialised()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialised()","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/initialised()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialised"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"role":"symbol","title":"initialised()","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"notifyFollowers","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUserIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"objectType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"objectId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/notifyfollowers(withuseridentifier:title:body:objecttype:objectid:completion:)","role":"symbol","title":"notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/notifyFollowers(withUserIdentifier:title:body:objectType:objectId:completion:)"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/SH":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/play(completion:)":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/play(completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/play(completion:)","abstract":[],"title":"play(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/setMusicCacheDelegate(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMusicCacheDelegate","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/setMusicCacheDelegate(_:)","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/setmusiccachedelegate(_:)","title":"setMusicCacheDelegate(_:)","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC":{"navigatorTitle":[{"text":"RadioSDKObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc","abstract":[],"title":"RadioSDKObjC","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKObjC"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/endRadioSession()":{"title":"endRadioSession()","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/endRadioSession()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"endRadioSession","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/endradiosession()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/getLiveShows(withLimit:start:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getLiveShows","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withLimit"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKList","text":"AutomixSDKList"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getLiveShows(withLimit:start:completion:)","title":"getLiveShows(withLimit:start:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/getliveshows(withlimit:start:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/reportUser(withIdentifier:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/reportUser(withIdentifier:completion:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/reportuser(withidentifier:completion:)","abstract":[],"role":"symbol","kind":"symbol","title":"reportUser(withIdentifier:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"reportUser","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/remove(_:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/remove(_:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/remove(_:)","role":"symbol","title":"remove(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/isAudioDeviceActive()":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/isaudiodeviceactive()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAudioDeviceActive"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/isAudioDeviceActive()","abstract":[],"title":"isAudioDeviceActive()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)":{"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/getaudiodata(withframes:numberofchannels:fadestate:audiopcmbuffer:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAudioData"},{"text":"(","kind":"text"},{"text":"withFrames","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfChannels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"fadeState"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"audioPCMBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"kind":"symbol","title":"getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/startRadioSession(completion:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/startRadioSession(completion:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/startradiosession(completion:)","role":"symbol","title":"startRadioSession(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRadioSession"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?, ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDK":{"abstract":[{"type":"text","text":"RadioSDK represents the Radio SDK and exposes all its functionality. It follows a Singleton pattern."}],"url":"\/documentation\/pacemakerradio\/radiosdk","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDK","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RadioSDK","kind":"identifier"}],"title":"RadioSDK","navigatorTitle":[{"text":"RadioSDK","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/instance()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/instance()","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/instance()","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"instance","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"RadioSDKObjC","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)RadioSDKObjC"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","title":"instance()","abstract":[]},"doc://org.cocoapods.PacemakerRadio/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/add(_:)":{"title":"add(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/add(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/add(_:)","abstract":[]},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/joinLiveMixtape(withIdentifier:completion:)":{"role":"symbol","abstract":[],"title":"joinLiveMixtape(withIdentifier:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinLiveMixtape"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/joinlivemixtape(withidentifier:completion:)"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/title","value":"RadioSDK"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/fragments","value":[{"kind":"identifier","text":"RadioSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDK\/navigatorTitle","value":[{"text":"RadioSDK","kind":"identifier"}]}]}]}