{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"PacemakerRadio"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedRestTokenExpired","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"tunedUserId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"refreshToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"tokenType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"kind":"text","text":": "},{"text":"TunedAuthenticationResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)TunedAuthenticationResponse"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"symbolKind":"method","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","externalID":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate(im)tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedRestTokenExpired","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"refreshToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)TunedAuthenticationResponse"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device."}],"type":"paragraph"}],"name":"deviceIdentifierForVendor"},{"content":[{"inlineContent":[{"text":"The ISO2 code of the country the device is located.","type":"text"}],"type":"paragraph"}],"name":"countryCode"},{"content":[{"inlineContent":[{"text":"The user’s id within the Tuned Global backend.","type":"text"}],"type":"paragraph"}],"name":"tunedUserId"},{"name":"oldAccessToken","content":[{"type":"paragraph","inlineContent":[{"text":"The expired access token.","type":"text"}]}]},{"name":"refreshToken","content":[{"type":"paragraph","inlineContent":[{"text":"The refresh token.","type":"text"}]}]},{"name":"tokenType","content":[{"inlineContent":[{"text":"The token type.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]}],"name":"completion"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/tunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/tunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)"]}],"sections":[],"abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate"]]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"kind":"symbol","abstract":[{"type":"text","text":"TunedAuthenticationResponse models the response of a Tuned OAuth request"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TunedAuthenticationResponse","kind":"identifier"}],"title":"TunedAuthenticationResponse","navigatorTitle":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"url":"\/documentation\/pacemakerradio\/tunedrestdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","title":"TunedRestDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TunedRestDelegate"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate\/tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","abstract":[{"type":"text","text":"Called by AutomixIQ when initialised against a Tuned Global backend or when its access token has expired."}],"url":"\/documentation\/pacemakerradio\/tunedrestdelegate\/tunedresttokenexpired(deviceidentifierforvendor:countrycode:tuneduserid:oldaccesstoken:refreshtoken:tokentype:completion:)","title":"tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)","navigatorTitle":[{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tunedRestTokenExpired","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceIdentifierForVendor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedUserId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"oldAccessToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"refreshToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)TunedAuthenticationResponse","text":"TunedAuthenticationResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tunedUserId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceIdentifierForVendor"},{"kind":"text","text":" "},{"text":"countryCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"countryCode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tunedUserId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tunedUserId"},{"kind":"text","text":" "},{"text":"oldAccessToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"oldAccessToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"refreshToken:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"refreshToken","kind":"internalParam"},{"kind":"text","text":" "},{"text":"tokenType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tokenType"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)TunedAuthenticationResponse"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"deviceIdentifierForVendor","content":[{"inlineContent":[{"type":"text","text":"The unique identifier of the device."}],"type":"paragraph"}]},{"name":"countryCode","content":[{"type":"paragraph","inlineContent":[{"text":"The ISO2 code of the country the device is located.","type":"text"}]}]},{"name":"tunedUserId","content":[{"inlineContent":[{"text":"The user’s id within the Tuned Global backend.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The expired access token."}],"type":"paragraph"}],"name":"oldAccessToken"},{"name":"refreshToken","content":[{"inlineContent":[{"type":"text","text":"The refresh token."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The token type."}],"type":"paragraph"}],"name":"tokenType"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"TunedAuthenticationResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments","value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle","op":"replace"},{"value":"TunedRestDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"op":"replace"},{"op":"replace","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/title","value":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tunedRestTokenExpiredWithDeviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate~1tunedRestTokenExpired(deviceIdentifierForVendor:countryCode:tunedUserId:oldAccessToken:refreshToken:tokenType:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}