{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotcreatechannellayout"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotcreatechannellayout"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotCreateChannelLayout","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}],"symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"role":"symbol","modules":[{"name":"PacemakerRadio"}],"title":"AutomixSDKErrorCode.cannotCreateChannelLayout","roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode","title":"AutomixSDKErrorCode","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotCreateChannelLayout":{"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotcreatechannellayout","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cannotCreateChannelLayout"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotCreateChannelLayout","role":"symbol","abstract":[],"title":"AutomixSDKErrorCode.cannotCreateChannelLayout"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeCannotCreateChannelLayout"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle"},{"value":"AutomixSDKErrorCodeCannotCreateChannelLayout","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/title"},{"op":"replace","value":[{"text":"AutomixSDKErrorCodeCannotCreateChannelLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotCreateChannelLayout\/fragments"}]}]}