{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variables","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","text":"AutomixSDKStatus"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"variables","content":[{"inlineContent":[{"text":"A list of AutomixSDKStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised.","type":"text"}],"type":"paragraph"}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Called when the status of AutomixIQ changes"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate"]]},"metadata":{"symbolKind":"method","externalID":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate(im)statusChangedWithVariables:status:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"variables","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"], "},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutomixSDKStatus","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"statusChangedWithVariables:status:"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","roleHeading":"Instance Method","required":true,"title":"statusChanged(variables:status:)"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate/statusChanged(variables:status:)":{"abstract":[{"text":"Called when the status of AutomixIQ changes","type":"text"}],"kind":"symbol","role":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate\/statusChanged(variables:status:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"statusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"variables"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","kind":"typeIdentifier","text":"AutomixSDKStatus"},{"text":")","kind":"text"}],"title":"statusChanged(variables:status:)","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate\/statuschanged(variables:status:)","navigatorTitle":[{"kind":"identifier","text":"statusChangedWithVariables:status:"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"kind":"symbol","title":"AutomixSDKStatusObserverDelegate","role":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"title":"AutomixSDKStatus","url":"\/documentation\/pacemakerradio\/automixsdkstatus","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatus"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"statusChangedWithVariables:status:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"statusChangedWithVariables:status:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"statusChangedWithVariables:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"variables"},{"text":" ","kind":"text"},{"text":"status:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","text":"AutomixSDKStatus","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"variables","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of AutomixSDKStatusVariable that changed since last time this method was called, or since AutomixIQ was initialised."}]}]},{"name":"status","content":[{"inlineContent":[{"type":"text","text":"The current status of AutomixIQ"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/title","value":"statusChangedWithVariables:status:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate~1statusChanged(variables:status:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"statusChangedWithVariables:status:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKStatus","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]}]}]}