{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"uiConfig","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"title":"uiConfig","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiConfig","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"}],"roleHeading":"Instance Property","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)uiConfig","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/uiConfig","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/uiconfig"]},{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/uiconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiConfig","kind":"identifier"},{"kind":"text","text":": "},{"text":"RadioSDKUIConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"}]}]}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"abstract":[],"title":"RadioSDKConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkconfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/uiConfig":{"type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/uiconfig","kind":"symbol","title":"uiConfig","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiConfig","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/uiConfig","abstract":[],"navigatorTitle":[{"text":"uiConfig","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"uiConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"uiConfig","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"RadioSDKUIConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"uiConfig"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"RadioSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1uiConfig\/title","value":"uiConfig"},{"value":[{"kind":"identifier","text":"uiConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1uiConfig\/fragments"},{"value":"RadioSDKUIConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title"},{"value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}