{"metadata":{"title":"AutomixSDKErrorCode.addTrackOutOfBounds","modules":[{"name":"AutomixIQ"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addTrackOutOfBounds","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeAddTrackOutOfBounds","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeAddTrackOutOfBounds"}]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackOutOfBounds","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/addtrackoutofbounds"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/addtrackoutofbounds"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrackOutOfBounds"}]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDK error codes"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","url":"\/documentation\/automixiq\/automixsdkerrorcode","type":"topic","title":"AutomixSDKErrorCode"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/addTrackOutOfBounds":{"type":"topic","abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/addtrackoutofbounds","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/addTrackOutOfBounds","title":"AutomixSDKErrorCode.addTrackOutOfBounds","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"addTrackOutOfBounds"}],"navigatorTitle":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","url":"\/documentation\/automixiq","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"AutomixSDKErrorCodeAddTrackOutOfBounds","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeAddTrackOutOfBounds","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackOutOfBounds\/title","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeAddTrackOutOfBounds","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1addTrackOutOfBounds\/fragments","op":"replace"}]}]}