{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionduration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/rightTransitionDuration"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}]}]}],"abstract":[{"text":"The duration of the right transition, in seconds","type":"text"}],"metadata":{"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDKWaveformModel(py)rightTransitionDuration","navigatorTitle":[{"kind":"identifier","text":"rightTransitionDuration"}],"title":"rightTransitionDuration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AutomixIQ"}]},"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"url":"\/documentation\/automixiq","title":"AutomixIQ","role":"collection","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel":{"kind":"symbol","role":"symbol","title":"AutomixSDKWaveformModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel","url":"\/documentation\/automixiq\/automixsdkwaveformmodel","abstract":[{"type":"text","text":"AutomixSDKWaveformModel models the waveform of a track."}],"navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformModel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKWaveformModel/rightTransitionDuration":{"navigatorTitle":[{"text":"rightTransitionDuration","kind":"identifier"}],"title":"rightTransitionDuration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightTransitionDuration"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKWaveformModel\/rightTransitionDuration","url":"\/documentation\/automixiq\/automixsdkwaveformmodel\/righttransitionduration","role":"symbol","abstract":[{"type":"text","text":"The duration of the right transition, in seconds"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rightTransitionDuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"rightTransitionDuration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTransitionDuration"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"AutomixSDKWaveformModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/title","op":"replace"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/fragments"},{"value":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel~1rightTransitionDuration\/title","value":"rightTransitionDuration"},{"value":[{"kind":"identifier","text":"rightTransitionDuration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKWaveformModel~1rightTransitionDuration\/fragments"}]}]}