{"abstract":[{"text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the entire unencrypted track.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the track that the AutomixIQ SDK is streaming."}]}],"name":"trackId"}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"the entire unencrypted track","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"modules":[{"name":"AutomixIQ"}],"navigatorTitle":[{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"required":true,"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider(im)syncGetCachedTrackWithTrackId:","title":"syncGetCachedTrack(trackId:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgetcachedtrack(trackid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgetcachedtrack(trackid:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetCachedTrack(trackId:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider":{"type":"topic","title":"AutomixSDKCachedMusicProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider","role":"symbol","kind":"symbol","abstract":[{"text":"AutomixSDKCachedMusicProvider protocol defines the methods to be implemented by a class tasked with storing and providing cached track data","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/syncGetCachedTrack(trackId:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetCachedTrack(trackId:)","title":"syncGetCachedTrack(trackId:)","kind":"symbol","abstract":[{"text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the entire unencrypted track.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgetcachedtrack(trackid:)","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"syncGetCachedTrackWithTrackId:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/title","value":"AutomixSDKCachedMusicProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/fragments","value":[{"text":"AutomixSDKCachedMusicProvider","kind":"identifier"}],"op":"replace"},{"value":"syncGetCachedTrackWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetCachedTrack(trackId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetCachedTrack(trackId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}]}]}]}