{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetTrackMetadata(trackId:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"AutomixIQ"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadata"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"syncGetTrackMetadata(trackId:)","required":true,"navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider(im)syncGetTrackMetadataWithTrackId:","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the required data from an on-device cache or any other synchronous method","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetTrackMetadata"},{"kind":"text","text":"("},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","text":"AutomixSDKTrackModel"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the track that the AutomixIQ SDK is streaming."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"the metadata of the track","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgettrackmetadata(trackid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgettrackmetadata(trackid:)"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider":{"type":"topic","title":"AutomixSDKCachedMusicProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider","role":"symbol","kind":"symbol","abstract":[{"text":"AutomixSDKCachedMusicProvider protocol defines the methods to be implemented by a class tasked with storing and providing cached track data","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKTrackModel":{"type":"topic","url":"\/documentation\/automixiq\/automixsdktrackmodel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"title":"AutomixSDKTrackModel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/syncGetTrackMetadata(trackId:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetTrackMetadata"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","title":"syncGetTrackMetadata(trackId:)","abstract":[{"type":"text","text":"Called by the AutomixIQ SDK before attempting to download a track to give an opportunity to retrieve the required data from an on-device cache or any other synchronous method"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/syncGetTrackMetadata(trackId:)","required":true,"url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/syncgettrackmetadata(trackid:)","navigatorTitle":[{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"syncGetTrackMetadataWithTrackId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"AutomixSDKTrackModel","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/title","value":"AutomixSDKCachedMusicProvider","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}]},{"op":"replace","value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/title"},{"op":"replace","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKTrackModel\/fragments"},{"value":"syncGetTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetTrackMetadata(trackId:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1syncGetTrackMetadata(trackId:)\/fragments"}]}]}