{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/trackfinisheddownloading(trackid:data:)"]},{"paths":["\/documentation\/automixiq\/automixsdkcachedmusicprovider\/trackfinisheddownloading(trackid:data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackFinishedDownloading","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The trackId of the asset in Tuned Global’s backend."}],"type":"paragraph"}]},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"text":"The track data.","type":"text"}]}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackFinishedDownloading(trackId:data:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKCachedMusicProvider(im)trackFinishedDownloadingWithTrackId:data:","title":"trackFinishedDownloading(trackId:data:)","roleHeading":"Instance Method","modules":[{"name":"AutomixIQ"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackFinishedDownloading","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"trackFinishedDownloadingWithTrackId:data:","kind":"identifier"}],"required":true,"symbolKind":"method"},"sections":[],"abstract":[{"text":"Called by the AutomixIQ SDK when a track has been fully downloaded.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider/trackFinishedDownloading(trackId:data:)":{"abstract":[{"text":"Called by the AutomixIQ SDK when a track has been fully downloaded.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider\/trackFinishedDownloading(trackId:data:)","url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider\/trackfinisheddownloading(trackid:data:)","navigatorTitle":[{"text":"trackFinishedDownloadingWithTrackId:data:","kind":"identifier"}],"title":"trackFinishedDownloading(trackId:data:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackFinishedDownloading","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"required":true},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKCachedMusicProvider":{"type":"topic","title":"AutomixSDKCachedMusicProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKCachedMusicProvider","url":"\/documentation\/automixiq\/automixsdkcachedmusicprovider","role":"symbol","kind":"symbol","abstract":[{"text":"AutomixSDKCachedMusicProvider protocol defines the methods to be implemented by a class tasked with storing and providing cached track data","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"trackFinishedDownloadingWithTrackId:data:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"trackFinishedDownloadingWithTrackId:data:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"trackFinishedDownloadingWithTrackId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"trackId"},{"text":" ","kind":"text"},{"text":"data:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackFinishedDownloading(trackId:data:)\/title","value":"trackFinishedDownloadingWithTrackId:data:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider~1trackFinishedDownloading(trackId:data:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"trackFinishedDownloadingWithTrackId:data:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/title","op":"replace","value":"AutomixSDKCachedMusicProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKCachedMusicProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKCachedMusicProvider"}]}]}]}