{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"AutomixSDKErrorCode.cannotRestoreAudioSession","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"externalID":"c:@M@PacemakerRadio@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotRestoreAudioSession","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRestoreAudioSession"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotrestoreaudiosession"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotrestoreaudiosession"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode":{"kind":"symbol","type":"topic","title":"AutomixSDKErrorCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkerrorcode"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKErrorCode/cannotRestoreAudioSession":{"type":"topic","title":"AutomixSDKErrorCode.cannotRestoreAudioSession","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKErrorCode\/cannotRestoreAudioSession","url":"\/documentation\/pacemakerradio\/automixsdkerrorcode\/cannotrestoreaudiosession","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotRestoreAudioSession","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cannotRestoreAudioSession","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"AutomixSDKErrorCodeCannotRestoreAudioSession","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/title","value":"AutomixSDKErrorCode"},{"op":"replace","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode\/navigatorTitle","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]},{"value":"AutomixSDKErrorCodeCannotRestoreAudioSession","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKErrorCode~1cannotRestoreAudioSession\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotRestoreAudioSession"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}