{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"},"seeAlsoSections":[{"title":"Initialization","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/initialise(apikey:tuneddelegate:statusdelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"]},{"paths":["\/documentation\/automixiq\/automixsdk\/initialise(apikey:tuneddelegate:statusdelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","kind":"identifier"}],"title":"initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(cm)initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TunedRestDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"AutomixIQ"}],"symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":"?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")? = nil)"}]}]},{"parameters":[{"name":"apiKey","content":[{"inlineContent":[{"type":"text","text":"The AutomixIQ API Key"}],"type":"paragraph"}]},{"name":"tunedDelegate","content":[{"type":"paragraph","inlineContent":[{"text":"The delegate in charge of feeding and renewing Tuned Global OAuth2 access tokens. See TunedRestDelegate.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of updating any UI with status updates from AutomixIQ. See AutomixSDKStatusObserverDelegate."}],"type":"paragraph"}],"name":"statusDelegate"},{"content":[{"inlineContent":[{"type":"text","text":"The ISO2 country code the device is located in.."}],"type":"paragraph"}],"name":"countryCode"},{"content":[{"inlineContent":[{"text":"Tuned Global’s store ID.","type":"text"}],"type":"paragraph"}],"name":"storeId"},{"content":[{"inlineContent":[{"text":"Tuned Global’s Application ID.","type":"text"}],"type":"paragraph"}],"name":"applicationId"},{"name":"musicCacheDelegate","content":[{"inlineContent":[{"type":"text","text":"The delegate in charge of saving and feeding in cached music to and from AutomixIQ"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Code to be executed upon completing the asynchronous request.","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against a Tuned Global backend"},{"text":" ","type":"text"},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"title":"TunedMusicCacheDelegate","url":"\/documentation\/automixiq\/tunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixsdk","role":"symbol","title":"AutomixSDK","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDK","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"role":"symbol","title":"AutomixSDKStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)":{"role":"symbol","navigatorTitle":[{"text":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","kind":"identifier"}],"title":"initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"apiKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":"?, "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TunedMusicCacheDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","abstract":[{"type":"text","text":"Initialiser for AutomixIQ to work against a Tuned Global backend"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feed OAuth2 access tokens to the Tuned Global APIs, as well as the ISO2 country code the device runs from and the Tuned Global Store ID."}],"url":"\/documentation\/automixiq\/automixsdk\/initialise(apikey:tuneddelegate:statusdelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)":{"role":"symbol","navigatorTitle":[{"text":"initialiseWithApiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","kind":"identifier"}],"title":"initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"streamingDelegate"},{"text":": ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"countryCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)","url":"\/documentation\/automixiq\/automixsdk\/initialise(apikey:streamingdelegate:statusdelegate:countrycode:storeid:applicationid:completion:)","abstract":[{"text":"Initialiser for AutomixIQ to work against any custom set of APIs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method takes in delegates to update the UI and feeds all data and metadata the AutomixIQ needs."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"title":"TunedRestDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)"],"generated":true,"title":"Initialization"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initialiseWithApiKey:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"apiKey","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"tunedDelegate:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"id<TunedRestDelegate>"},{"kind":"text","text":") "},{"text":"tunedDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDelegate:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","text":"id<AutomixSDKStatusObserverDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"statusDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"countryCode:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"countryCode"},{"kind":"text","text":" "},{"text":"storeId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"storeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"applicationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"musicCacheDelegate:"},{"text":"(","kind":"text"},{"text":"id<TunedMusicCacheDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"text":") ","kind":"text"},{"text":"musicCacheDelegate","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"op":"replace","value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments"},{"value":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initialiseWithApiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(apiKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)\/title","value":"initialiseWithApiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialise(apiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"initialiseWithApiKey:streamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","op":"replace"}]}]}