{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)"],"title":"Waveform Data access","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/setwaveformpointspertrack(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdk\/setwaveformpointspertrack(_:)"]}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setWaveformPointsPerTrack"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)setWaveformPointsPerTrack:","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","title":"setWaveformPointsPerTrack(_:)","navigatorTitle":[{"text":"setWaveformPointsPerTrack:","kind":"identifier"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Sets the resolution of the waveform data for a track"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setWaveformPointsPerTrack"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"waveformPointsPerTrack","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"waveformPointsPerTrack","content":[{"type":"paragraph","inlineContent":[{"text":"The number of points representing a waveform for a track, maximum of 1024","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setWaveformPointsPerTrack(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","role":"symbol","navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"title":"AutomixSDK","abstract":[{"text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDK"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","type":"topic","kind":"symbol","url":"\/documentation\/automixiq","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setWaveformPointsPerTrack(_:)":{"type":"topic","title":"setWaveformPointsPerTrack(_:)","abstract":[{"type":"text","text":"Sets the resolution of the waveform data for a track"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/setwaveformpointspertrack(_:)","navigatorTitle":[{"text":"setWaveformPointsPerTrack:","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setWaveformPointsPerTrack(_:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/waveformDataForTrack(identifier:applyTransitions:)":{"type":"topic","title":"waveformDataForTrack(identifier:applyTransitions:)","abstract":[{"text":"Gets the waveform data for a track.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"applyTransitions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> [[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]]?"}],"url":"\/documentation\/automixiq\/automixsdk\/waveformdatafortrack(identifier:applytransitions:)","navigatorTitle":[{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyTransitions:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"setWaveformPointsPerTrack:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setWaveformPointsPerTrack:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Waveform Data access","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/waveformDataForTrack(identifier:applyTransitions:)"],"generated":true}],"op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"setWaveformPointsPerTrack:"},{"kind":"text","text":"("},{"text":"int32_t","preciseIdentifier":"c:@T@int32_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"waveformPointsPerTrack","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"AutomixSDK","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments","op":"replace","value":[{"text":"AutomixSDK","kind":"identifier"}]},{"value":"setWaveformPointsPerTrack:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setWaveformPointsPerTrack(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setWaveformPointsPerTrack(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setWaveformPointsPerTrack:","kind":"identifier"}]},{"value":"waveformDataForTrackWithIdentifier:applyTransitions:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1waveformDataForTrack(identifier:applyTransitions:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1waveformDataForTrack(identifier:applyTransitions:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"waveformDataForTrackWithIdentifier:applyTransitions:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}