{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setFilterExplicit(filterExplicit:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the filter explicit lyrics flag."},{"text":" ","type":"text"},{"type":"text","text":"When set to on, AutomixIQ will skip over the tracks that have the explicit content flag set in their metadata by mixing the currently playing track with the first available non-explicit track in the queue."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdk\/setfilterexplicit(filterexplicit:completion:)"]},{"paths":["\/documentation\/automixiq\/automixsdk\/setfilterexplicit(filterexplicit:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFilterExplicit"},{"text":"(","kind":"text"},{"text":"filterExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request."}],"type":"paragraph"}]}]}],"sections":[],"seeAlsoSections":[{"title":"Settings","generated":true,"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)"]}],"metadata":{"modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","symbolKind":"method","title":"setFilterExplicit(filterExplicit:completion:)","navigatorTitle":[{"text":"setFilterExplicitWithFilterExplicit:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFilterExplicit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"filterExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"externalID":"c:@M@AutomixIQ@objc(cs)AutomixSDK(im)setFilterExplicitWithFilterExplicit:completion:","role":"symbol"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setFilterExplicit(filterExplicit:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setFilterExplicit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filterExplicit"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setFilterExplicit(filterExplicit:completion:)","navigatorTitle":[{"kind":"identifier","text":"setFilterExplicitWithFilterExplicit:completion:"}],"url":"\/documentation\/automixiq\/automixsdk\/setfilterexplicit(filterexplicit:completion:)","type":"topic","abstract":[{"text":"Sets the filter explicit lyrics flag.","type":"text"},{"text":" ","type":"text"},{"text":"When set to on, AutomixIQ will skip over the tracks that have the explicit content flag set in their metadata by mixing the currently playing track with the first available non-explicit track in the queue.","type":"text"}],"title":"setFilterExplicit(filterExplicit:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK":{"navigatorTitle":[{"text":"AutomixSDK","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdk","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK","type":"topic","title":"AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setVinylStartStopEnabled(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVinylStartStopEnabled"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)","navigatorTitle":[{"kind":"identifier","text":"setVinylStartStopEnabled:completion:"}],"url":"\/documentation\/automixiq\/automixsdk\/setvinylstartstopenabled(_:completion:)","type":"topic","abstract":[{"text":"Enables \/ Disables vinyl pause sound effect.","type":"text"}],"title":"setVinylStartStopEnabled(_:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/setPreferredTransitionDurationSeconds(_:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds"},{"kind":"text","text":"(Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)","navigatorTitle":[{"kind":"identifier","text":"setPreferredTransitionDurationSeconds:completion:"}],"url":"\/documentation\/automixiq\/automixsdk\/setpreferredtransitiondurationseconds(_:completion:)","abstract":[{"text":"Sets AutomixIQ’s preferred transition duration - transitions will not be exactly this duration but AutomixIQ will favour transitions with duration close to this one.","type":"text"},{"text":" ","type":"text"},{"text":"Setting it to 0 disables this hint and allows the engine to select the transition duration based on trained genre-based transition data.","type":"text"}],"type":"topic","title":"setPreferredTransitionDurationSeconds(_:completion:)","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"kind":"symbol","title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"setFilterExplicitWithFilterExplicit:completion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setFilterExplicitWithFilterExplicit:completion:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setPreferredTransitionDurationSeconds(_:completion:)","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/setVinylStartStopEnabled(_:completion:)"],"generated":true,"title":"Settings"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setFilterExplicitWithFilterExplicit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"filterExplicit"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setFilterExplicit(filterExplicit:completion:)\/title","op":"replace","value":"setFilterExplicitWithFilterExplicit:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setFilterExplicit(filterExplicit:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setFilterExplicitWithFilterExplicit:completion:","kind":"identifier"}]},{"value":"AutomixSDK","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDK"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK\/fragments"},{"value":"setVinylStartStopEnabled:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setVinylStartStopEnabled(_:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setVinylStartStopEnabled(_:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVinylStartStopEnabled:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setPreferredTransitionDurationSeconds(_:completion:)\/title","value":"setPreferredTransitionDurationSeconds:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1setPreferredTransitionDurationSeconds(_:completion:)\/fragments","op":"replace"}]}]}