{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkobjc"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKObjC"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"symbolKind":"class","externalID":"c:objc(cs)AutomixSDKObjC","modules":[{"name":"PacemakerRadio"}],"title":"AutomixSDKObjC"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKObjC","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/on"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/add(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/addTrack(withIdentifier:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/addTracks(withIdentifiers:metadata:index:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOff(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOn(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixStatus()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/back(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/clearCache(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/getAutomixStreamingDelegate()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/isAudioDeviceActive()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/largeFontSize()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/loopPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/mediumFontName()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/moveTrack(at:to:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/next(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/pause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/placeholderWaveformDataForTrack(withIdentifier:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/play(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/playTrackToEndThenPause(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/previous(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/radioUIViewController()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/remove(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/removeTrack(at:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/reorderTracks(withNewOrder:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/resetPlaylistToEmpty(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/seek(toSeconds:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setAutomixPlaySpeed(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setAutomixVolumeNormalised(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setFilterExplicit(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setMusicCacheDelegate(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setMuteOn(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setPreferredTransitionDurationSeconds(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setReplayOn(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setVinylStartStopEnabled(_:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setWaveformPointsPerTrack(_:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/skipToTrack(at:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/stopEngine()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/stopLoopingPlayingTrack(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/terminate()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/toggleMute(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/toggleReplay(completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixSDKError(withCode:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/errorDescription(withCode:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialised()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/instance()","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/internetAvailable()"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"seeAlsoSections":[{"generated":true,"anchor":"AutomixIQ","title":"AutomixIQ","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK"]}],"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)":{"title":"waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/waveformdatafortrack(withidentifier:applyentertransition:applyexittransition:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"waveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"applyEnterTransition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applyExitTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyEnterTransition:applyExitTransition:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/errorDescription(withCode:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/errorDescription(withCode:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":"("},{"text":"withCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/errordescription(withcode:)","title":"errorDescription(withCode:)"},"doc://org.cocoapods.PacemakerRadio/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/back(completion:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/back(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/back(completion:)","kind":"symbol","title":"back(completion:)","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/radioUIViewController()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/radioUIViewController()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIViewController"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/radiouiviewcontroller()","title":"radioUIViewController()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/getAutomixStreamingDelegate()":{"title":"getAutomixStreamingDelegate()","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/getautomixstreamingdelegate()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"kind":"text","text":"() -> any "},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/getAutomixStreamingDelegate()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/add(_:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/add(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"add","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/add(_:)","title":"add(_:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/placeholderWaveformDataForTrack(withIdentifier:)":{"title":"placeholderWaveformDataForTrack(withIdentifier:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/placeholderwaveformdatafortrack(withidentifier:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"placeholderWaveformDataForTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"text":"AutomixSDKWaveformModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/placeholderWaveformDataForTrack(withIdentifier:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setAutomixPlaySpeed(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setAutomixPlaySpeed(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setAutomixPlaySpeed"},{"kind":"text","text":"("},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setautomixplayspeed(_:completion:)","title":"setAutomixPlaySpeed(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/moveTrack(at:to:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/moveTrack(at:to:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"moveTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":", "},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/movetrack(at:to:completion:)","title":"moveTrack(at:to:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/toggleMute(completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/toggleMute(completion:)","abstract":[],"title":"toggleMute(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/togglemute(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toggleMute"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC":{"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKObjC","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"type":"topic","title":"AutomixSDKObjC","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/loopPlayingTrack(completion:)":{"role":"symbol","abstract":[],"title":"loopPlayingTrack(completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopPlayingTrack"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/loopPlayingTrack(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/loopplayingtrack(completion:)"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/next(completion:)":{"role":"symbol","abstract":[],"title":"next(completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"next","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/next(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/next(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setPreferredTransitionDurationSeconds(_:completion:)":{"role":"symbol","type":"topic","title":"setPreferredTransitionDurationSeconds(_:completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setpreferredtransitiondurationseconds(_:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setPreferredTransitionDurationSeconds(_:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredTransitionDurationSeconds"},{"text":"(","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setWaveformPointsPerTrack(_:)":{"abstract":[],"title":"setWaveformPointsPerTrack(_:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setwaveformpointspertrack(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setWaveformPointsPerTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setWaveformPointsPerTrack(_:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/seek(toSeconds:completion:)":{"role":"symbol","type":"topic","title":"seek(toSeconds:completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/seek(toseconds:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/seek(toSeconds:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"seek","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toSeconds"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/previous(completion:)":{"abstract":[],"title":"previous(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/previous(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previous"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/previous(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"role":"symbol","type":"topic","title":"loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/loadtracks(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/loadTracks(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadTracks","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withIdentifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"playTrackIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"contextType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/isAudioDeviceActive()":{"role":"symbol","type":"topic","title":"isAudioDeviceActive()","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/isaudiodeviceactive()","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/isAudioDeviceActive()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAudioDeviceActive"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixIQ-article":{"kind":"article","url":"\/documentation\/pacemakerradio\/automixiq-article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixIQ-article","role":"article","type":"topic","title":"AutomixIQ","abstract":[{"type":"text","text":"Availablity of underlying technologies and APIs."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setMusicCacheDelegate(_:)":{"abstract":[],"title":"setMusicCacheDelegate(_:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setmusiccachedelegate(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMusicCacheDelegate"},{"text":"((any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setMusicCacheDelegate(_:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/waveformDataForTrack(withIdentifier:applyTransitions:)":{"role":"symbol","type":"topic","title":"waveformDataForTrack(withIdentifier:applyTransitions:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/waveformdatafortrack(withidentifier:applytransitions:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/waveformDataForTrack(withIdentifier:applyTransitions:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"waveformDataForTrack","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applyTransitions"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKWaveformModel","text":"AutomixSDKWaveformModel"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/resetPlaylistToEmpty(completion:)":{"abstract":[],"title":"resetPlaylistToEmpty(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/resetplaylisttoempty(completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetPlaylistToEmpty","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/resetPlaylistToEmpty(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)":{"role":"symbol","type":"topic","title":"initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/initialise(with:tuneddelegate:statusdelegate:musiccachedelegate:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:tunedDelegate:statusDelegate:musicCacheDelegate:completion:)","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","text":"TunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/reorderTracks(withNewOrder:completion:)":{"abstract":[],"title":"reorderTracks(withNewOrder:completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/reordertracks(withneworder:completion:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reorderTracks"},{"text":"(","kind":"text"},{"text":"withNewOrder","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/reorderTracks(withNewOrder:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/on":{"role":"symbol","type":"topic","title":"on","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/on","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/on","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"on","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/automixOff(completion:)":{"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automixOff"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithErrorAndPlaybackState","text":"CompletionWithErrorAndPlaybackState"},{"text":"?)","kind":"text"}],"title":"automixOff(completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOff(completion:)","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/automixoff(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"automixOn","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier","text":"AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"text":"playTrackIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier","text":"Int32"},{"text":", ","kind":"text"},{"text":"seconds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoplay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"contextType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contextId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"abstract":[],"role":"symbol","title":"automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOn(withIdentifiers:metadata:playTrackIndex:seconds:autoplay:contextType:contextId:completion:)","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/automixon(withidentifiers:metadata:playtrackindex:seconds:autoplay:contexttype:contextid:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/terminate()":{"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"terminate","kind":"identifier"},{"text":"()","kind":"text"}],"title":"terminate()","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/terminate()","role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/terminate()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/pause(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pause"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"role":"symbol","title":"pause(completion:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/pause(completion:)","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/pause(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/stopLoopingPlayingTrack(completion:)":{"title":"stopLoopingPlayingTrack(completion:)","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/stoploopingplayingtrack(completion:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopLoopingPlayingTrack","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/stopLoopingPlayingTrack(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/automixOn(completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixOn(completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automixOn","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/automixon(completion:)","title":"automixOn(completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/initialised()":{"title":"initialised()","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialised()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialised"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/initialised()","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setFilterExplicit(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setFilterExplicit(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setFilterExplicit"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setfilterexplicit(_:completion:)","title":"setFilterExplicit(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/toggleReplay(completion:)":{"title":"toggleReplay(completion:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/toggleReplay(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toggleReplay","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/togglereplay(completion:)","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/skipToTrack(at:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/skipToTrack(at:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"skipToTrack","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/skiptotrack(at:completion:)","title":"skipToTrack(at:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/removeTrack(at:completion:)":{"title":"removeTrack(at:completion:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/removeTrack(at:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeTrack","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/removetrack(at:completion:)","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/addTracks(withIdentifiers:metadata:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/addTracks(withIdentifiers:metadata:index:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addTracks","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifiers"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/addtracks(withidentifiers:metadata:index:completion:)","title":"addTracks(withIdentifiers:metadata:index:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/automixStatus()":{"title":"automixStatus()","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixStatus()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"automixStatus","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"AutomixSDKStatus","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/automixstatus()","kind":"symbol","role":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/addTrack(withIdentifier:metadata:index:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/addTrack(withIdentifier:metadata:index:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTrack"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": "},{"text":"AutomixSDKTrackModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel"},{"text":"?, ","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/addtrack(withidentifier:metadata:index:completion:)","title":"addTrack(withIdentifier:metadata:index:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setMuteOn(_:completion:)":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setmuteon(_:completion:)","abstract":[],"role":"symbol","title":"setMuteOn(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setMuteOn","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setMuteOn(_:completion:)","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/largeFontSize()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/largeFontSize()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"largeFontSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/largefontsize()","title":"largeFontSize()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/internetAvailable()":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/internetavailable()","abstract":[],"role":"symbol","title":"internetAvailable()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internetAvailable","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/internetAvailable()","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/mediumFontName()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/mediumFontName()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mediumFontName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/mediumfontname()","title":"mediumFontName()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/remove(_:)":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/remove(_:)","abstract":[],"role":"symbol","title":"remove(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/remove(_:)","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setVinylStartStopEnabled(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setVinylStartStopEnabled(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVinylStartStopEnabled"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setvinylstartstopenabled(_:completion:)","title":"setVinylStartStopEnabled(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setAutomixVolumeNormalised(_:completion:)":{"title":"setAutomixVolumeNormalised(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAutomixVolumeNormalised","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setAutomixVolumeNormalised(_:completion:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setautomixvolumenormalised(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getAudioData"},{"text":"(","kind":"text"},{"text":"withFrames","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfChannels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fadeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"text":"audioPCMBuffer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AVAudioPCMBuffer","preciseIdentifier":"c:objc(cs)AVAudioPCMBuffer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/getaudiodata(withframes:numberofchannels:fadestate:audiopcmbuffer:)","title":"getAudioData(withFrames:numberOfChannels:fadeState:audioPCMBuffer:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}],"type":"topic","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","kind":"symbol","url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/setReplayOn(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/setReplayOn(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setReplayOn","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/setreplayon(_:completion:)","title":"setReplayOn(_:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/automixSDKError(withCode:)":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/automixsdkerror(withcode:)","abstract":[],"role":"symbol","title":"automixSDKError(withCode:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"automixSDKError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"text":") -> any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/automixSDKError(withCode:)","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/instance()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/instance()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instance"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/instance()","title":"instance()"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/clearCache(completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/clearCache(completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/clearcache(completion:)","title":"clearCache(completion:)"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDK":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDK"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDK","kind":"identifier"}],"title":"AutomixSDK","abstract":[{"type":"text","text":"AutomixSDK represents the AutomixIQ SDK and exposes all its functionality. It follows a Singleton pattern."}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDK","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdk"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/stopEngine()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/stopEngine()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopEngine"},{"text":"()","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/stopengine()","title":"stopEngine()"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/play(completion:)":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/play(completion:)","abstract":[],"role":"symbol","title":"play(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/play(completion:)","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/initialise(with:streamingDelegate:statusDelegate:completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/initialise(with:streamingDelegate:statusDelegate:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig","text":"AutomixSDKConfig"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamingDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/initialise(with:streamingdelegate:statusdelegate:completion:)","title":"initialise(with:streamingDelegate:statusDelegate:completion:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/joinLiveMixtape(withIdentifier:completion:)":{"url":"\/documentation\/pacemakerradio\/automixsdkobjc\/joinlivemixtape(withidentifier:completion:)","abstract":[],"role":"symbol","title":"joinLiveMixtape(withIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"joinLiveMixtape","kind":"identifier"},{"kind":"text","text":"("},{"text":"withIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/joinLiveMixtape(withIdentifier:completion:)","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKObjC/playTrackToEndThenPause(completion:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKObjC\/playTrackToEndThenPause(completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playTrackToEndThenPause"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionWithError","kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"?)","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkobjc\/playtracktoendthenpause(completion:)","title":"playTrackToEndThenPause(completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/title","value":"AutomixSDK"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDK"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDK\/navigatorTitle","value":[{"text":"AutomixSDK","kind":"identifier"}],"op":"replace"}]}]}