{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate"]]},"metadata":{"title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"kind":"text","text":"("},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sessionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"newSessionId","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","required":true,"externalID":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate(im)asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","role":"symbol"},"abstract":[{"type":"text","text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"newSessionId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The id of the device attempting to stream content within the streaming APIs.","type":"text"}],"type":"paragraph"}],"name":"streamingDeviceId"},{"name":"sessionId","content":[{"type":"paragraph","inlineContent":[{"text":"The current session Id if available. If one is provided and no longer valid a renewed one will be returned.","type":"text"}]}]},{"name":"trackId","content":[{"inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is attempting to stream."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asyncGetStream","kind":"identifier"},{"text":"(","kind":"text"},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"sessionId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newSessionId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required.","type":"text"}],"navigatorTitle":[{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","kind":"symbol","title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","url":"\/documentation\/pacemakerradio\/automixsdkstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","required":true},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","url":"\/documentation\/pacemakerradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"asyncGetStreamWithStreamingDeviceId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"streamingDeviceId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionId"},{"text":" ","kind":"text"},{"text":"trackId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"trackId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"streamingDeviceId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the device attempting to stream content within the streaming APIs."}]}]},{"name":"sessionId","content":[{"inlineContent":[{"text":"The current session Id if available. If one is provided and no longer valid a renewed one will be returned.","type":"text"}],"type":"paragraph"}]},{"name":"trackId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the track that AutomixIQ is attempting to stream."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Code to be executed upon completing the asynchronous request"}]}],"name":"completion"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKStreamingDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","op":"replace"}]}]}