{"abstract":[{"type":"text","text":"How to create a UI to reflect the AutomixIQ player"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/updating-custom-player's-ui-article"]},{"paths":["\/documentation\/automixiq\/updating-custom-player's-ui-article"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"title":"Updating custom player’s UI","identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"],"generated":true}],"sections":[],"primaryContentSections":[{"content":[{"anchor":"Receiving-status-updates","text":"Receiving status updates","level":2,"type":"heading"},{"inlineContent":[{"text":"AutomixIQ reports its state via ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","type":"reference","isActive":true},{"type":"text","text":". This delegate reports the status via its statusChanged method every time the status changes. The function specifies the current status and the variables that were altered since the last time an update was issued. Use the status variables to update the content of your player UI."}],"type":"paragraph"},{"syntax":"swift","code":["public class MyPlayer: NSObject, AutomixSDKStatusObserverDelegate {","    \/\/ ...","","    var latestStatus: AutomixSDKStatus? = nil","    public func statusChanged(variables: [NSNumber], status: AutomixSDKStatus) {","        self.latestStatus = status","        let mirror = Mirror(reflecting: status)","        for propertyInt in variables {","            guard let property: AutomixSDKStatusVariable = AutomixSDKStatusVariable.init(rawValue: propertyInt.intValue) else {","                continue","            }","            \/\/ Update my UI here ->","            switch property {","                case .playing:","                    break","                case .mixing:","                    break","                case .playingTrackIdentifier:","                    break","                case .playingTrackIndex:","                    break","                case .playingTrackIndexInternal:","                    break","                case .playingTrackCurrentTime:","                    break","                case .playingTrackCurrentTimeInternal:","                    break","                case .playingTrackTotalTime:","                    break","                case .playingTrackStreamingProgress:","                    break","                case .canSkipToPrevious:","                    break","                case .canSkipToNext:","                    break","                case .canBack:","                    break","                case .canPlayPause:","                    break","                case .canSeek:","                    break","                case .canReorderTracks:","                    break","                case .replayOn:","                    break","                case .readyToPlay:","                    break","                case .canMixNow:","                    break","                case .playlist:","                    break","                case .muted:","                    break","                case .playSpeed:","                    break","                case .normalisedVolume:","                    break","                case .preferredTransitionDurationSeconds:","                    break","                case .requestedLoopTrackIdentifier:","                    break","                case .requestedPauseTrackIdentifier:","                    break","                case .vinylStartStop:","                    break","                case .nextTransitionDuration:","                    break","                case .transitionStartTimeSeconds:","                    break","                case .failedTrackLoadIdentifiers:","                    break","                case .canOnOff:","                    break","                case .playingTrackOriginalSessionId:","                    break","                case .explicitLyricsFiltering:","                    break","                case .mixId:","                    break","            }","        }","    }","","","    \/\/ ...","}"],"type":"codeListing"},{"anchor":"Receiving-playback-events","level":2,"type":"heading","text":"Receiving playback events"},{"type":"paragraph","inlineContent":[{"text":"When a playback event happens, AutomixIQ calls the status observer delegate method:","type":"text"}]},{"type":"codeListing","code":["public class MyPlayer: NSObject, AutomixSDKStatusObserverDelegate {","    \/\/ ...","","    public func playbackEvent(type: AutomixSDKPlaybackEventType, identifier: String?, originalSessionId: String?, status: AutomixSDKStatus?) {","        switch (type) {","            case .trackPlayStart:","                break;","            case .trackPlayPlayed5Secs:","                break;","            case .trackPlayHeartbeat30Secs:","                break;","            case .trackPlayStartMixingIntoNext:","                break;","            case .trackPlaySkipped:","                break;","            case .trackPlayFinished:","                break;","            case .mixPlaybackEnded:","                break;","        }","    }","    \/\/ ...","}"],"syntax":"swift"},{"inlineContent":[{"text":"The type of playback event is modelled by the enum ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","isActive":true}],"type":"paragraph"},{"type":"heading","anchor":"Accessing-waveform-data","level":2,"text":"Accessing waveform data"},{"type":"paragraph","inlineContent":[{"text":"When waveform data for a track is available, AutomixIQ calls the observer delegate method:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["public class MyPlayer: NSObject, AutomixSDKStatusObserverDelegate {","    \/\/ ...","","    public func waveformDataAvailable(identifier: String) {","        let waveformData = AutomixSDK.waveformDataForTrack(identifier: identifier, applyTransitions: false)","        guard let xValues = waveformData.xAxis","              let yValues = waveformData.yAxis else {","            return","        }","        \/\/\/ Render things on screen, etc.","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Please refer to "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article","isActive":true,"type":"reference"}]},{"type":"heading","level":2,"text":"The AutomixIQ status","anchor":"The-AutomixIQ-status"},{"inlineContent":[{"type":"text","text":"The status of AutomixIQ is modelled by "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus"},{"text":":","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","isActive":true}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","interfaceLanguage":"swift"},"metadata":{"role":"article","modules":[{"name":"AutomixIQ"}],"title":"Updating your player UI","roleHeading":"Article"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/automixiq","role":"collection"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKPlaybackEventType":{"url":"\/documentation\/automixiq\/automixsdkplaybackeventtype","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType","type":"topic","kind":"symbol","abstract":[{"text":"AutomixSDKPlaybackEventType is an enum of all the available playback events","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackEventType"}],"title":"AutomixSDKPlaybackEventType","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatus":{"title":"AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatus"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Accessing-waveform-data-article":{"abstract":[],"type":"topic","url":"\/documentation\/automixiq\/accessing-waveform-data-article","title":"Accessing waveform data","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Accessing-waveform-data-article","role":"article","kind":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"type":"topic","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","title":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKPlaybackEventType"],"title":"Updating custom player’s UI","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":"AutomixSDKPlaybackEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKPlaybackEventType\/fragments","value":[{"text":"AutomixSDKPlaybackEventType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/title","value":"AutomixSDKStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatus\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}