{"kind":"symbol","abstract":[{"type":"text","text":"The title of a track"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Name"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel"]]},"metadata":{"title":"Name","navigatorTitle":[{"text":"Name","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel(py)Name"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel\/name"]},{"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/Name":{"title":"Name","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/name","navigatorTitle":[{"text":"Name","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Name","abstract":[{"type":"text","text":"The title of a track"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"Name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"title":"AutomixSDKTrackModel","abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKTrackModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"Name","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Name"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"Name","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Name\/title","value":"Name"},{"op":"replace","value":[{"kind":"identifier","text":"Name"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Name\/fragments"},{"value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}]},{"op":"replace","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle"}]}]}