{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Operator","extendedModule":"Swift","modules":[{"name":"PacemakerRadio","relatedModules":["Swift"]}],"title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@PacemakerRadio@E@AutomixSDKPlaylistOperationType","role":"symbol","symbolKind":"op"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/!=(_:_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/!=(_:_:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/Equatable-Implementations","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/equatable-implementations"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","title":"AutomixSDKPlaylistOperationType","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType/!=(_:_:)":{"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype\/!=(_:_:)","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AutomixSDKPlaylistOperationType","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]},{"value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle"}]}]}