{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotcreateinputbuffer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/cannotcreateinputbuffer"]}],"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeCannotCreateInputBuffer","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cannotCreateInputBuffer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"role":"symbol","title":"AutomixSDKErrorCode.cannotCreateInputBuffer","symbolKind":"case","modules":[{"name":"AutomixIQ"}]},"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateInputBuffer","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotCreateInputBuffer"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/cannotCreateInputBuffer":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/cannotCreateInputBuffer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cannotCreateInputBuffer","kind":"identifier"}],"abstract":[],"title":"AutomixSDKErrorCode.cannotCreateInputBuffer","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkerrorcode\/cannotcreateinputbuffer","navigatorTitle":[{"text":"AutomixSDKErrorCodeCannotCreateInputBuffer","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"url":"\/documentation\/automixiq\/automixsdkerrorcode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKErrorCode"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","role":"symbol","title":"AutomixSDKErrorCode","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCode"}],"kind":"symbol","abstract":[{"text":"AutomixSDK error codes","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"AutomixSDKErrorCodeCannotCreateInputBuffer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"AutomixSDKErrorCodeCannotCreateInputBuffer","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeCannotCreateInputBuffer"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"AutomixSDKErrorCodeCannotCreateInputBuffer","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/title","op":"replace"},{"value":[{"text":"AutomixSDKErrorCodeCannotCreateInputBuffer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1cannotCreateInputBuffer\/fragments"},{"value":"AutomixSDKErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"text":"AutomixSDKErrorCode","kind":"identifier"}]}]}]}