{"metadata":{"modules":[{"name":"PacemakerRadio"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariableNextTransitionDuration"}],"title":"AutomixSDKStatusVariable.nextTransitionDuration","roleHeading":"Case","externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableNextTransitionDuration","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextTransitionDuration"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nextTransitionDuration","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/nexttransitionduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/nexttransitionduration"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/nextTransitionDuration","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","kind":"symbol","title":"AutomixSDKStatusVariable","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixIQ status variable type"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/nextTransitionDuration":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/nextTransitionDuration","type":"topic","title":"AutomixSDKStatusVariable.nextTransitionDuration","navigatorTitle":[{"text":"AutomixSDKStatusVariableNextTransitionDuration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/nexttransitionduration","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"nextTransitionDuration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKStatusVariableNextTransitionDuration"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusVariableNextTransitionDuration"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableNextTransitionDuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"AutomixSDKStatusVariable","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1nextTransitionDuration\/title","value":"AutomixSDKStatusVariableNextTransitionDuration"},{"value":[{"text":"AutomixSDKStatusVariableNextTransitionDuration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1nextTransitionDuration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}