{"metadata":{"role":"symbol","externalID":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate(im)willDismissRadioUI","title":"willDismissRadioUI()","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDismissRadioUI"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"willDismissRadioUI"}],"modules":[{"name":"PacemakerRadio"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Called by AutomixSDK when the Radio UI about to be dismissed","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiouidelegate\/willdismissradioui()"]},{"paths":["\/documentation\/pacemakerradio\/radiouidelegate\/willdismissradioui()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissRadioUI"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate\/willDismissRadioUI()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate/willDismissRadioUI()":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate\/willDismissRadioUI()","type":"topic","title":"willDismissRadioUI()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDismissRadioUI"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pacemakerradio\/radiouidelegate\/willdismissradioui()","navigatorTitle":[{"text":"willDismissRadioUI","kind":"identifier"}],"abstract":[{"type":"text","text":"Called by AutomixSDK when the Radio UI about to be dismissed"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","type":"topic","title":"RadioUIDelegate","kind":"symbol","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"willDismissRadioUI"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"willDismissRadioUI","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willDismissRadioUI","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"willDismissRadioUI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate~1willDismissRadioUI()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate~1willDismissRadioUI()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willDismissRadioUI"}]},{"value":"RadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments","value":[{"text":"RadioUIDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","op":"replace","value":[{"text":"RadioUIDelegate","kind":"identifier"}]}]}]}