{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playlist"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/playlist"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable"]]},"metadata":{"role":"symbol","externalID":"c:@M@PacemakerRadio@E@AutomixSDKStatusVariable@AutomixSDKStatusVariablePlaylist","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playlist"}],"title":"AutomixSDKStatusVariable.playlist","modules":[{"name":"PacemakerRadio"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylist"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/playlist"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatusvariable\/playlist"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable/playlist":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable\/playlist","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable\/playlist","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylist"}],"title":"AutomixSDKStatusVariable.playlist","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playlist","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","kind":"symbol","abstract":[{"text":"AutomixIQ status variable type","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"AutomixSDKStatusVariablePlaylist","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"AutomixSDKStatusVariablePlaylist","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariablePlaylist"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1playlist\/title","value":"AutomixSDKStatusVariablePlaylist"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable~1playlist\/fragments","op":"replace","value":[{"text":"AutomixSDKStatusVariablePlaylist","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}