{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPlayPause"}]}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canplaypause"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstatusvariable\/canplaypause"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"AutomixSDKStatusVariable.canPlayPause","externalID":"c:@M@AutomixIQ@E@AutomixSDKStatusVariable@AutomixSDKStatusVariableCanPlayPause","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"canPlayPause","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}],"modules":[{"name":"AutomixIQ"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canPlayPause"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable"]]},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}],"title":"AutomixIQ","url":"\/documentation\/automixiq","kind":"symbol","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable/canPlayPause":{"abstract":[],"role":"symbol","title":"AutomixSDKStatusVariable.canPlayPause","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canPlayPause"}],"navigatorTitle":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}],"type":"topic","url":"\/documentation\/automixiq\/automixsdkstatusvariable\/canplaypause","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable\/canPlayPause","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusVariable":{"url":"\/documentation\/automixiq\/automixsdkstatusvariable","type":"topic","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"title":"AutomixSDKStatusVariable","role":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusVariable","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"AutomixSDKStatusVariableCanPlayPause","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKStatusVariableCanPlayPause"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"AutomixSDKStatusVariableCanPlayPause","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canPlayPause\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable~1canPlayPause\/fragments","value":[{"text":"AutomixSDKStatusVariableCanPlayPause","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/title","value":"AutomixSDKStatusVariable","op":"replace"},{"value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusVariable\/fragments","op":"replace"}]}]}