{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoCurrentTrack"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoCurrentTrack"}],"symbolKind":"case","roleHeading":"Case","title":"AutomixSDKErrorCode.seekNoCurrentTrack","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekNoCurrentTrack"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKErrorCode@AutomixSDKErrorCodeSeekNoCurrentTrack","modules":[{"name":"AutomixIQ"}],"role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/seeknocurrenttrack"]},{"paths":["\/documentation\/automixiq\/automixsdkerrorcode\/seeknocurrenttrack"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekNoCurrentTrack"}]}]}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","kind":"symbol","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"url":"\/documentation\/automixiq"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode":{"role":"symbol","kind":"symbol","title":"AutomixSDKErrorCode","navigatorTitle":[{"text":"AutomixSDKErrorCode","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkerrorcode","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode","type":"topic","abstract":[{"type":"text","text":"AutomixSDK error codes"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AutomixSDKErrorCode","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKErrorCode/seekNoCurrentTrack":{"abstract":[],"url":"\/documentation\/automixiq\/automixsdkerrorcode\/seeknocurrenttrack","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKErrorCode\/seekNoCurrentTrack","title":"AutomixSDKErrorCode.seekNoCurrentTrack","type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekNoCurrentTrack"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"AutomixSDKErrorCodeSeekNoCurrentTrack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AutomixSDKErrorCodeSeekNoCurrentTrack","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoCurrentTrack"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/title","op":"replace","value":"AutomixSDKErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoCurrentTrack\/title","value":"AutomixSDKErrorCodeSeekNoCurrentTrack"},{"value":[{"kind":"identifier","text":"AutomixSDKErrorCodeSeekNoCurrentTrack"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKErrorCode~1seekNoCurrentTrack\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}