{"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"allowFX","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"allowAudioEffects"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"allowBackgrounds"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"allowCommenting"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowVoiceOver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"text":"allowSongSuggestions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"text":"allowInvites","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"allowStudio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"deeplinkToUser"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"\")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig(im)initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:","roleHeading":"Initializer","symbolKind":"init","title":"init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"allowFX","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowAudioEffects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowBackgrounds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"allowCommenting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"allowVoiceOver","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"allowSongSuggestions","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowInvites"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"allowStudio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deeplinkToUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","navigatorTitle":[{"text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)":{"role":"symbol","abstract":[],"title":"init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"allowFX"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowAudioEffects"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowBackgrounds"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"allowCommenting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowVoiceOver","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"allowSongSuggestions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowInvites"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowStudio","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"deeplinkToUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig\/init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig\/init(allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:deeplinktouser:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"navigatorTitle":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","abstract":[],"kind":"symbol","title":"RadioSDKFeatureSetConfig","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAllowFX:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"allowFX","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAudioEffects:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowAudioEffects"},{"text":" ","kind":"text"},{"text":"allowBackgrounds:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"allowBackgrounds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowCommenting:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"allowCommenting","kind":"internalParam"},{"kind":"text","text":" "},{"text":"allowVoiceOver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowVoiceOver","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowSongSuggestions:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowSongSuggestions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowInvites:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"allowInvites"},{"kind":"text","text":" "},{"text":"allowPublicBroadcasts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"allowPublicBroadcasts","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowStudio:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowStudio"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deeplinkToUser:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"deeplinkToUser","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)\/title","value":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig~1init(allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAllowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:deeplinkToUser:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title","value":"RadioSDKFeatureSetConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle"}]}]}