{"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig"]}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/featureSetConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/uiConfig"],"title":"Instance Properties","generated":true},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/colorToInt(color:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/intToColor(colorInt:)"],"title":"Type Methods"}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig","title":"RadioSDKConfig","modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RadioSDKConfig","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Initialising-PacemakerRadio-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel"],"anchor":"Initializing-PacemakerRadio-for-use-with-Tuned-Globals-APIs","title":"Initializing PacemakerRadio for use with Tuned Global’s APIs"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioUIDelegate"}],"abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","title":"RadioUIDelegate","url":"\/documentation\/pacemakerradio\/radiouidelegate","type":"topic","kind":"symbol","navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"role":"symbol","title":"RadioSDKUIConfig","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKConfig":{"abstract":[],"role":"symbol","title":"AutomixSDKConfig","kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKConfig"}],"url":"\/documentation\/pacemakerradio\/automixsdkconfig","navigatorTitle":[{"text":"AutomixSDKConfig","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/SQ":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/intToColor(colorInt:)":{"kind":"symbol","type":"topic","title":"intToColor(colorInt:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/intToColor(colorInt:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"intToColorWithColorInt:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intToColor","kind":"identifier"},{"kind":"text","text":"("},{"text":"colorInt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/inttocolor(colorint:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"url":"\/documentation\/pacemakerradio\/tunedrestdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TunedRestDelegate"}],"navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"title":"TunedRestDelegate"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStreamingDelegate":{"title":"AutomixSDKStreamingDelegate","url":"\/documentation\/pacemakerradio\/automixsdkstreamingdelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"kind":"symbol","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKLogLevel":{"type":"topic","title":"AutomixSDKLogLevel","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkloglevel","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKFeatureSetConfig":{"navigatorTitle":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"title":"RadioSDKFeatureSetConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkfeaturesetconfig"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","role":"symbol","kind":"symbol","title":"init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:featuresetconfig:uiconfig:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"featureSetConfig","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"uiConfig"},{"kind":"text","text":": "},{"text":"RadioSDKUIConfig","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Initialising-PacemakerRadio-article":{"type":"topic","title":"Initializing PacemakerRadio","role":"article","kind":"article","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Initialising-PacemakerRadio-article","abstract":[{"text":"How to validate your client and start using the PacemakerRadio SDK with Tuned Global APIs","type":"text"}],"url":"\/documentation\/pacemakerradio\/initialising-pacemakerradio-article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperationType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","title":"AutomixSDKPlaylistOperationType","type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperationtype","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"title":"TunedMusicCacheDelegate","url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","role":"symbol","type":"topic","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaybackMode":{"abstract":[{"text":"AutomixIQ playback mode","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkplaybackmode","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode","title":"AutomixSDKPlaybackMode"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/featureSetConfig":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/featureSetConfig","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/featuresetconfig","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"featureSetConfig","kind":"identifier"},{"kind":"text","text":": "},{"text":"RadioSDKFeatureSetConfig","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKFeatureSetConfig"}],"navigatorTitle":[{"kind":"identifier","text":"featureSetConfig"}],"abstract":[],"type":"topic","title":"featureSetConfig","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","type":"topic","title":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/colorToInt(color:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/colorToInt(color:)","title":"colorToInt(color:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"colorToInt","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"colorToIntWithColor:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/colortoint(color:)","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusVariable":{"url":"\/documentation\/pacemakerradio\/automixsdkstatusvariable","title":"AutomixSDKStatusVariable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","role":"symbol","abstract":[{"type":"text","text":"AutomixIQ status variable type"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"type":"topic","navigatorTitle":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/uiConfig":{"abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/uiconfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiConfig"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig","kind":"typeIdentifier","text":"RadioSDKUIConfig"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"uiConfig"}],"title":"uiConfig","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/uiConfig","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"url":"\/documentation\/pacemakerradio\/radiosdkconfig","title":"RadioSDKConfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKConfig"}],"kind":"symbol","navigatorTitle":[{"text":"RadioSDKConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"RadioSDKConfig","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/featureSetConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/uiConfig"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/colorToInt(color:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/intToColor(colorInt:)"],"title":"Type Methods","anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig"]}],"op":"replace"},{"op":"replace","value":[{"title":"Initializing PacemakerRadio for use with Tuned Global’s APIs","anchor":"Initializing-PacemakerRadio-for-use-with-Tuned-Globals-APIs","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Initialising-PacemakerRadio-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKFeatureSetConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusVariable","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaybackMode","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperationType","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKLogLevel"]}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKConfig","text":"AutomixSDKConfig"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","value":"RadioUIDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle","op":"replace","value":[{"text":"RadioUIDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","op":"replace","value":"RadioSDKUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/title","value":"AutomixSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/fragments","value":[{"text":"AutomixSDKConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKConfig"}]},{"op":"replace","value":"intToColorWithColorInt:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1intToColor(colorInt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1intToColor(colorInt:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"intToColorWithColorInt:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title","op":"replace","value":"TunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/title","op":"replace","value":"AutomixSDKStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/title","value":"AutomixSDKLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKLogLevel\/navigatorTitle","value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"op":"replace"},{"value":"RadioSDKFeatureSetConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKFeatureSetConfig"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKFeatureSetConfig\/navigatorTitle","value":[{"text":"RadioSDKFeatureSetConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/title","op":"replace","value":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:featureSetConfig:uiConfig:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:featureSetConfig:uiConfig:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/title","value":"AutomixSDKPlaylistOperationType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/fragments","value":[{"text":"AutomixSDKPlaylistOperationType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperationType\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperationType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}]},{"op":"replace","value":"AutomixSDKPlaybackMode","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaybackMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaybackMode\/navigatorTitle","value":[{"text":"AutomixSDKPlaybackMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1featureSetConfig\/title","value":"featureSetConfig","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1featureSetConfig\/fragments","op":"replace","value":[{"text":"featureSetConfig","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1colorToInt(color:)\/title","value":"colorToIntWithColor:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"colorToIntWithColor:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1colorToInt(color:)\/fragments"},{"value":"AutomixSDKStatusVariable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKStatusVariable"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKStatusVariable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusVariable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1uiConfig\/title","value":"uiConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1uiConfig\/fragments","value":[{"kind":"identifier","text":"uiConfig"}],"op":"replace"},{"op":"replace","value":"RadioSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}]},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}