{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelTrace"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelTrace","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/automixiq\/automixsdkloglevel\/logleveltrace"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/automixsdkloglevel\/logleveltrace"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"]]},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelTrace"}],"roleHeading":"Case","navigatorTitle":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}],"externalID":"c:@M@AutomixIQ@E@AutomixSDKLogLevel@AutomixSDKLogLevelLogLevelTrace","title":"AutomixSDKLogLevel.logLevelTrace","role":"symbol","modules":[{"name":"AutomixIQ"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","url":"\/documentation\/automixiq","type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel/logLevelTrace":{"url":"\/documentation\/automixiq\/automixsdkloglevel\/logleveltrace","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel\/logLevelTrace","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevelTrace"}],"title":"AutomixSDKLogLevel.logLevelTrace"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"title":"AutomixSDKLogLevel","url":"\/documentation\/automixiq\/automixsdkloglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"AutomixSDKLogLevelLogLevelTrace","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"AutomixSDKLogLevelLogLevelTrace"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelTrace\/title","op":"replace","value":"AutomixSDKLogLevelLogLevelTrace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel~1logLevelTrace\/fragments","value":[{"text":"AutomixSDKLogLevelLogLevelTrace","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title","op":"replace","value":"AutomixSDKLogLevel"},{"value":[{"kind":"identifier","text":"AutomixSDKLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments","op":"replace"}]}]}