{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/dialogTitleFontBold"},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig(py)dialogTitleFontBold","title":"dialogTitleFontBold","modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dialogTitleFontBold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dialogTitleFontBold"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dialogTitleFontBold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogtitlefontbold"]},{"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogtitlefontbold"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"]]},"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"role":"symbol","title":"RadioSDKUIConfig","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig/dialogTitleFontBold":{"abstract":[],"navigatorTitle":[{"text":"dialogTitleFontBold","kind":"identifier"}],"kind":"symbol","title":"dialogTitleFontBold","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/dialogTitleFontBold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dialogTitleFontBold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig\/dialogtitlefontbold","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"dialogTitleFontBold","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"dialogTitleFontBold","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogTitleFontBold"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"RadioSDKUIConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}]},{"op":"replace","value":"dialogTitleFontBold","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1dialogTitleFontBold\/title"},{"value":[{"text":"dialogTitleFontBold","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1dialogTitleFontBold\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}