{"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/radioUIFontSizeLarge","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeLarge"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"]]},"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizelarge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizelarge"]}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"radioUIFontSizeLarge","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeLarge"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig(py)radioUIFontSizeLarge","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeLarge"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig/radioUIFontSizeLarge":{"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizelarge","kind":"symbol","navigatorTitle":[{"text":"radioUIFontSizeLarge","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeLarge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","title":"radioUIFontSizeLarge","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/radioUIFontSizeLarge","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RadioSDKUIConfig"}],"role":"symbol","title":"RadioSDKUIConfig","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"radioUIFontSizeLarge","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"radioUIFontSizeLarge","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeLarge","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1radioUIFontSizeLarge\/title","value":"radioUIFontSizeLarge"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1radioUIFontSizeLarge\/fragments","value":[{"kind":"identifier","text":"radioUIFontSizeLarge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}