{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackBpm","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackBpm","kind":"identifier"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"PacemakerRadio"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"trackBpm","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"kind":"identifier","text":"trackBpm"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeTrack(py)trackBpm","title":"trackBpm","roleHeading":"Instance Property","symbolKind":"property"},"abstract":[{"text":"The bpm of the track","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackbpm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackbpm"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"title":"AutomixSDKMixtapeTrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack/trackBpm":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack\/trackBpm","url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack\/trackbpm","abstract":[{"text":"The bpm of the track","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackBpm"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","title":"trackBpm","role":"symbol","navigatorTitle":[{"text":"trackBpm","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"trackBpm","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"trackBpm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":" ","kind":"text"},{"text":"trackBpm","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title","value":"AutomixSDKMixtapeTrack"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrack"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackBpm\/title","value":"trackBpm"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack~1trackBpm\/fragments","value":[{"text":"trackBpm","kind":"identifier"}]}]}]}