{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackDownloadCompeleted"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The id of the track that the AutomixIQ SDK is streaming.","type":"text"}]}],"name":"trackId"},{"name":"data","content":[{"inlineContent":[{"type":"text","text":"The track data as an array of bytes."}],"type":"paragraph"}]}]}],"metadata":{"title":"trackDownloadCompeleted(trackId:data:)","modules":[{"name":"AutomixIQ"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"trackDownloadCompeletedWithTrackId:data:","kind":"identifier"}],"required":true,"role":"symbol","externalID":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate(im)trackDownloadCompeletedWithTrackId:data:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackDownloadCompeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompeleted(trackid:data:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompeleted(trackid:data:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompeleted(trackId:data:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Called by the AutomixIQ SDK when a track has been fully downloaded.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A sample use case would be, for instance, allowing for encrypted on-device caching of downloaded tracks."}],"kind":"symbol","references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"url":"\/documentation\/automixiq","role":"collection","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadCompeleted(trackId:data:)":{"navigatorTitle":[{"text":"trackDownloadCompeletedWithTrackId:data:","kind":"identifier"}],"title":"trackDownloadCompeleted(trackId:data:)","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompeleted(trackid:data:)","required":true,"role":"symbol","type":"topic","abstract":[{"text":"Called by the AutomixIQ SDK when a track has been fully downloaded.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"A sample use case would be, for instance, allowing for encrypted on-device caching of downloaded tracks."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompeleted(trackId:data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackDownloadCompeleted"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the information it requires to play content.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"See TunedDemoStreamingHandler for an example of an object implementing this protocol."}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","type":"topic","role":"symbol","title":"AutomixSDKStreamingDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"trackDownloadCompeletedWithTrackId:data:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackDownloadCompeletedWithTrackId:data:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"trackDownloadCompeletedWithTrackId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"trackId"},{"text":" ","kind":"text"},{"text":"data:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompeleted(trackId:data:)\/title","value":"trackDownloadCompeletedWithTrackId:data:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompeleted(trackId:data:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"trackDownloadCompeletedWithTrackId:data:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments"}]}]}