{"kind":"article","abstract":[{"text":"How to validate your client and start using the AutomixIQ SDK with a custom backend","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"]]},"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Essentials","text":"Essentials"},{"inlineContent":[{"text":"This document explains how to integrate AutomixIQ with your application you are using a custom backend to access tracks and metadata","type":"text"}],"type":"paragraph"},{"type":"heading","text":"Initialization when you take the responsibility of providing audio data and metadata","level":3,"anchor":"Initialization-when-you-take-the-responsibility-of-providing-audio-data-and-metadata"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to initialise AutomixIQ when you take the responsibility of providing audio data and metadata you need a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate"},{"text":" and a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate"},{"type":"text","text":", plus a store ID, applicationId and a country code:"}]},{"syntax":"swift","type":"codeListing","code":["func application(_ application: UIApplication, ","                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {","    \/\/ ...","","    let automixSDKStreamingDelegate: AutomixSDKStreamingDelegate = myAutomixSDKStreamingDelegate","    let automixSDKStatusObserverDelegate: AutomixSDKStatusObserverDelegate = myAutomixSDKStatusObserverDelegate","    let countryCode: String = myCountryCode \/\/ \"US\" ? \"AU\"?","    let storeId: String = myTunedStoreId","    let applicationId: String = myApplicationId","    AutomixSDK.initialise(streamingDelegate:automixSDKStreamingDelegate,","                          statusDelegate:automixSDKStatusObserverDelegate,","                          countryCode:countryCode,","                          storeId:storeId,","                          applicationId:applicationId)","    { error in","        if error != nil {","            \/\/ This means you are forbidden to use the Automix SDK or you have no internet connection.","            return","        }","        \/\/ The Automix SDK public functions can be used from this point onwards :)","    }","","    \/\/ ...","}"]},{"type":"heading","text":"AutomixSDKStreamingDelegate","level":4,"anchor":"AutomixSDKStreamingDelegate"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"If your custom backend puts fetching metadata and track data behind a login, AutomixIQ needs to know if the user in your application is logged in or not via"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/isLoggedIn()","type":"reference","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func isLoggedIn() {","        return self.loggedIn","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If your custom backend only allows playback on a device under certain conditions (for instance in only allows one device to play at any given time), AutomixIQ needs to know if a device is allowed to play via","type":"text"},{"text":" ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncCheckDeviceStatus(completion:)"}]}]}]},{"type":"codeListing","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func asyncCheckDeviceStatus(completion: @escaping (_ error: Error?, _ canContinuePlaying: Bool) -> Void) {","        self.canDeviceContinuePlaying() { allowedToPlay in","            return allowedToPlay","        }","    }","    \/\/ ...","}"],"syntax":"swift"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ requires devices to have a unique identifier, provided via"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/getDeviceIdentifier()","isActive":true,"type":"reference"}]}]}],"type":"unorderedList"},{"syntax":"swift","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func getDeviceIdentifier() -> String {","        return self.deviceIdentifier","    }","    \/\/ ...","}"],"type":"codeListing"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"This provides hooks to inject cached track audio data and metadata, preventing AutomixIQ from having to request this data from your custom backend if they are already available. This also enables offline playback when all required data is available on the device","type":"text"}]}]}],"type":"unorderedList"},{"inlineContent":[{"text":"This is done via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetTrackMetadata(trackId:)"}],"type":"paragraph"},{"code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func syncGetTrackMetadata(trackId: String?) -> AutomixIQ.AutomixSDKTrackModel? {","        \/\/ If I have this track cached, I should be able to tell its metadata","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.metadataForTrack(trackId)","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"and ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","isActive":true}]},{"syntax":"swift","type":"codeListing","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func syncGetCachedTrack(trackId: String) -> Data? {","        \/\/ If I have this track cached, I should be able to decrypt it and send the data","        if self.isTrackCached(trackId) == false {","            return nil","        }","        return self.unencryptedDataForTrack(trackId)","    }","    \/\/ ...","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ will pass every track metadata model it may have downloaded to the client to provide an opportunity to cache it. If you do not need this, you may leave this function empty."},{"text":" ","type":"text"},{"text":"``AutomixSDKStreamingDelegate\/cacheMetadata(_:)`","type":"text"}]},{"code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func cacheMetadata(_ metadata: [AutomixSDKTrackModel]) -> Data? {","        self.metadataForTrack[metadata.trackId] = metadata","    }","    \/\/ ...","}"],"type":"codeListing","syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"AutomixIQ will download track metadata as it needs it. When required, it will do so via"},{"type":"text","text":" "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","isActive":true}]}]}]},{"type":"codeListing","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func asyncGetTrackMetadata(trackId: String, completion: @escaping (_ error: Error?, _ track: AutomixSDKTrackModel?) -> Void) {","        self.getTrackMetadata(trackId: trackId) { error, trackMetadata in","            let automixSDKTrackModel = translateMetadata(trackMetadata)","            return completion(error, automixSDKTrackModel)","        }","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"When AutomixIQ needs to download a track, it will ask for the url for it. It supports session IDs if you want urls to expire and return 403s. It will do so via"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","isActive":true,"type":"reference"}],"type":"paragraph"}]}]},{"code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func asyncGetStream(streamingDeviceId: String, sessionId: String, trackId: String, completion: @escaping (_ error: Error?, _ url: String?, _ newSessionId: String?, _ reportingURLS: Beacons?) -> Void) {","        self.getTrackURL(deviceId: streamingDeviceId, sessionId: sessionId, trackId: trackId) { error, url in ","            return completion(error, url)","        }","    }","    \/\/ ...","}"],"syntax":"swift","type":"codeListing"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"When a track finishes downloading, AutomixIQ will pass the audio data for you to cache if required. This is done via"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","isActive":true}],"type":"paragraph"}]}]},{"type":"codeListing","syntax":"swift","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func trackDownloadCompleted(trackId: String, data: NSData) {","        self.cacheTrack(trackId: trackId, data: data)","    }","    \/\/ ...","}"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"As a track is being downloaded, AutomixIQ will report download progress via","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)"}]}]}]},{"type":"codeListing","code":["public class MyAutomixSDKStreamingDelegate: NSObject, AutomixSDKStreamingDelegate {","    \/\/ ...","    public func trackDownloadProgressChanged(trackId: String, progress: Swift.Float) {","        self.updateTrackDownloadProgress(trackId: trackId, progress: progress)","    }","    \/\/ ...","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Do keep in mind this download is done lazily, as AutomixIQ requires data for analysis \/ playback. There is no guarantee a track will download in its entirety if the track is not played in its entirety."}]},{"anchor":"AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","type":"heading","level":4},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","isActive":true},{"type":"text","text":" is responsible for updating your player’s UI, please refer to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","isActive":true}]},{"type":"heading","level":3,"text":"Checking if AutomixIQ is initialised","anchor":"Checking-if-AutomixIQ-is-initialised"},{"inlineContent":[{"type":"text","text":"To check wether AutomixIQ is currently initialised, use"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialised()"}],"type":"paragraph"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"AutomixIQ"}],"title":"Initializing AutomixIQ with a custom backend"},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"],"generated":true,"title":"Initializing AutomixIQ for use with a custom backend"}],"identifier":{"url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Initialising-AutomixIQ-with-custom-backend-article","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/automixiq\/initialising-automixiq-with-custom-backend-article"]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"title":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncGetTrackMetadata(trackId:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ when it requires the metadata of a track in order to load it."}],"title":"asyncGetTrackMetadata(trackId:completion:)","type":"topic","required":true,"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asyncgettrackmetadata(trackid:completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetTrackMetadata(trackId:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"asyncGetTrackMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"track","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","text":"AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"asyncGetTrackMetadataWithTrackId:completion:"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKLogLevel":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel","role":"symbol","navigatorTitle":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"url":"\/documentation\/automixiq\/automixsdkloglevel","kind":"symbol","abstract":[{"text":"AutomixSDKLogLevel is an enum of all the AutomixIQ available log levels","type":"text"}],"title":"AutomixSDKLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKLogLevel","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadProgressChanged(trackId:progress:)":{"navigatorTitle":[{"text":"trackDownloadProgressChangedWithTrackId:progress:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadProgressChanged(trackId:progress:)","kind":"symbol","type":"topic","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadprogresschanged(trackid:progress:)","abstract":[{"type":"text","text":"Called by AutomixIQ when a track download progress has changed."}],"title":"trackDownloadProgressChanged(trackId:progress:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackDownloadProgressChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/syncGetTrackMetadata(trackId:)":{"abstract":[{"text":"Called by AutomixIQ before attempting to download a tracks metadata to allow the client to provide any cached metadata, return nil if not available.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgettrackmetadata(trackid:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"syncGetTrackMetadata"},{"text":"(","kind":"text"},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"AutomixSDKTrackModel","preciseIdentifier":"c:@M@AutomixIQ@objc(cs)AutomixSDKTrackModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetTrackMetadata(trackId:)","navigatorTitle":[{"kind":"identifier","text":"syncGetTrackMetadataWithTrackId:"}],"type":"topic","kind":"symbol","title":"syncGetTrackMetadata(trackId:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncCheckDeviceStatus(completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Called by AutomixIQ regularly while something is being played, this can be used if you have restrictions on the number of devices that can play simultaneously"}],"type":"topic","title":"asyncCheckDeviceStatus(completion:)","required":true,"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asynccheckdevicestatus(completion:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncCheckDeviceStatus(completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asyncCheckDeviceStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"canContinuePlaying"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"asyncCheckDeviceStatusWithCompletion:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/Updating-custom-player's-UI-article":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/Updating-custom-player's-UI-article","abstract":[{"text":"How to create a UI to reflect the AutomixIQ player","type":"text"}],"url":"\/documentation\/automixiq\/updating-custom-player's-ui-article","type":"topic","title":"Updating your player UI","kind":"article","role":"article"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/trackDownloadCompleted(trackId:data:)":{"title":"trackDownloadCompleted(trackId:data:)","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/trackDownloadCompleted(trackId:data:)","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/trackdownloadcompleted(trackid:data:)","type":"topic","abstract":[{"type":"text","text":"Called by AutomixIQ when a track has been fully downloaded. This can be used to cache the track locally on the user’s device."}],"kind":"symbol","role":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"trackDownloadCompleted","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"trackId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)":{"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/asyncgetstream(streamingdeviceid:sessionid:trackid:completion:)","title":"asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"asyncGetStream"},{"kind":"text","text":"("},{"text":"streamingDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"sessionId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"trackId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"newSessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)","type":"topic","abstract":[{"text":"Called by AutomixIQ to obtain the URL to stream audio from, a sessionId if the URL is to be salted with one, and the URL to report playback events if required.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/isLoggedIn()":{"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/isloggedin()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/isLoggedIn()","navigatorTitle":[{"kind":"identifier","text":"isLoggedIn"}],"abstract":[{"type":"text","text":"Called by AutomixIQ to learn if it is allowed to stream content that is protected by some form of authentication."},{"type":"text","text":" "},{"type":"text","text":"An example is, an implementation via an API behind OAuth would return true if access and refresh tokens are available, false otherwise"}],"type":"topic","title":"isLoggedIn()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLoggedIn"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true,"role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/getDeviceIdentifier()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getDeviceIdentifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"getDeviceIdentifier"}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/getdeviceidentifier()","title":"getDeviceIdentifier()","abstract":[{"type":"text","text":"Called by Automix to learn the identity of the device requesting to stream audio, for those services that require it."},{"text":" ","type":"text"},{"type":"text","text":"An example would be, a service that only allows one device to stream at any one time, would need to know the identity of the device to provide the stream."}],"kind":"symbol","required":true,"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/getDeviceIdentifier()"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDK/initialised()":{"abstract":[{"text":"Returns the initialised status of the Automix SDK.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdk\/initialised()","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDK\/initialised()","type":"topic","title":"initialised()","kind":"symbol","navigatorTitle":[{"text":"initialised","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialised"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","url":"\/documentation\/automixiq","title":"AutomixIQ","abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content.","type":"text"}],"url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"AutomixSDKStreamingDelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate/syncGetCachedTrack(trackId:)":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"syncGetCachedTrackWithTrackId:"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate\/syncGetCachedTrack(trackId:)","abstract":[{"type":"text","text":"Called by AutomixIQ before attempting to download a track to allow the client to provide any cached track data, return nil if not available."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"syncGetCachedTrack"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"syncGetCachedTrack(trackId:)","role":"symbol","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate\/syncgetcachedtrack(trackid:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKLogLevel"],"title":"Initializing AutomixIQ for use with a custom backend","generated":true}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","value":"AutomixSDKStatusObserverDelegate","op":"replace"},{"value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","op":"replace"},{"value":"asyncGetTrackMetadataWithTrackId:completion:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetTrackMetadata(trackId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asyncGetTrackMetadataWithTrackId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/title","op":"replace","value":"AutomixSDKLogLevel"},{"value":[{"text":"AutomixSDKLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKLogLevel\/fragments","op":"replace"},{"value":"trackDownloadProgressChangedWithTrackId:progress:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadProgressChanged(trackId:progress:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackDownloadProgressChangedWithTrackId:progress:"}]},{"value":"syncGetTrackMetadataWithTrackId:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetTrackMetadata(trackId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"syncGetTrackMetadataWithTrackId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetTrackMetadata(trackId:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/title","op":"replace","value":"asyncCheckDeviceStatusWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncCheckDeviceStatus(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"asyncCheckDeviceStatusWithCompletion:","kind":"identifier"}]},{"value":"trackDownloadCompletedWithTrackId:data:","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1trackDownloadCompleted(trackId:data:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"trackDownloadCompletedWithTrackId:data:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/title","op":"replace","value":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1asyncGetStream(streamingDeviceId:sessionId:trackId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"asyncGetStreamWithStreamingDeviceId:sessionId:trackId:completion:"}]},{"value":"isLoggedIn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1isLoggedIn()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1isLoggedIn()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isLoggedIn","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1getDeviceIdentifier()\/title","value":"getDeviceIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1getDeviceIdentifier()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getDeviceIdentifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialised()\/title","value":"initialised"},{"value":[{"kind":"text","text":"+ "},{"text":"initialised","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDK~1initialised()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","op":"replace","value":"AutomixSDKStreamingDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]},{"value":"syncGetCachedTrackWithTrackId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate~1syncGetCachedTrack(trackId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"syncGetCachedTrackWithTrackId:","kind":"identifier"}],"op":"replace"}]}]}