{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/radioUIFontSizeMatchMachine","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizematchmachine"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizematchmachine"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKUIConfig(py)radioUIFontSizeMatchMachine","roleHeading":"Instance Property","modules":[{"name":"PacemakerRadio"}],"title":"radioUIFontSizeMatchMachine","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeMatchMachine"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig/radioUIFontSizeMatchMachine":{"title":"radioUIFontSizeMatchMachine","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIFontSizeMatchMachine","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig\/radiouifontsizematchmachine","navigatorTitle":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig\/radioUIFontSizeMatchMachine","kind":"symbol","abstract":[]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","title":"PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","role":"collection","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKUIConfig":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKUIConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RadioSDKUIConfig","kind":"identifier"}],"title":"RadioSDKUIConfig","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RadioSDKUIConfig"}],"url":"\/documentation\/pacemakerradio\/radiosdkuiconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"radioUIFontSizeMatchMachine","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeMatchMachine","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1radioUIFontSizeMatchMachine\/title","value":"radioUIFontSizeMatchMachine","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig~1radioUIFontSizeMatchMachine\/fragments","op":"replace","value":[{"text":"radioUIFontSizeMatchMachine","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/title","value":"RadioSDKUIConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/fragments","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKUIConfig\/navigatorTitle","value":[{"text":"RadioSDKUIConfig","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}