{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters\/mixMlScore"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mixMlScore","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixmlscore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixmlscore"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKMixtapeCounters(py)mixMlScore","navigatorTitle":[{"text":"mixMlScore","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mixMlScore","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"title":"mixMlScore","symbolKind":"property"},"abstract":[{"type":"text","text":"The likelyhood this mixtape will be liked according to some ML model"}],"kind":"symbol","references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters/mixMlScore":{"url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters\/mixmlscore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The likelyhood this mixtape will be liked according to some ML model"}],"title":"mixMlScore","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters\/mixMlScore","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mixMlScore"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"mixMlScore"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","title":"AutomixSDKMixtapeCounters","url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","type":"topic","abstract":[{"type":"text","text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"navigatorTitle":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"mixMlScore","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"mixMlScore","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"mixMlScore","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters~1mixMlScore\/title","op":"replace","value":"mixMlScore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters~1mixMlScore\/fragments","value":[{"kind":"identifier","text":"mixMlScore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}