{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialise"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"streamingDelegate"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"? = nil)"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkobjc\/initialise(with:statusdelegate:countrycode:storeid:applicationid:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC"]]},"metadata":{"title":"initialise(with:statusDelegate:countryCode:storeId:applicationId:completion:)","modules":[{"name":"AutomixIQ"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","text":"AutomixSDKStreamingDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)AutomixSDKObjC(cm)initialiseWithStreamingDelegate:statusDelegate:countryCode:storeId:applicationId:completion:","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(with:statusDelegate:countryCode:storeId:applicationId:completion:)"},"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC/initialise(with:statusDelegate:countryCode:storeId:applicationId:completion:)":{"title":"initialise(with:statusDelegate:countryCode:storeId:applicationId:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(with:statusDelegate:countryCode:storeId:applicationId:completion:)","url":"\/documentation\/automixiq\/automixsdkobjc\/initialise(with:statusdelegate:countrycode:storeid:applicationid:completion:)","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompletionWithError"}],"abstract":[],"type":"topic","role":"symbol","title":"CompletionWithError","navigatorTitle":[{"kind":"identifier","text":"CompletionWithError"}],"url":"\/documentation\/automixiq\/completionwitherror"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"type":"topic","title":"AutomixSDKStatusObserverDelegate","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented by a class tasked with observing the status of the AutomixIQ SDK to reflect it on a UI."}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"kind":"symbol","url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","role":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"title":"AutomixIQ","kind":"symbol","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","role":"collection","url":"\/documentation\/automixiq","type":"topic","abstract":[{"text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStreamingDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStreamingDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"title":"AutomixSDKStreamingDelegate","url":"\/documentation\/automixiq\/automixsdkstreamingdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"abstract":[{"text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the information it requires to play content.","type":"text"},{"text":" ","type":"text"},{"text":"See TunedDemoStreamingHandler for an example of an object implementing this protocol.","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKObjC"}],"abstract":[],"type":"topic","role":"symbol","title":"AutomixSDKObjC","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKObjC"}],"url":"\/documentation\/automixiq\/automixsdkobjc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","op":"replace","value":"AutomixSDKStatusObserverDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStreamingDelegate\/fragments"}]}]}