{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKPlaylistOperation(im)init","role":"symbol","symbolKind":"method","modules":[{"name":"PacemakerRadio"}],"title":"init"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation\/init"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/pacemakerradio\/automixsdkplaylistoperation\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation/init":{"kind":"symbol","title":"init","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation\/init"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"type":"topic","kind":"symbol","url":"\/documentation\/pacemakerradio","title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"abstract":[{"type":"text","text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist."}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","title":"AutomixSDKPlaylistOperation","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}]},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}