{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playing"]},{"paths":["\/documentation\/pacemakerradio\/automixsdkstatus\/playing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playing","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playing"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Represents if sound is playing from Automix SDK, true if it is, false otherwise.","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"property","title":"playing","roleHeading":"Instance Property","externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKStatus(py)playing","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"text":"playing","kind":"identifier"}],"role":"symbol"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","role":"symbol","title":"AutomixSDKStatus","abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"url":"\/documentation\/pacemakerradio\/automixsdkstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKStatus"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"type":"topic","kind":"symbol","title":"PacemakerRadio","role":"collection","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","url":"\/documentation\/pacemakerradio"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus/playing":{"url":"\/documentation\/pacemakerradio\/automixsdkstatus\/playing","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus\/playing","abstract":[{"type":"text","text":"Represents if sound is playing from Automix SDK, true if it is, false otherwise."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"playing"}],"type":"topic","title":"playing","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playing"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"playing","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"playing","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"playing","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"AutomixSDKStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playing\/title","value":"playing","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus~1playing\/fragments","op":"replace","value":[{"kind":"identifier","text":"playing"}]}]}]}