{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/automixiq\/automixsdkobjc\/initialise(withapikey:tuneddelegate:statusdelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ","doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(withAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"},"metadata":{"title":"initialise(withAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","roleHeading":"Type Method","modules":[{"name":"AutomixIQ"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialise"},{"kind":"text","text":"("},{"text":"withAPIKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tunedDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","text":"CompletionWithError"},{"kind":"text","text":"?)"}],"externalID":"c:objc(cs)AutomixSDKObjC(cm)initialiseWithAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAPIKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"apiKey","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","text":"CompletionWithError","preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError"},{"text":"? = nil)","kind":"text"}]}]}],"references":{"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedMusicCacheDelegate":{"navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"title":"TunedMusicCacheDelegate","url":"\/documentation\/automixiq\/tunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedMusicCacheDelegate","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"abstract":[{"text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data","type":"text"}]},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ":{"abstract":[{"type":"text","text":"Enable smooth transitions between tracks for a seamlessly beat-matched experience within your iOS music application."}],"role":"collection","kind":"symbol","url":"\/documentation\/automixiq","title":"AutomixIQ","type":"topic","identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKStatusObserverDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI."}],"url":"\/documentation\/automixiq\/automixsdkstatusobserverdelegate","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"role":"symbol","title":"AutomixSDKStatusObserverDelegate","type":"topic"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC/initialise(withAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)":{"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC\/initialise(withAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialise","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAPIKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tunedDelegate"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedRestDelegate","text":"TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@AutomixIQ@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":")?, "},{"text":"countryCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@AutomixIQ@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:AutomixSDK.h@T@CompletionWithError","kind":"typeIdentifier","text":"CompletionWithError"},{"text":"?)","kind":"text"}],"url":"\/documentation\/automixiq\/automixsdkobjc\/initialise(withapikey:tuneddelegate:statusdelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"initialise(withAPIKey:tunedDelegate:statusDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/CompletionWithError":{"abstract":[],"role":"symbol","url":"\/documentation\/automixiq\/completionwitherror","navigatorTitle":[{"text":"CompletionWithError","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"CompletionWithError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/CompletionWithError","title":"CompletionWithError","type":"topic","kind":"symbol"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/TunedRestDelegate":{"title":"TunedRestDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TunedRestDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/TunedRestDelegate","type":"topic","url":"\/documentation\/automixiq\/tunedrestdelegate"},"doc://org.cocoapods.AutomixIQ/documentation/AutomixIQ/AutomixSDKObjC":{"type":"topic","kind":"symbol","url":"\/documentation\/automixiq\/automixsdkobjc","navigatorTitle":[{"text":"AutomixSDKObjC","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AutomixIQ\/documentation\/AutomixIQ\/AutomixSDKObjC","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKObjC","kind":"identifier"}],"role":"symbol","title":"AutomixSDKObjC","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/title","value":"TunedMusicCacheDelegate"},{"value":[{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedMusicCacheDelegate\/fragments"},{"value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1AutomixSDKStatusObserverDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/title","value":"TunedRestDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.AutomixIQ~1documentation~1AutomixIQ~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}