{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allowInvites","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/allowInvites","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"allowInvites","navigatorTitle":[{"kind":"identifier","text":"allowInvites"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"PacemakerRadio"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)allowInvites","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allowInvites","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/allowinvites"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/allowinvites"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/allowInvites":{"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/allowinvites","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowInvites"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowInvites","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"allowInvites","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/allowInvites","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"allowInvites","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"allowInvites"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowInvites"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1allowInvites\/title","value":"allowInvites","op":"replace"},{"value":[{"kind":"identifier","text":"allowInvites"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1allowInvites\/fragments"},{"value":"RadioSDKConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"}]}]}