{"metadata":{"title":"init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowFX"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowAudioEffects"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowBackgrounds"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"allowCommenting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"allowVoiceOver","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowSongSuggestions"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowInvites"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"allowStudio","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fontFamily","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"titleFontSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeHuge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeLarge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeSmall"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"textFieldFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"textFieldBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldPlaceholderTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogTitleFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogTitleTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"dialogDescriptionTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonBorderRadius"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBorder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":")"}],"externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(im)initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","navigatorTitle":[{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"}],"roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"PacemakerRadio"}]},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:fontfamily:titlefontsize:radiouifontsizehuge:radiouifont-1z5df"]},{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:fontfamily:titlefontsize:radiouifontsizehuge:radiouifont-1z5df"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"country"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"allowFX","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true, "},{"text":"allowAudioEffects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"allowBackgrounds"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = true, "},{"text":"allowCommenting","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"text":"allowVoiceOver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"allowSongSuggestions","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = true, ","kind":"text"},{"text":"allowInvites","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"allowPublicBroadcasts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = true, ","kind":"text"},{"text":"allowStudio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"fontFamily"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" = \"HelveticaNeue\", ","kind":"text"},{"text":"titleFontSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" = 14, "},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 40, "},{"kind":"externalParam","text":"radioUIFontSizeLarge"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 16, ","kind":"text"},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 14, ","kind":"text"},{"kind":"externalParam","text":"radioUIFontSizeSmall"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":" = 12, ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 10, "},{"kind":"externalParam","text":"radioUIFontSizeMatchMachine"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 20, ","kind":"text"},{"text":"textFieldFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.init(white: 0.2, alpha: 1), "},{"text":"textFieldBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":" = 5, "},{"text":"textFieldTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = UIColor.white, "},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = UIColor.black, "},{"text":"dialogTitleFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"dialogTitleTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogDescriptionFontBold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"dialogDescriptionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonFontBold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" = UIColor.clear, ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":" = -1, "},{"kind":"externalParam","text":"dialogPrimaryButtonTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true, ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" = UIColor.white, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonFontBold"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" = UIColor.clear, ","kind":"text"},{"text":"dialogSecondaryButtonBorderRadius","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":" = -1, ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" = UIColor.white, ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"dialogSecondaryButtonBorderColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" = UIColor.clear)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/init(apikey:country:storeid:applicationid:allowfx:allowaudioeffects:allowbackgrounds:allowcommenting:allowvoiceover:allowsongsuggestions:allowinvites:allowpublicbroadcasts:allowstudio:fontfamily:titlefontsize:radiouifontsizehuge:radiouifont-1z5df","kind":"symbol","navigatorTitle":[{"text":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowFX"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"allowAudioEffects","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowBackgrounds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowCommenting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowVoiceOver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowSongSuggestions"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowInvites"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"allowPublicBroadcasts","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowStudio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"fontFamily","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"titleFontSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIFontSizeHuge"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeLarge","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeRegular","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"radioUIFontSizeSmall","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIFontSizeMatchMachine","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textFieldFontBold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textFieldBackgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"textFieldBorderRadius","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":", ","kind":"text"},{"text":"textFieldTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textFieldPlaceholderTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogTitleFontBold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogTitleTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"dialogDescriptionFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogDescriptionTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonFontBold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorderRadius"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogPrimaryButtonTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogPrimaryButtonBorder"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogPrimaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonFontBold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dialogSecondaryButtonBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dialogSecondaryButtonBorderRadius"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dialogSecondaryButtonBorder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dialogSecondaryButtonBorderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"title":"init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithApiKey:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"apiKey","kind":"internalParam"},{"kind":"text","text":" "},{"text":"country:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"country","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storeId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"storeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"applicationId"},{"kind":"text","text":" "},{"text":"allowFX:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"allowFX"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAudioEffects:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowAudioEffects","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowBackgrounds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"allowBackgrounds"},{"kind":"text","text":" "},{"text":"allowCommenting:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"allowCommenting","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowVoiceOver:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"allowVoiceOver"},{"kind":"text","text":" "},{"text":"allowSongSuggestions:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"allowSongSuggestions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowInvites:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"allowInvites"},{"kind":"text","text":" "},{"text":"allowPublicBroadcasts:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowPublicBroadcasts","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowStudio:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowStudio"},{"text":" ","kind":"text"},{"text":"fontFamily:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"fontFamily","kind":"internalParam"},{"kind":"text","text":" "},{"text":"titleFontSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"titleFontSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeHuge:"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"radioUIFontSizeHuge"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeLarge:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeLarge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeRegular:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeRegular","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeSmall:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"text":"radioUIFontSizeSmall","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeTiny:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"radioUIFontSizeTiny","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"radioUIFontSizeMatchMachine:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"radioUIFontSizeMatchMachine"},{"text":" ","kind":"text"},{"text":"textFieldFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"textFieldFontBold"},{"kind":"text","text":" "},{"text":"textFieldBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textFieldBackgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldBorderRadius:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"textFieldBorderRadius"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldTextColor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textFieldTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldPlaceholderTextColor:"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textFieldPlaceholderTextColor"},{"kind":"text","text":" "},{"text":"dialogTitleFontBold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogTitleFontBold"},{"text":" ","kind":"text"},{"text":"dialogTitleTextColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dialogTitleTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogDescriptionFontBold:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogDescriptionFontBold"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogDescriptionTextColor:"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogDescriptionTextColor"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonFontBold:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogPrimaryButtonFontBold"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBackgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dialogPrimaryButtonBackgroundColor"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonBorderRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dialogPrimaryButtonBorderRadius","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dialogPrimaryButtonTextColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dialogPrimaryButtonTextColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogPrimaryButtonBorder:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogPrimaryButtonBorder"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogPrimaryButtonBorderColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogPrimaryButtonBorderColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dialogSecondaryButtonFontBold:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonFontBold"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonBackgroundColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" *) ","kind":"text"},{"text":"dialogSecondaryButtonBackgroundColor","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonBorderRadius:"},{"text":"(","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dialogSecondaryButtonBorderRadius"},{"kind":"text","text":" "},{"text":"dialogSecondaryButtonTextColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonTextColor"},{"text":" ","kind":"text"},{"text":"dialogSecondaryButtonBorder:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"dialogSecondaryButtonBorder","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dialogSecondaryButtonBorderColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dialogSecondaryButtonBorderColor"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/title","value":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1init(apiKey:country:storeId:applicationId:allowFX:allowAudioEffects:allowBackgrounds:allowCommenting:allowVoiceOver:allowSongSuggestions:allowInvites:allowPublicBroadcasts:allowStudio:fontFamily:titleFontSize:radioUIFontSizeHuge:radioUIFontSizeLarge:radioUIFontSizeRegular:radioUIFontSizeSmall:radioUIFontSizeTiny:radioUIFontSizeMatchMachine:textFieldFontBold:textFieldBackgroundColor:textFieldBorderRadius:textFieldTextColor:textFieldPlaceholderTextColor:dialogTitleFontBold:dialogTitleTextColor:dialogDescriptionFontBold:dialogDescriptionTextColor:dialogPrimaryButtonFontBold:dialogPrimaryButtonBackgroundColor:dialogPrimaryButtonBorderRadius:dialogPrimaryButtonTextColor:dialogPrimaryButtonBorder:dialogPrimaryButtonBorderColor:dialogSecondaryButtonFontBold:dialogSecondaryButtonBackgroundColor:dialogSecondaryButtonBorderRadius:dialogSecondaryButtonTextColor:dialogSecondaryButtonBorder:dialogSecondaryButtonBorderColor:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig","op":"replace"},{"value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments"},{"op":"replace","value":[{"text":"RadioSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"}]}]}