{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/radioUIFontSizeRegular"},"metadata":{"roleHeading":"Instance Property","title":"radioUIFontSizeRegular","symbolKind":"property","role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)radioUIFontSizeRegular","navigatorTitle":[{"text":"radioUIFontSizeRegular","kind":"identifier"}],"modules":[{"name":"PacemakerRadio"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizeregular"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizeregular"]}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/radioUIFontSizeRegular":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/radioUIFontSizeRegular","title":"radioUIFontSizeRegular","type":"topic","url":"\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizeregular","navigatorTitle":[{"text":"radioUIFontSizeRegular","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"radioUIFontSizeRegular","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"radioUIFontSizeRegular"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"radioUIFontSizeRegular","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeRegular"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1radioUIFontSizeRegular\/title","value":"radioUIFontSizeRegular"},{"op":"replace","value":[{"text":"radioUIFontSizeRegular","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1radioUIFontSizeRegular\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","value":"RadioSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"value":[{"text":"RadioSDKConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle","op":"replace"}]}]}