{"metadata":{"roleHeading":"Instance Property","title":"radioUIFontSizeSmall","symbolKind":"property","role":"symbol","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)radioUIFontSizeSmall","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeSmall"}],"modules":[{"name":"PacemakerRadio"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"radioUIFontSizeSmall"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizesmall"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizesmall"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/radioUIFontSizeSmall","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"radioUIFontSizeSmall"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"sections":[],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/radioUIFontSizeSmall":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"radioUIFontSizeSmall"}],"abstract":[],"kind":"symbol","title":"radioUIFontSizeSmall","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/radioUIFontSizeSmall","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"radioUIFontSizeSmall","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/radiouifontsizesmall"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"radioUIFontSizeSmall","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"radioUIFontSizeSmall","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"radioUIFontSizeSmall","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title","op":"replace","value":"RadioSDKConfig"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"value":[{"text":"RadioSDKConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle"},{"value":"radioUIFontSizeSmall","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1radioUIFontSizeSmall\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1radioUIFontSizeSmall\/fragments","op":"replace","value":[{"text":"radioUIFontSizeSmall","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}