{"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"PacemakerRadio"}],"title":"textFieldBorderRadius","externalID":"c:@M@PacemakerRadio@objc(cs)RadioSDKConfig(py)textFieldBorderRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"textFieldBorderRadius","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"textFieldBorderRadius","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldBorderRadius"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/textfieldborderradius"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pacemakerradio\/radiosdkconfig\/textfieldborderradius"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/textFieldBorderRadius"},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKConfig","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKConfig"}],"title":"RadioSDKConfig","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkconfig","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig","kind":"symbol","type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","role":"collection","type":"topic","title":"PacemakerRadio","kind":"symbol","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKConfig/textFieldBorderRadius":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textFieldBorderRadius"}],"url":"\/documentation\/pacemakerradio\/radiosdkconfig\/textfieldborderradius","kind":"symbol","title":"textFieldBorderRadius","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKConfig\/textFieldBorderRadius","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textFieldBorderRadius","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"textFieldBorderRadius","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"textFieldBorderRadius","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"text":"textFieldBorderRadius","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"RadioSDKConfig","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/fragments","value":[{"kind":"identifier","text":"RadioSDKConfig"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig\/navigatorTitle","op":"replace","value":[{"text":"RadioSDKConfig","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1textFieldBorderRadius\/title","value":"textFieldBorderRadius","op":"replace"},{"op":"replace","value":[{"text":"textFieldBorderRadius","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioSDKConfig~1textFieldBorderRadius\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}