{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkobjc\/getautomixstreamingdelegate()"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC"]]},"metadata":{"title":"getAutomixStreamingDelegate()","roleHeading":"Instance Method","externalID":"c:objc(cs)RadioSDKObjC(im)getAutomixStreamingDelegate","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"text":"AutomixSDKStreamingDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate"}],"symbolKind":"method","role":"symbol","modules":[{"name":"PacemakerRadio"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/getAutomixStreamingDelegate()":{"title":"getAutomixStreamingDelegate()","abstract":[],"url":"\/documentation\/pacemakerradio\/radiosdkobjc\/getautomixstreamingdelegate()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAutomixStreamingDelegate","kind":"identifier"},{"text":"() -> any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStreamingDelegate","kind":"typeIdentifier","text":"AutomixSDKStreamingDelegate"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/getAutomixStreamingDelegate()","kind":"symbol","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKObjC","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}],"abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc","title":"RadioSDKObjC"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStreamingDelegate":{"navigatorTitle":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkstreamingdelegate","type":"topic","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStreamingDelegate","abstract":[{"type":"text","text":"AutomixSDKStreamingDelegate protocol defines the methods to be implemented with providing AutomixIQ the information it requires to play content."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AutomixSDKStreamingDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/title","value":"AutomixSDKStreamingDelegate"},{"value":[{"text":"AutomixSDKStreamingDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStreamingDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKStreamingDelegate"}]}]}]}