{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(withAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/radiosdkobjc\/initialize(withapikey:tuneddelegate:statusdelegate:radiouidelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAPIKey"},{"kind":"text","text":" "},{"text":"apiKey","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"text":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"RadioUIDelegate","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate"},{"kind":"text","text":", "},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"musicCacheDelegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","text":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (((any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAPIKey"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"apiKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"radioUIDelegate"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","kind":"typeIdentifier","text":"RadioUIDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"countryCode"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"musicCacheDelegate","kind":"externalParam"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"text":")?) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"title":"initialize(withAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"PacemakerRadio"}],"externalID":"c:objc(cs)RadioSDKObjC(cm)initializeWithAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"withAPIKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"tunedDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","text":"AutomixSDKStatusObserverDelegate"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"radioUIDelegate"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate","text":"RadioUIDelegate"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"applicationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"musicCacheDelegate","kind":"externalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"TunedMusicCacheDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}]},"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioUIDelegate":{"url":"\/documentation\/pacemakerradio\/radiouidelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioUIDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"RadioUIDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioUIDelegate","type":"topic","title":"RadioUIDelegate","kind":"symbol","abstract":[{"type":"text","text":"RadioUIDelegate protocol defines the methods to be implemented by a class tasked with providing the Automix SDK the user interface requires for social features."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatusObserverDelegate":{"role":"symbol","abstract":[{"text":"AutomixSDKStatusObserverDelegate protocol defines the methods to be implemented with observing the status of AutomixIQ to reflect it on a UI.","type":"text"}],"title":"AutomixSDKStatusObserverDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkstatusobserverdelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatusObserverDelegate"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedMusicCacheDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedMusicCacheDelegate"}],"role":"symbol","navigatorTitle":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/tunedmusiccachedelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedMusicCacheDelegate","kind":"symbol","abstract":[{"type":"text","text":"TunedMusicCacheDelegate protocol defines the methods to be implemented with storing and providing cached track data"}],"title":"TunedMusicCacheDelegate"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedRestDelegate":{"title":"TunedRestDelegate","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedRestDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TunedRestDelegate"}],"kind":"symbol","abstract":[{"type":"text","text":"TunedRestDelegate protocol defines the methods to be implemented that will provide AutomixIQ the credentials and identifiers to Tuned Global’s backend"}],"url":"\/documentation\/pacemakerradio\/tunedrestdelegate","role":"symbol","navigatorTitle":[{"text":"TunedRestDelegate","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"kind":"symbol","title":"PacemakerRadio","url":"\/documentation\/pacemakerradio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","role":"collection","abstract":[{"type":"text","text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ."}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RadioSDKObjC","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RadioSDKObjC"}],"abstract":[],"role":"symbol","url":"\/documentation\/pacemakerradio\/radiosdkobjc","title":"RadioSDKObjC"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/RadioSDKObjC/initialize(withAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/RadioSDKObjC\/initialize(withAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","url":"\/documentation\/pacemakerradio\/radiosdkobjc\/initialize(withapikey:tuneddelegate:statusdelegate:radiouidelegate:countrycode:storeid:applicationid:musiccachedelegate:completion:)","title":"initialize(withAPIKey:tunedDelegate:statusDelegate:radioUIDelegate:countryCode:storeId:applicationId:musicCacheDelegate:completion:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"withAPIKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tunedDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"TunedRestDelegate","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedRestDelegate","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"statusDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)AutomixSDKStatusObserverDelegate","kind":"typeIdentifier","text":"AutomixSDKStatusObserverDelegate"},{"kind":"text","text":", "},{"text":"radioUIDelegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"RadioUIDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)RadioUIDelegate"},{"kind":"text","text":", "},{"text":"countryCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"applicationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"musicCacheDelegate"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(pl)TunedMusicCacheDelegate","kind":"typeIdentifier","text":"TunedMusicCacheDelegate"},{"kind":"text","text":")?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (((any "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}]}},"variantOverrides":[{"patch":[{"value":"RadioUIDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/fragments","value":[{"text":"RadioUIDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RadioUIDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1RadioUIDelegate\/navigatorTitle"},{"value":"AutomixSDKStatusObserverDelegate","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/fragments","value":[{"text":"AutomixSDKStatusObserverDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatusObserverDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKStatusObserverDelegate"}]},{"value":"TunedMusicCacheDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/title"},{"op":"replace","value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/fragments"},{"value":[{"text":"TunedMusicCacheDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedMusicCacheDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/title","value":"TunedRestDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/fragments","value":[{"text":"TunedRestDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TunedRestDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedRestDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}