{"seeAlsoSections":[{"anchor":"Data-models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"generated":true,"title":"Data models"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel"]},{"paths":["\/documentation\/pacemakerradio\/automixsdktrackmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@PacemakerRadio@objc(cs)AutomixSDKTrackModel","roleHeading":"Class","title":"AutomixSDKTrackModel","modules":[{"name":"PacemakerRadio"}],"navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKTrackModel","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}]}]}],"sections":[],"abstract":[{"text":"AutomixSDKTrackModel models a track. This metadata is required.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(from:)","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Artists","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Duration-24vp","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Image","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/IsExplicit-7zkjp","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Name","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/ReleaseName","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/TrackId","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/TrackNumber-76etb","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/bpm","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/duration-3eh2u","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/isExplicit-55j45","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/key","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackNumber-6peuy"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject","doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.PacemakerRadio\/Se","doc:\/\/org.cocoapods.PacemakerRadio\/SE","doc:\/\/org.cocoapods.PacemakerRadio\/SQ","doc:\/\/org.cocoapods.PacemakerRadio\/SH"],"kind":"relationships"}],"references":{"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/ReleaseName":{"title":"ReleaseName","abstract":[{"type":"text","text":"The name of the album this track belongs to"}],"navigatorTitle":[{"text":"ReleaseName","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/ReleaseName","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/releasename","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReleaseName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"type":"topic"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeCounters":{"title":"AutomixSDKMixtapeCounters","kind":"symbol","abstract":[{"text":"AutomixSDKMixtapeCounters models the set of counters for information about a mixtape","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","type":"topic","navigatorTitle":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapecounters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKArtistModel":{"type":"topic","title":"AutomixSDKArtistModel","abstract":[{"type":"text","text":"AutomixSDKArtistModel models an artist."}],"url":"\/documentation\/pacemakerradio\/automixsdkartistmodel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKArtistModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/TrackNumber-76etb":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/TrackNumber-76etb","title":"TrackNumber","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/tracknumber-76etb","kind":"symbol","abstract":[{"type":"text","text":"The index of this track in the album it belongs to"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/init(from:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/init(from:)","kind":"symbol","title":"init(from:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(from:)"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/Data-models-article":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","kind":"article","abstract":[{"text":"How data is passed to and from PacemakerRadio","type":"text"}],"title":"Data models","type":"topic","url":"\/documentation\/pacemakerradio\/data-models-article","role":"article"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","title":"init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)","type":"topic","navigatorTitle":[{"text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/init(trackid:artistname:name:duration:isexplicit:tracknumber:releasename:key:tempo:image:)","kind":"symbol","abstract":[{"type":"text","text":"Initialises a Track Model"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"trackId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"artistName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"isExplicit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"trackNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"releaseName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"tempo","kind":"externalParam"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.PacemakerRadio/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(pl)NSObject"},"doc://org.cocoapods.PacemakerRadio/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SH"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformModel":{"title":"AutomixSDKWaveformModel","kind":"symbol","abstract":[{"text":"AutomixSDKWaveformModel models the waveform of a track.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","navigatorTitle":[{"text":"AutomixSDKWaveformModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdkwaveformmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"role":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPlaylistOperation":{"type":"topic","title":"AutomixSDKPlaylistOperation","abstract":[{"text":"AutomixSDKPlaylistOperation models a move, add or remove operation of a track in a playlist.","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkplaylistoperation","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation","navigatorTitle":[{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPlaylistOperation","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/TunedAuthenticationResponse":{"type":"topic","title":"TunedAuthenticationResponse","abstract":[{"text":"TunedAuthenticationResponse models the response of a Tuned OAuth request","type":"text"}],"url":"\/documentation\/pacemakerradio\/tunedauthenticationresponse","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","navigatorTitle":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TunedAuthenticationResponse","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/isExplicit-55j45":{"role":"symbol","navigatorTitle":[{"text":"isExplicit","kind":"identifier"}],"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/isexplicit-55j45","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isExplicit"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Objective-C accessible member for IsExplicit","type":"text"}],"title":"isExplicit","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/isExplicit-55j45"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/bpm":{"abstract":[{"type":"text","text":"Objective-C accessible member for the bpm, 09 if unavailable"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/bpm","title":"bpm","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bpm"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","navigatorTitle":[{"text":"bpm","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/bpm"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/trackNumber-6peuy":{"abstract":[{"text":"Objective-C accessible member for the track number","type":"text"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackNumber-6peuy","type":"topic","title":"trackNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"trackNumber"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/tracknumber-6peuy"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKWaveformBlob":{"abstract":[{"type":"text","text":"AutomixSDKWaveformBlob models the data to create a waveform shape representing a track"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkwaveformblob","navigatorTitle":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"type":"topic","title":"AutomixSDKWaveformBlob","role":"symbol"},"doc://org.cocoapods.PacemakerRadio/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/TrackId":{"title":"TrackId","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/TrackId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"TrackId","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/trackid","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The identifier of a track as an integer"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/Artists":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"Artists","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@PacemakerRadio@objc(cs)AutomixSDKArtistModel","text":"AutomixSDKArtistModel","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/artists","kind":"symbol","role":"symbol","abstract":[{"text":"The artists of a track - the first one is the one to be presented by a UI","type":"text"}],"navigatorTitle":[{"text":"Artists","kind":"identifier"}],"title":"Artists","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Artists"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/duration-3eh2u":{"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/duration-3eh2u","navigatorTitle":[{"text":"duration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Objective-C accessible member for the track duration"}],"title":"duration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"duration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/duration-3eh2u"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel":{"type":"topic","title":"AutomixSDKTrackModel","abstract":[{"type":"text","text":"AutomixSDKTrackModel models a track. This metadata is required."}],"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel","navigatorTitle":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKList":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKList","kind":"identifier"}],"abstract":[],"title":"AutomixSDKList","url":"\/documentation\/pacemakerradio\/automixsdklist","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","navigatorTitle":[{"text":"AutomixSDKList","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrackImage":{"type":"topic","title":"AutomixSDKMixtapeTrackImage","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrackImage models the image for a track in a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrackimage","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","navigatorTitle":[{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeTrackImage","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeLite":{"type":"topic","title":"AutomixSDKMixtapeLite","abstract":[{"type":"text","text":"AutomixSDKMixtapeLite models a mixtape with the minimum required fields"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapelite","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","navigatorTitle":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKMixtapeLite","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/Name":{"url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/name","kind":"symbol","abstract":[{"text":"The title of a track","type":"text"}],"navigatorTitle":[{"text":"Name","kind":"identifier"}],"title":"Name","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Name","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"Name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKPluginMetadataModel":{"type":"topic","title":"AutomixSDKPluginMetadataModel","abstract":[{"type":"text","text":"AutomixSDKPluginMetadataModel models metadata of a track traditionally obtained by running plugins on it. Key and BPM are recommented for best mixing."},{"type":"text","text":" "},{"text":"The Type entry for bpm and key are “key” and “bpm” (case sensitive) respectively, the values need to be formatted as strings, and the key needs to be in OpenKey format.","type":"text"}],"url":"\/documentation\/pacemakerradio\/automixsdkpluginmetadatamodel","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtape":{"abstract":[{"text":"AutomixSDKMixtape models a mixtape","type":"text"}],"title":"AutomixSDKMixtape","url":"\/documentation\/pacemakerradio\/automixsdkmixtape","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKMixtape"}],"navigatorTitle":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","role":"symbol","type":"topic","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/IsExplicit-7zkjp":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IsExplicit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/IsExplicit-7zkjp","abstract":[{"type":"text","text":"true if the track is explicit, false otherwise"}],"title":"IsExplicit","type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/isexplicit-7zkjp"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKUser":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKUser"}],"title":"AutomixSDKUser","url":"\/documentation\/pacemakerradio\/automixsdkuser","abstract":[{"text":"AutomixSDKUser models a user","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AutomixSDKUser","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/SE":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/SE","title":"Swift.Encodable"},"doc://org.cocoapods.PacemakerRadio/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKMixtapeTrack":{"kind":"symbol","abstract":[{"type":"text","text":"AutomixSDKMixtapeTrack models a track in a mixtape"}],"url":"\/documentation\/pacemakerradio\/automixsdkmixtapetrack","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","title":"AutomixSDKMixtapeTrack","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/Duration-24vp":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/duration-24vp","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Duration-24vp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":"?","kind":"text"}],"role":"symbol","title":"Duration","kind":"symbol","abstract":[{"text":"The duration of a track in seconds","type":"text"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio":{"title":"PacemakerRadio","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio","type":"topic","url":"\/documentation\/pacemakerradio","abstract":[{"text":"Broadcast your playlist, mix, or set along with your voice, to the world. Tune in to other broadcasts and jump in the conversation with comments, or show your support with quick reactions. An interactive UI for AutomixIQ.","type":"text"}],"role":"collection","kind":"symbol"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKStatus":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AutomixSDKStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AutomixSDKStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"AutomixSDKStatus models the State of the AutomixSDK during playback."}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkstatus","title":"AutomixSDKStatus"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/key":{"abstract":[{"type":"text","text":"Objective-C accessible member for the key, nil if unavailable"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/key","title":"key","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"key","kind":"identifier"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/key"},"doc://org.cocoapods.PacemakerRadio/Se":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/Image":{"abstract":[{"type":"text","text":"The url of the artwork image for this track as a String"}],"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Image","title":"Image","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"role":"symbol","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/image"},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKTrackModel/trackIdentifier":{"type":"topic","url":"\/documentation\/pacemakerradio\/automixsdktrackmodel\/trackidentifier","role":"symbol","kind":"symbol","title":"trackIdentifier","identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackIdentifier","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":"Objective-C accessible member for the track identifier as String","type":"text"}],"navigatorTitle":[{"text":"trackIdentifier","kind":"identifier"}]},"doc://org.cocoapods.PacemakerRadio/documentation/PacemakerRadio/AutomixSDKGenericList":{"identifier":"doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKGenericList","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomixSDKGenericList","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutomixSDKGenericList"}],"abstract":[{"type":"text","text":"AutomixSDKGenericList models a list of things"}],"kind":"symbol","url":"\/documentation\/pacemakerradio\/automixsdkgenericlist","title":"AutomixSDKGenericList"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"AutomixSDKTrackModel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"AutomixSDKTrackModel","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Artists","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Image","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/Name","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/ReleaseName","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/bpm","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/duration-3eh2u","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/isExplicit-55j45","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/key","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackIdentifier","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/trackNumber-6peuy"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKTrackModel\/init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/objc(cs)NSObject"]}]},{"value":[{"generated":true,"title":"Data models","identifiers":["doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/Data-models-article","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKArtistModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPluginMetadataModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKStatus","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformModel","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/TunedAuthenticationResponse","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKList","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKUser","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtape","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeCounters","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeLite","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrack","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKMixtapeTrackImage","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKWaveformBlob","doc:\/\/org.cocoapods.PacemakerRadio\/documentation\/PacemakerRadio\/AutomixSDKPlaylistOperation"],"anchor":"Data-models"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutomixSDKTrackModel"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"value":"ReleaseName","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1ReleaseName\/title"},{"value":[{"text":"ReleaseName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1ReleaseName\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/title","value":"AutomixSDKMixtapeCounters","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/fragments","value":[{"text":"AutomixSDKMixtapeCounters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeCounters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKMixtapeCounters"}]},{"value":"AutomixSDKArtistModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/fragments","op":"replace","value":[{"text":"AutomixSDKArtistModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKArtistModel\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKArtistModel"}],"op":"replace"},{"value":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1init(trackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTrackId:artistName:name:duration:isExplicit:trackNumber:releaseName:key:tempo:image:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/title","value":"AutomixSDKWaveformModel"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/title","value":"AutomixSDKPlaylistOperation","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPlaylistOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AutomixSDKPlaylistOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/title","value":"TunedAuthenticationResponse"},{"value":[{"text":"TunedAuthenticationResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"TunedAuthenticationResponse"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1TunedAuthenticationResponse\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1isExplicit-55j45\/title","op":"replace","value":"isExplicit"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1isExplicit-55j45\/fragments","value":[{"kind":"identifier","text":"isExplicit"}],"op":"replace"},{"op":"replace","value":"bpm","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1bpm\/title"},{"op":"replace","value":[{"text":"bpm","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1bpm\/fragments"},{"value":"trackNumber","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1trackNumber-6peuy\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1trackNumber-6peuy\/fragments","op":"replace","value":[{"text":"trackNumber","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/title","value":"AutomixSDKWaveformBlob","op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKWaveformBlob"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKWaveformBlob","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKWaveformBlob\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Artists\/title","value":"Artists"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Artists\/fragments","op":"replace","value":[{"kind":"identifier","text":"Artists"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1duration-3eh2u\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1duration-3eh2u\/fragments","value":[{"text":"duration","kind":"identifier"}]},{"op":"replace","value":"AutomixSDKTrackModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/fragments","value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"op":"replace"},{"value":[{"kind":"identifier","text":"AutomixSDKTrackModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/title","value":"AutomixSDKList"},{"value":[{"kind":"identifier","text":"AutomixSDKList"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKList\/navigatorTitle"},{"op":"replace","value":"AutomixSDKMixtapeTrackImage","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/title"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrackImage\/navigatorTitle","value":[{"kind":"identifier","text":"AutomixSDKMixtapeTrackImage"}]},{"op":"replace","value":"AutomixSDKMixtapeLite","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/title"},{"value":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/fragments"},{"value":[{"text":"AutomixSDKMixtapeLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeLite\/navigatorTitle"},{"value":"Name","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Name\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Name\/fragments","op":"replace","value":[{"text":"Name","kind":"identifier"}]},{"value":"AutomixSDKPluginMetadataModel","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/fragments","value":[{"text":"AutomixSDKPluginMetadataModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"AutomixSDKPluginMetadataModel"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKPluginMetadataModel\/navigatorTitle","op":"replace"},{"op":"replace","value":"AutomixSDKMixtape","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/title"},{"op":"replace","value":[{"text":"AutomixSDKMixtape","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/fragments"},{"value":[{"kind":"identifier","text":"AutomixSDKMixtape"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtape\/navigatorTitle"},{"value":"AutomixSDKUser","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/title"},{"op":"replace","value":[{"text":"AutomixSDKUser","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/fragments"},{"op":"replace","value":[{"text":"AutomixSDKUser","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKUser\/navigatorTitle"},{"op":"replace","value":"AutomixSDKMixtapeTrack","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/fragments","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKMixtapeTrack\/navigatorTitle","value":[{"text":"AutomixSDKMixtapeTrack","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/title","op":"replace","value":"AutomixSDKStatus"},{"value":[{"kind":"identifier","text":"AutomixSDKStatus"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKStatus\/navigatorTitle","op":"replace","value":[{"text":"AutomixSDKStatus","kind":"identifier"}]},{"value":"key","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1key\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1key\/fragments","value":[{"text":"key","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Image\/title","value":"Image","op":"replace"},{"value":[{"text":"Image","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1Image\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1trackIdentifier\/title","value":"trackIdentifier","op":"replace"},{"op":"replace","value":[{"text":"trackIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.PacemakerRadio~1documentation~1PacemakerRadio~1AutomixSDKTrackModel~1trackIdentifier\/fragments"}]}]}